### ISSUE TITLE
coalesce operator => only php 7.+

### ISSUE THREAD

**Issue by mtrefzer** [phpMussel/phpMussel#103]
@Maikuolan With the use of the coalesce operator in latest refactoring the sources won't work for < php7 (or am I wrong?). 
Perhaps you shoud mention that in the README.

**Comment by Maikuolan** [comment]
Eep.. Good catch.

I was reading some of the PHP documentation regarding operators earlier during the week and thought I'd read that it'd been implemented since an earlier version, but I double-checked just now, and it seems I'd misread about something else. Maybe one of the hazards of reading documentation late at night when tired I guess, although I really should've caught this before going ahead and writing anything based upon it; Sorry about that.

I'm intending that the eventual phpMussel v1.0.0 release should be compatible with PHP >= 5.4.0 (full migration to PHP >= 7.0.0 should happen _eventually_, but probably not until some future v2.0.0 release in a few years or so, after PHP 7.0.0 has gained a stronger market dominance above earlier PHP versions), and so, yeah.. You're correct; Using the null coalescence operator would cause problems with trying to run phpMussel with versions of PHP < 7.0.0.

I'm going to mark this issue as a bug and revert those changes later tonight. Maybe I can reimplement them again in the future for phpMussel v2.0.0, but due to compatibility issues, they'll need to wait for a while.

**Comment by Maikuolan** [comment]
Marking as fixed and closing.

Shouldn't be a problem anymore. :-)
