### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by matteoraggi** [phpMussel/phpMussel#104]
I am using php 5.6 on my webserver, I have uploaded /phpMussel-master/ at the root of my wordpress website then I have changed the permissions of the folder vault to 777 ad then going to https://mywebsite/phpMussel-master/phpmussel.php then I receive this error: Internal Server Error.

**Comment by Maikuolan** [comment]
Hi matteoraggi,

Sorry to hear that there have been these problems.

Do you have access to your PHP error logfile (sometimes named as `error.log` or similar, usually located in a `/logs/` directory, above the `/public_html/` root)?

There could be some sensitive information in there, so, better to not share the whole file, but if have this file, could you check if there's any lines in there relating to phpMussel? If there is, this information may help us to determine exactly what has gone wrong.

Also, which version of the package did you try to install (v0.10.0, v1.0.0-DEV, etc)?

Cheers. :-)

**Comment by matteoraggi** [comment]
```
[Fri Sep 02 12:54:45 2016] [error] [client MYCONNECTIONIP] File does not exist: WEBSITEPATH/500.shtml, referer: WEBSITEPATH/phpMussel-master/
[Fri Sep 02 12:54:45 2016] [error] [client MYCONNECTIONIP] SoftException in Application.cpp:261: File "WEBSITEPATH/phpMussel-master/phpmussel.php" is writeable by group, referer: WEBSITEPATH/phpMussel-master/
[Fri Sep 02 12:54:40 2016] [error] [client MYCONNECTIONIP] client denied by server configuration: WEBSITEPATH/phpMussel-master/vault/
```

**Comment by DanielRuf** [comment]
Possibly the file permissions (chmod).

**Comment by matteoraggi** [comment]
the version should be v1.0.0 I have read it in the changelog, I dowloaded it from here few minutes ago: https://github.com/Maikuolan/phpMussel/archive/master.zip

**Comment by matteoraggi** [comment]
ok, so where do you suggest me to change the chmod? in which files and or folders?

**Comment by Maikuolan** [comment]
:+1: 

I've done some googling for the specific errors mentioned above, and based on what I've found, I suspect that your hosting company possibly may have security measures to prevent against CHMOD'ing files/directories to 777.

Via http://stackoverflow.com/questions/2900690/how-do-i-give-php-write-access-to-a-directory:

> _"If you get a 500 Error when setting the permissions to 777 (world writable), then it means your server is setup to prevent executing such files. This is done for security reasons. In that case, you will want to use 755 as the highest permissions on a file."_

Although 777 is currently recommended by the documentation, if 777 isn't possible, 755 would be the next best CHMOD setting to use (777 is recommended by the documentation due to that it gives the greatest chance to phpMussel to be able to read/write to the vault in most circumstances; 755 should usually work too, although I've occasionally seen some issues with it with certain weirdly configured hosts).

Try changing the CHMOD settings for the vault to 755 and test phpMussel, to see whether the error code persists, and if it doesn't persist, test to see whether phpMussel can write to the vault; If it can, then it may just be that you'll need to use 755 for your particular hosting service.

If the error persists, we'll keep digging further (may be some other cause).

**Comment by Maikuolan** [comment]
@matteoraggi Did this solve the problem?

**Comment by matteoraggi** [comment]
777 is possible with fastcomet.com hosting, I was testing it up there.

**Comment by DanielRuf** [comment]
Normally this is not needed (because this is insecure) when you switch from FastCGI to Apache module for PHP, just for your information ;-)

**Comment by Maikuolan** [comment]
@DanielRuf Maybe the documentation should be updated to reflect this; What do you think? 777 is currently recommended by the documentation due to the aforementioned reasons, but the security concerns pertinent to using 777 should probably be mentioned too (they're not mentioned in the documentation currently), as well as alternatives (755, etc).

**Comment by DanielRuf** [comment]
@Maikuolan definitely. I would not suggest using 777 and try to recommend using the right permissions in combination with the PHP mode (Apache module). If this is not possible, users should be aware that they can use 777 but that this is also a security risk (for CGI / FastCGI, ...).

**Comment by matteoraggi** [comment]
yes, but ot me it doesn't work with 777 too, this is my problem.

**Comment by DanielRuf** [comment]
Well, because they are for beginners and also use an outdated, unsupported and insecure PHP version on their own website

```
---request begin---
HEAD / HTTP/1.1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/34.0
Accept: */*
Host: www.fastcomet.com
Connection: Keep-Alive

---request end---
---response begin---
HTTP/1.1 200 OK
Date: Tue, 20 Sep 2016 11:01:43 GMT
Server: Apache
X-Powered-By: PHP/5.4.45
Set-Cookie: session=39a0161f57d2d13ce32db8c5b744c6c4; path=/
Cache-Control: max-age=600, private, must-revalidate
Expires: Tue, 20 Sep 2016 11:01:43 GMT
Vary: Accept-Encoding,User-Agent
Connection: close
Content-Type: text/html; charset=utf-8

---response end---
```

**Comment by matteoraggi** [comment]
I am using 5.6 because using "vtiger crm" and it don't works with php 7. I don't think that it is a problem..

**Comment by DanielRuf** [comment]
@matteoraggi that was not about you the information. Seems 5.4 is their Apache module version or they are always using FastCGI. The comment shows the result from a wget command with your hosting provider (their website).

**Comment by DanielRuf** [comment]
Closing as this seems to be fixed by using `chmod 777` https://github.com/Maikuolan/phpMussel/issues/104#issuecomment-248266327

**Comment by Maikuolan** [comment]
Both PHP 5.4.45 and PHP 5.6 (the versions cited in previous comments here) should work correctly with phpMussel; The minimum version of PHP required in order to use phpMussel is PHP > 5.4.0 (so anything upwards of that should be okay; PHP > 7.0 is recommended for best performance due to significant improvements made since PHP 7.0, but PHP > 5.4.0 should work). I don't think the PHP version is the problem in this case. :-)

_Marking issue as "resolved" and adding a new to-do item regarding CHMOD recommendations._

If the problem persists, let us know and we'll reopen the issue.

**Comment by DanielRuf** [comment]
@Maikuolan no, I just wanted to mention that fastcomet (the wget result is from their website) use a very old PHP version (5.4.x) which may be the Apache PHP module version so I think all other versions on their servers are running under CGI/FastCGI. Just as information.

**Comment by Maikuolan** [comment]
Ah, okay. :+1:
