### ISSUE TITLE
PHPMussel doesn't work after updating

### ISSUE THREAD

**Issue by pabatribick** [phpMussel/phpMussel#109]
Hey,

Now my PHP-Project doesn't work, because PHPMussel does not work after your changes (update) since 2 days. What happened? I got one error: Parse error: syntax error, unexpected '$x' (T_VARIABLE) in phpmussel/vault/functions.php on line 210

Please fix that. PHPMussel is nice to scan Files.

**Comment by Maikuolan** [comment]
Sorry about this problem, and thank you for reporting this. :-)

It seems a small change introduced in one of my recent commits was causing this problem; I didn't catch it during prior testing, unfortunately. Anyhow, I've reverted the change just now, so, f you redownload the "functions.php" and replace your old copy with the redownloaded copy, the problem should be resolved (the problem was caused by only one line in that file, so, you shouldn't need to redownload the entire package to patch this).
