### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by Anan5a** [phpMussel/phpMussel#111]
I would like to translate the project into my native language, <b>Bangla (বাংলা)</b>

**Comment by Maikuolan** [comment]
Awesome! :-3

That would be really cool.

**Comment by Anan5a** [comment]
But where to start? -_-

**Comment by DanielRuf** [comment]
@Anan5a You can start with the english file, copy and translate it.

**Comment by Maikuolan** [comment]
I'd delay translating the README documentation for now (because there's a new feature I'm working on at the moment which'll require changing many parts of the README documentation very shortly), but the internal language data can be worked on right now without any risks (the new feature that I'm working on at the moment won't require changing any of the internal language data). :+1: 

If you fork the project, look for the file `/vault/lang/lang.en.php` (this is the internal language data for English). If you duplicate that file, and name the duplicate something like `lang.bn.php` ("BN" is the ISO 639-1 language code for _Bangla বাংলা_), just change the duplicate as per necessary (translating its contents from English to Bangla), commit the changes, and then send a PR. :-)

**Comment by Maikuolan** [comment]
(Alternatively, if it's easier, we're also registered with POEditor; Any changes made there, I can manually duplicate to the repo; Either method - editing the internal language data directly via forking the project or editing it via POEditor - are okay, and are equally workable; Though, if you're participating in Hacktoberfest at the moment, forking the project may be a better idea, because working with POEditor doesn't count towards Hacktoberfest contributions; Entering the GitHub "Contributors" list, also, requires commits).

**Comment by Maikuolan** [comment]
When working on the README documentation, same deal: Just find the English version of the README documentation, duplicate it, rename it, and translate the duplicate as per necessary. :-)

The English version of the README documentation can be found at `/_docs/readme.en.md` (and the duplicate would probably be best named something like `readme.bn.md`).

I would recommend to start on the internal language data instead though; Maybe try doing the README documentation in a week or so (if interested in helping with this), due to imminent changes to be made because of this new feature I'm working on at the moment.

**Comment by Maikuolan** [comment]
@Anan5a Any news about this? The README files are a little smaller now than they were before, due to that I've deleted some content from them which won't be relevant after the *v1.0.0* release (references to CVDs, MAP files, etc; signatures will handled a little differently in the future), so, it might be a little easier to translate now, than it was before. Anyway, no rush and no pressure, of course; Just hoping to hear from you  about how this is going. Cheers. :-)

**Comment by Anan5a** [comment]
No worry. I'll consider on that after finishing my board exam. End on
28 February :)

**Comment by Maikuolan** [comment]
Awesome! Thanks for the update, and good luck with the exams. :-)

**Comment by Maikuolan** [comment]
*Closing for issues cleanup.*
