### ISSUE TITLE
How Often Are The Signatures Updated?

### ISSUE THREAD

**Issue by ibanks** [phpMussel/phpMussel#114]
Hello Maikuolan,

I am considering using your solution for virus scanning file uploads, but I needed to know how often you update your virus signatures. If they are not updated that often, what other solutions to update them do I have? I was thinking that if I already have ClamAV installed on the server, then whenever it is updated, I could just take the main.cvd file and somehow update the phpMussel app signatures by copying this file to the signatures directory. Is that possible?

**Comment by Maikuolan** [comment]
Hi @ibanks,

When the project first started, I was updating the signatures at least once per month, but currently at this time, they're outdated by a few months. The reason for this is that I was updating everything manually (the format used by the ClamAV CVDs and by the phpMussel CVDs is very similar, but not 100% identical; there are some subtle differences due to the differences between how phpMussel and ClamAV interpret signatures respectively and etc), and it was taking too much time to get everything up-to-date all the time when doing it manually, so, as other issues gained higher priority and as my available time decreased, so too did the frequency of new signature updates decrease.

I'm currently working on a way to be able to update them automatically via a batch job or similar and a way to streamline the whole process, which hopefully should be ready within this or the next month hopefully. This change will also be accompanied by a change to the way in which phpMussel handles signatures overall, will be backwards incompatible with older configuration files and will likely also be backwards incompatible with former custom signature files and the likes (but things like plugins won't be affected by this in any way though, and will remain 100% backwards compatible with the current master branch, "v1.0.0-DEV"). Signatures are also likely to be shipped via a different repository in the future (in preparation for how we eventually plan to handle major versions >= 1).

In summary:

> I needed to know how often you update your virus signatures.

Not often enough currently, but hopefully much more often in near future.

> I was thinking that if I already have ClamAV installed on the server, then whenever it is updated, I could just take the main.cvd file and somehow update the phpMussel app signatures by copying this file to the signatures directory. Is that possible?

Not currently possible, unfortunately; At least, not without a bit of preparation work (due to the subtle differences in signature formats between ClamAV and phpMussel, which is why I was manually preparing the ClamAV signature files for use with phpMussel prior to uploading them here).

**Comment by ibanks** [comment]
Thanks Maikuolan for the quick response and the clear insight into what's going on. phpclamav was very heavy on our server load so we needed another solution. We'll be monitoring the progress of your app and hope to use it soon. Thanks!

**Comment by DanielRuf** [comment]
@ibanks what exactly is your planned usage of phpMussel (the scenario)? phpMussel is mainly for scanning files while they are uploaded.

**Comment by ibanks** [comment]
Yes. That is what we wanted to use it for. It runs perfectly to where it doesn't take a lot of time to scan a file. It is a really good solution. The only problem is the frequency of the signature updates. If that was corrected or there was a way to fix that (even if it requires a little work on our end), then we would definitely use this. The other solutions out there are just to long. For instance using clamscan executable even takes long.

**Comment by DanielRuf** [comment]
@ibanks so executable (.exe) files are allowed to be uploaded and you need real detection of malware? You also have a VirusTotal scanner in phpMussel (just checks the file hashes). And you can block uploads by file type, content and other options.

**Comment by ibanks** [comment]
@DanielRuf .exe files are not allowed to be uploaded. Only jpg, png, and pdf files. So we do detect the file type. However, malware and viruses can be uploaded via jpg, png, or pdf files. So we were looking for a scanning process to filter malicious uploads. As mentioned, this is a good service but the signatures aren't updated often. Are you suggesting that phpMussel is enough for this because it uses VirusTotal? If so, how?

**Comment by DanielRuf** [comment]
@ibanks if you mean webshells, the detection rate of phpMussel is very good. phpMussel also checks the content if it is ok based on the mimetype afaik. So you should be pretty ok. I don't think that you need the binary detection (exe files and so on) as these are mostly not hidden behind such extensions.

The VirusTotal scan only checks the hash and gives feedback if the exact same file with this hash (based on the content, filename does not matter) was previously scanned on VirusTotal.

The ClamAV signatures are mostly for binary files and binary malware as the other signatures already detect many threats and also overlap a bit with the ClamAV signatures (regarding the detection of malware).

Or how do you see this @Maikuolan?

**Comment by Maikuolan** [comment]
It's actually kind of interesting, the current direction of the discussion here and the points raised.

Although I'd previously mentioned "not often enough currently", in regards to how frequently the signatures are updated, this would *mostly* be problematic for being able to detect malware within PE sections (distinct fragments/components within Windows binaries/executables), due to how frequently new malware is discovered within PE files, how frequently new signatures for this type of malware are released by ClamAV, the ever-depreciating usefulness of any one particular signature over time as it ages and so on.

However, in regards specifically to signatures designed to detect malware within image files and PDF files, it mightn't be anywhere near as problematic, actually. Of course, there are new threats emerging all the time for these, too, just as with everything else, but new threats for these, specifically, aren't appearing anywhere near as frequently nor as often as are threats for PE files, Java files, macros, Android apps and some of the other currently more favoured and more commonly exploited infection vectors, and ClamAV actually doesn't seem to release new signatures specifically for images and PDF files anywhere near as often as they do for other types of files and other infection vectors, from what I've seen while analysing their daily signature releases over time.

If you were allowing executable binaries of any kind to be uploaded to your website, I would suggest that phpMussel would *NOT* currently be adequate for your needs, due to the lack of signature updates, and would further suggest that it'd be more likely for phpMussel to miss something than it would be for it to actually catch something for the same reason. However, if you're restricting uploads specifically to just image files and PDF files, phpMussel should actually already be adequate for your needs as it is currently, pending appropriate configuration and so on.

What I would recommend in that case, is to just ditch the PE signatures from phpMussel entirely (they represent nearly half of phpMussel's entire memory footprint, meaning that ditching them should slash the memory footprint for your phpMussel installation nearly in half, and if you're not allowing executable binaries to be uploaded anyway, then they'll never actually be used by phpMussel anyway and you won't be needing them), and ensure that you're using these configuration options:

All "chameleon attack" directives as TRUE(/ON/Enabled):
```INI
chameleon_from_php=true
chameleon_from_exe=true
chameleon_to_archive=true
chameleon_to_doc=true
chameleon_to_img=true
chameleon_to_pdf=true
```

The "filetype_whitelist" directive as EMPTY:
```INI
filetype_whitelist=''
```

The "filetype_greylist" directive as containing all the filetypes that you explicitly want to ALLOW to be uploaded, delimited by a comma (for example, if you wanted to allow JPEGs, GIFs and PDFs, you have something like the following; modify as per your own requirements):
```INI
filetype_greylist='gif,jpg,jpeg,pdf'
```

With that, image files and PDFs files should be scanned, and anything else should be automatically blacklisted under any foreseeable circumstances.

For optimum protection, too, I would recommend checking out the Virus Total options available in the configuration. Setting the above as recommended might be enough as is, but leveraging the Virus Total options provided would definitely improve your website security and could help in some situations. :-)

(PS, the current codebase available from the "master" branch is stable and should function as expected, but avoid the "dev-WIP" branch; the "dev-WIP" branch is not currently stable and won't function as expected).

**Comment by Maikuolan** [comment]
(( Also, that reminds me; We should probably look into our old idea about a GD-based plugin for phpMussel again at some point in the future. That would definitely help with ensuring the safety of image uploads. ))

**Comment by ad-wade** [comment]
While I often do not understand exactly what you-all are saying (i.e. "...just ditch the PE signatures from phpMussel entirely..."), I find it fascinating to read...and perhaps even learn something occasionally. 

My situation is similar to ibanks, in that we do not allow executable files to be uploaded to our XenForo forum.  So far (over a year now) phpMussel has worked well for us.  

If/when someone uploads something phpMussel sees as a threat, the upload progress bar XF displays to the person uploading will simply freeze at 0%.  Then of course they would contact me, about why they  can't upload something and I realize they need to be put them on a very short leash.

All that said, presently we only allow the following file types to be uploaded:
`zip
txt
pdf
png
jpg
jpeg
jpe
gif
gpx
mp3
mp4`

Do you see any file-type there, which could be a security issue for us?(i.e. Allow some malware or virus to slip through the crack.)

**Comment by Maikuolan** [comment]
Assuming that a "chameleon attack" isn't used (bit of an obscure security term, but basically refers to an attack whereby a dangerous/untrusted file is able to cause some damage that it wouldn't normally be able to cause, by way of pretending to be something that would normally be considered safe/trusted; for example: a file of a blacklisted type which is renamed to look like a file of a whitelisted type, or a malicious executable binary masquerading as a simple JPEG file, probably with a program icon which is the same as the standard icon used for JPEGs and with a filename something like "I.Am.Just.An.Ordinary.Picture.JPEG______________.exe"; that sort of thing; named so due to the way a chameleon can camouflage itself to protect itself against predators and those that would do it harm, and is also why I recommend enabling all the configuration options/directives relating to protection against chameleon attacks in almost all cases), and assuming that only those filetypes are uploaded, and that files uploaded of those types are actually truly of those types, there's not too much there really.

One risk that *all* of those particular filetypes have, is that they can contain other things which are unrelated to themselves, such as malicious PHP code which *won't* be executed when a user opens the file *directly*, but which *could* potentially execute if accessed/read in certain potentially dangerous ways by the server which hosts them, but the `chameleon_from_php` configuration option should prevent that particular thing from happening.

There are some malware strains which are kind of very old now (relatively speaking), which could infect and damage Windows-based machines, using PDFs as their carriers and Acrobat Reader as their infection vector, which could be executed on a system by very specific and now outdated versions of Acrobat Reader, and which have since been patched against by the latest versions of Acrobat Reader itself anyway (and no other PDF readers were ever viable infection vectors for these particular malware strains AFAIK).

ZIPs, of course, could be used as carriers/containers for malicious files, and therefore be considered dangerous in their own right, but if filetype blacklisting is carried into the contents of ZIP files (therefore meaning for your allowed/disallowed filetypes to also apply to the contents of ZIP files), this shouldn't really be any problem at all (can be set by specifying TRUE for "filetype_archives"):
```INI
filetype_archives=true
```

(Important to remember, of course, that almost anything anywhere can potentially carry malware/viruses in some form or another, but that doesn't mean any of it can actually be executed or cause any damage. For example.. Trying to execute a PHP virus on a machine which doesn't have PHP installed and which doesn't understand PHP code, won't do anything, or trying to execute a 64-bit Windows executable on an old iMac from the 90's, and etc, won't really do anything. Whether something is actually dangerous or not, often depends on context).

**Comment by ibanks** [comment]
@Maikuolan and @DanielRuf I'm still talking with my team about our recent discussions and using your solution. In essence what you are saying is that phpMussel looks for specific attacks (i.e. your way of identifying webshells, chameleon attacks..etc) that would be helpful in scanning image files and pdf's. In addition you also check to see if the file uploaded was previously flagged by VirusTotal scanner as a malicious file. Why ClamAV would over time only update virus signatures for binary/executable files I do not understand. All files are binary and I'm sure with some craftiness some new malware/virus architecture can be included within image files. Please feel free to elaborate on that as there may be something I do not understand. Also, I'm just curious as to why you all didn't think to somehow automate your virus signature updates when you created phpMussel. Just asking :-)

**Comment by Ami777** [comment]
@Maikuolan Can you provide information about what are differences in ClamAV signatures and phpMussel signatures? Maybe someone can create this automated tool to covert it.

**Comment by Maikuolan** [comment]
- When downloading the main/daily signature files from the ClamAV website, they're packaged into "CVD" files, which are actually archives containing some dozen or so different signature files combined into single CVDs. phpMussel signature files aren't packaged like this when distributed, so, that's the foremost difference to be aware of for those wanting to prepare ClamAV signatures for use with phpMussel themselves (perhaps obvious to anyone with a good understanding of the way that ClamAV distributes their signature files who happens to have glanced at the phpMussel signatures, but worth mentioning nonetheless). Also, next commit will drop the use of the "CVD" file extension for phpMussel signatures, due to that using this extension could be misleading in consideration of that the CVDs directly downloaded from the ClamAV website are archives, whereas the signature files included with phpMussel are not archives. (This is also the main reason why a direct copy/paste of the ClamAV CVDs into phpMussel won't work).
- phpMussel's "MAP" files is another difference, and previously, there was some information mentioned in the documentation about "MAP" files, but that information can be disregarded, because I intend to completely remove these with the next commit anyhow (so, this difference is deprecated, soon to be obsolete). The purpose of the MAP files was to expedite the scan process by bypassing any signatures considered non-triggerable within specific scan contexts, and is principally a good idea, but has weak/poor maintainability, and at this point, I feel is a bit hacky and not a good way to go moving forward. I'm currently trying to think up better ways to approach this problem. An entirely different approach to signature distribution is one concept I'm exploring, and should definitely help, but will probably still need to be combined with something else, too. This is better suited for its own issue ticket though, so I'll leave it at that, for now.
- All ClamAV normalised signatures (NBD signatures), regardless of the intended scan target (whether HTML files, PE files, Java files, Shockwave files, and so on), can be contained within the same singular NBD files, with the scan target being identified by the second parameter in the signature, like so:
`Signature-File:99:0123456789abcdef`
(Where "99" is the scan target [or type of haystack] and "0123456789abcdef" is a hexadecimal representation of the indicator/needle to look for within the scan target / haystack).
phpMussel signatures don't use this second parameter, because phpMussel has a different way of determining the intended scan target, and would look something more like this:
`\x30\x10\x10\x10Signature-File:0123456789abcdef`
This is a very minor difference though, IMO.
- The shorthand/pseudo-compression used by phpMussel signature names is something unique to phpMussel signature files, and does not exist within the ClamAV signatures as verbatim from their website. This was implemented to reduce the size of phpMussel signature files slightly, due to that an excessively large footprint for phpMussel and its signature files could reduce the viability of its use with shared hosting solutions. Various other tactics are also used to these ends, too. When preparing ClamAV signatures for use with phpMussel, I modify the ClamAV signature names according to this shorthand/pseudo-compression. Not modifying the names won't break anything, and this isn't particularly important from a functional perspective, but helps to keep down the size of files.
- ClamAV mixes regex and non-regex [regular expression] signatures together into the same files; phpMussel doesn't.
- Most importantly: ClamAV uses its own homebrew expression engine, which the ClamAV signatures are written in mind with, where phpMussel relies on the regex functions provided by PHP (therefore, PCRE). The syntax for the expression engine used by ClamAV is very different to PCRE, used by PHP, and this is one of the points where the most care is needed when preparing signatures for use with phpMussel.
- There are *some* types of ClamAV signatures which phpMussel doesn't yet support: The ClamAV "logical" signatures (LBD) are one such example.
- The "Complex Extended" signatures concept originated with phpMussel, rather than ClamAV, and so, there's nothing requiring preparation so far as these are concerned.
- In the past, *some* of the ClamAV "logical" signatures were rewritten in accordance with the phpMussel "complex extended" signatures, but this is a tedious and inefficient solution which I wouldn't recommend doing again; Next commit will dump all of these, and simply modifying phpMussel at some point to be able to support logical signatures would make more sense here.
- Dedicating lines within signature files to use conditional logic in-lieu of signatures in order to be able to jump between points in signature files is unique to phpMussel, and does not exist within the ClamAV signatures as verbatim from their website. Example:
`>FD-RX>^466f6f626172.*$>-1`
- The PE Sectional signatures from ClamAV, when preparing for use with phpMussel, I usually snip to the most recent ~20MBs or so of signatures (which usually works out to approximately ~400,000 or so signatures). This is because, if I didn't snip it down, we'd end up with signature files upwards of ~290MBs in size, which combined together, along with the potential sizes of files to be scanned, plus other memory usage requirements, could result in PHP occupying excessive amounts of active memory when scanning files, which could slow down servers, result in PHP halting, crashing, etc. Because PHP was never really intended to be used for powering anti-virus engines, a lot of what phpMussel ultimately does is compromise between what we actually want to do, and what we're practically able to do within the scope of PHP, safely. In this case, the consequence of snipping down signature files, aside from having smaller signatures and aside from a reduced risk of crashing PHP, is that we have less actual signatures, which means we're not catching as many different viruses/malware/etc as intended by the original non-snipped signature files. This is also why I've told people that using phpMussel is significantly better than using nothing at all, but that using an actual anti-virus service/daemon is significantly better than relying solely on phpMussel, if they're able to get one up and running on their server. The fact that most people on shared hosting services aren't able to get one up and running (due to restrictions from their provider) is one of the reasons I would highly recommend phpMussel for shared hosting environments, but nonetheless, it isn't perfect. Ultimately, I think, the best solution here would probably be to hand over the entire scan process to a SaaS service, but then, that's also currently somewhat outside the scope of the project anyhow.
- PE Extended signatures is unique to phpMussel, and does not exist in the ClamAV signatures. ClamAV does not support these types of signatures, AFAIK.
- ClamAV supports certificate scanning; phpMussel does not currently support this.
- ClamAV supports signatures concerning specific entry and exit points within executables. As I see no way to do this currently without either sandboxing or reverse-engineering executables, and as phpMussel does not attempt to sandbox or reverse-engineer the files being scanned, at this time, phpMussel does not support signatures concerning specific entry and exit points within executables.
- There are some deprecated/obsolete types of signatures that were previously supported by ClamAV, which phpMussel currently supports still due to not yet removing support for them (archive metadata signatures, for example). This will be corrected with the next commit. Support for filename signatures won't be deprecated or removed, however (these still serve a good purpose for phpMussel, IMO).
- Starting and finishing points within files for signatures is the same between phpMussel and ClamAV (i.e., signatures which themselves specify where to start and finish checking within a file for a specific indicator).
- The "IGN", "PDB", and "WDB" signatures within the ClamAV signature files, at this time, I entirely ignore. These don't have any use within phpMussel at this time (aren't supported).
- The phpMussel URL scanner was created specifically for phpMussel, and has nothing to do with ClamAV (so, none of the ClamAV signatures are used by the phpMussel URL scanner).
- The "FTM" signatures within the ClamAV signature files is somewhat similar in purpose to the phpMussel switch file (switch.dat), but are nonetheless ignored. phpMussel doesn't use this FTM file. The switch.dat file, likewise, was written for phpMussel for determining what type of file a file being scanned is and such.

It's about 2AM and I'm typing from work at the moment; Not sure if I've missed anything. I think that's most of it, though. I'll look over everything again when I get home later in the morning.

In any case though, I should mention that there's quite a lot about the phpMussel format that I kind of want to change, TBH. I think it could be made to be better than it currently is. Automation is definitely the way to go, though; I don't feel too keen on manually preparing everything on an ongoing basis into the future, especially so if it can be avoided by way of automation. Doing it manually just isn't particularly efficient, is very time consuming and tedious, and takes away time that could be spent elsewhere, like working on code and such. :-/

If someone could build a simple tool to automatically prepare everything, that would be fantastic. Though, some discussion about what others would and wouldn't like to see in that regard would not be unwelcome either, due to that nailing down any required changes *prior* to building any such tool could be good, as to make it easier for whoever does it and to reduce the chances of needing to change the way it works in the future.

Anyhow, I need to get back to working at the moment; I'll reply again a little later.

**Comment by Ami777** [comment]
Hi. Thank you! i think in the near future I will try to build automated tool to do this. I will contact you :)

**Comment by DanielRuf** [comment]
> Hi. Thank you! i think in the near future I will try to build automated tool to do this. I will contact you :)

That would be really great.

**Comment by Maikuolan** [comment]
It's a work-in-progress, but work has started on a tool, available here: __[phpMussel/SigTool](https://github.com/phpMussel/SigTool)__.

**Comment by Maikuolan** [comment]
There are improvements to be made, but it's basically working now. Marking this as resolved and closing.
