### ISSUE TITLE
phpMussel blocking .jpg files

### ISSUE THREAD

**Issue by ibanks** [phpMussel/phpMussel#116]
How can I quickly fix this or blacklist .jpg files for detection temporarily?

**Comment by ibanks** [comment]
Sorry if I may have said it incorrectly or may sound confusing, but temporarily I do not want .jpg files to be scanned. So that's what I'm trying to get done.

**Comment by DanielRuf** [comment]
@ibanks just whitelist the file extension so phpMussel won't scan it, see https://github.com/Maikuolan/phpMussel/blob/db79dc80d888c60fa792303b687d392148d54eb3/vault/config.ini.RenameMe#L385 and https://github.com/Maikuolan/phpMussel/blob/db79dc80d888c60fa792303b687d392148d54eb3/vault/config.ini.RenameMe#L366-L375

**Comment by ibanks** [comment]
The error message when someone uploads a jpg image is saying "phpMussel graphics Defacement..."

**Comment by DanielRuf** [comment]
@ibanks the error is there for a reason. But first we would have to check if these are false positives or legit blocks. Can you provide example images which trigger this error but are harmless?

**Comment by ibanks** [comment]
So it doesn't seem like I can provide you with the exact image that triggered the error as this is now being used by our customer. However, I can tell you that it was an image captured by phone. So my question is have you all ever had issues with images captured by phone? Is there some special way in which these images need to be saved before being uploaded and scanned by phpMussel?

**Comment by DanielRuf** [comment]
@ibanks possibly the exif data is a problem but I am not sure.

For debugging purposes it would be helpful to have some more information so we can easily reproduce this, create a failing test and fix this instead of guessing which caused this.

But @Maikuolan might be able to tell more about the triggered signature. Can you prodive the full block / kill message?

**Comment by ibanks** [comment]
Okay. I'm in the process now of trying to reproduce this. In the meantime, I believe I can get the kill message from the scan_log.txt file correct?

**Comment by DanielRuf** [comment]
> I can get the kill message from the scan_log.txt file correct?

Exactly.

**Comment by ibanks** [comment]
Okay. So I'm noticing that it is not doing this on every .jpg upload. Here is the one that failed:

DATE: Mon, 23 Jan 2017 11:51:28 -0500
== SCAN RESULTS / WHY FLAGGED ==
Detected phpMussel-Graphics.Defacement.X-01 (1485190232547-957817382.jpg)!
== MD5 SIGNATURE RECONSTRUCTION (FILE-HASH:FILE-SIZE:FILE-NAME) ==
81fa2ce5ad10a9b9ef3ff6c64ec632f0:3241991:1485190232547-957817382.jpg


Mon, 23 Jan 2017 11:51:01 -0500 Finished.
Mon, 23 Jan 2017 11:51:28 -0500 Started.
> Checking '1485190232547-957817382.jpg' (FN: 7951dba5; FD: 3f67850c):
-> Detected phpMussel-Graphics.Defacement.X-01!

**Comment by DanielRuf** [comment]
Removed the IP address as we do not need this.

**Comment by DanielRuf** [comment]
Removed the IP address as we do not need this.

> Mon, 23 Jan 2017 11:51:01 -0500 Finished.
> Mon, 23 Jan 2017 11:51:28 -0500 Started.

@Maikuolan is this correct?

**Comment by Maikuolan** [comment]
I'd say that in this case, we've got a false positive.

FYI: The defacement signatures are intended to detect indicators of website defacements within files (a good example of this can be seen with some of our HTML signatures, which look for strings like "Hacked by", "0wn3d by" and similar within HTML files). Defacements, in their own right, are not a type of malware, and do not (usually) contain things like trojans, viruses, etc. However, the reason it's worthwhile to look out for them (again, usually, but not always), is that the presence of defacement indicators can sometimes suggest a much larger, unseen problem with a website, beyond the scope simply of file uploads, like vulnerable code, preexisting backdoors and such. Depending on how confident you are with your website security otherwise, depending on how closely you want to monitor file uploads (or whether you'd prefer to operate on a set-and-forget basis), and depending on whether you're interested only in blocking direct, immediate threats, or whether you're also interested in looking for signs of indirect threats (such as with the case of defacement indicators), in many cases, the defacement signatures can simply be disabled without any real concern for side-effects or unforeseen consequence.

The specific offending signature in this case, ("phpMussel-Graphics.Defacement.X-01"), looks for the existence of "r00t" within image files (therefore, if an image file contained that specific string somewhere in its raw content, and assuming that this signature hasn't been disabled, that the image file or file type hasn't been whitelisted, and that defacement detections haven't been disabled, this signature will be triggered). If the user in question is simply attempting to upload a photo from their phone, it's extremely doubtful that the detection in this particular case is of any meaningful interest (which, in combination with the consideration that defacements aren't malware in their own right, it's clear that this is false positive).

Considering this instance, and also considering the short length of the string being detected and the potentially wider than desirable scope, I'm thinking I'll just drop the specific offending signature entirely upon the next signatures update.

For now, to deal with the problem in this specific instance, I see three possible approaches.

1. If you don't want JPG/JPEG files to be scanned, __*at all*__, then, the best solution, as per DanielRuf's earlier suggestion, would be to simply whitelist the file extensions. That will ensure that JPG/JPEG files are never scanned. If they're never scanned, then, this specific detection will never occur.

2. Alternatively, if you still want JPG/JPEG files to be scanned, in order to simply avoid this specific detection, you could add the name of this signature to the greylist. You can do this by adding "phpMussel-Graphics.Defacement.X-01" (without the quotes) to the "greylist.csv" file, located in the phpMussel vault directory. If there are other signatures already listed there, separate them by commas.

3. Alternatively, if you still want JPG/JPEG files to be scanned, and if - based upon what I've written above in regards to defacement signatures - you don't think you'll be needing to detect defacement indicators, the easiest solution would be to just disable defacement detection entirely. To do this, in your phpMussel configuration file, look for this:
```INI
detect_deface=true
```

..and change it to this:
```INI
detect_deface=false
```

(That'll disable defacement detection entirely).

*Marking this issue under both "Support" and "False Positive". We'll keep the issue open until both have been resolved.*

**Comment by Maikuolan** [comment]
> Removed the IP address as we do not need this.
> 
> > Mon, 23 Jan 2017 11:51:01 -0500 Finished.
> > Mon, 23 Jan 2017 11:51:28 -0500 Started.
> 
> @Maikuolan is this correct?

Good point.. That doesn't look normal, actually; Finish time should not be earlier than the start time. I'm not really sure what would cause that, TBH.

**Comment by DanielRuf** [comment]
@ibanks can we close this issue?

@Maikuolan should we create a new issue for the last comment (wrong time) and check if we can reproduce it in the current version?

**Comment by ibanks** [comment]
Hello,

I apologize for my totally late response on this issue. We got swamped at
my job with other projects and this issue hasn't been fully resolved. I do
believe that the issue was in regards to uploads being denied by phpMussel
because of exif data on images. That problem still exists, but what we did
was take one of the servers off of our load balancer. So now phpMussel
isn't being used to scan uploaded files but we do want to use it. So do you
have any updates in this issue? Has it been resolved in a new version?
Thank you for checking back with me.

Isaiah

**Comment by Maikuolan** [comment]
Hi Isaiah,

No problem about the late response. :-)

There's a rather significant update in the works currently that'll change the way in which signatures are actually deployed in the first place; When this update is released, it should resolve the issue at hand.

I'd like the keep this issue ticket open for now so that we're able to properly confirm that the problem is resolved after the update is released. Release of this update has mostly been delayed due to work commitments of my own external to this project, but should occur reasonably soon; I'll reply here again when it does.

Thanks for your patience.

Caleb M / Maikuolan.

**Comment by Maikuolan** [comment]
Hi again Isaiah,

I've just release v1.0.0; When you've got a moment, could you confirm whether this problem persists?

Cheers,
Caleb M.

**Comment by Maikuolan** [comment]
Marking this issue as *fixed* and *resolved* and closing it. If the problem persists, please feel free to reopen it. Thanks. :-)
