### ISSUE TITLE
phpMussel is not able to catch some types of viruses (embedded binaries)

### ISSUE THREAD

**Issue by wajdijurry** [phpMussel/phpMussel#129]
Some types of viruses can't be caught by phpmussel like a pdf file contains "embedded msf payload (reverse https) exploit".

How can this be solved ? What signature does this type of viruses has ?

This is an attached file contains the exploit.
[infected.pdf](https://github.com/Maikuolan/phpMussel/files/981683/infected.pdf)

**Comment by DanielRuf** [comment]
This is hard to detect by inspecting just the code and would decrease the performance. In this case we need new signatures (ClamAV or manually created hashes). Signatures have to be implemented by @Maikuolan. Creating them manually is not so easy and not yet automatized.

**Comment by Maikuolan** [comment]
phpMussel is already able to scan raw binary, regardless of the type of file, seeing as raw binary is raw binary anyhow, regardless of the type of file in question. Although kind of not a perfect solution, and easy to work around, if we wanted to detect some specific strings of specific parts of the raw binary within specific files, for very common builds of files with wide distribution, for where unique markers can be found within the raw binary corresponding to the container in question, it should be possible to manually write new signatures either as "general" signatures or "PDF" signatures; That can be done easily enough. However, writing hash-based signatures is far less resource intensive, is better for performance, etc; That may be preferable in some cases. The two major downsides to hash-based signatures though, are that firstly, any permutation of the file whatsoever would be sufficient to circumvent a hash-based signature (so, they're only good for detecting specific files which are not expected to change frequently), and secondly, if we want to keep the overall footprint/size of the signature files to a minimum, older and less important hash-based signatures are likely to be dumped after some time, due to that their numbers tends to grow very quickly when relying on that method over some period of time.

That all said though, phpMussel is not currently capable of recognising nor reverse-engineering PDF files into their base/constituent parts, and so, scanning individual containers within a PDF file, independent of scanning the file as a whole, isn't currently possible at this time.

I'm not entirely sure whether the ClamAV engine currently does this either; I'd need to test it to confirm, I think.

Probably the best solution might be to have these such files forwarded to Virus Total to be scanned, rather than to write signatures of our own for these; Less long-term maintenance costs and ultimately going to be more reliable, too.

Although at this time, the way that phpMussel has been coded to leverage the Virus Total API means that it only checks Virus Total for known hashes  (i.e., files already previously scanning by Virus Total), and it doesn't currently send any actual raw binary to Virus Total, it is on the to-do list to eventually improve this, as so that whole files / raw binary can be sent to Virus Total to be scanned. When that happens, that would probably provide us with the best option for these types of PDF files, I think.

**Comment by wajdijurry** [comment]
I had a look on this issue #114, which was talking about the same thing I already did.
When will you release the updated databases of the signatures ?

**Comment by wajdijurry** [comment]
Any replies please ?!

**Comment by Maikuolan** [comment]
Sorry for the delayed reply; Busier than anticipated past few days.

Currently trying to figure out the best way to deploy signatures automatically. Have delayed new signature releases the past few months mostly due to that (hoping to avoid doing too many more manual cuts if possible). How long this'll take mostly comes down to availability of time, commitments to multiple projects (some paid/commercial; some others unpaid/free and open-source like phpMussel; split priorities), employment commitments (which unfortunately must always take priority above anything else) and such; I'm not entirely sure I could give a 100% reliable date for it.

This is currently a top priority though, so, with the exception of any pending bug-fixes and any work already in progress (such as completion of any currently-in-progress documentation translations and L10N work), I anticipate this being completed prior to any new features, other unrelated major changes, and prior to the completion of anything that hasn't been started yet otherwise.

**Comment by wajdijurry** [comment]
Can you give me an estimation for the release date for the signatures database upgrade ?
It's really urgent issue.

**Comment by DanielRuf** [comment]
> Can you give me an estimation for the release date for the signatures database upgrade ?
> It's really urgent issue.

Generally I would suggest a donation if this is urgent to support the development.

What exactly do you need to be detected? Is this already detected by other scanners and included in the official ClamAV signatures? Would a signature really help as this would just work if the file is identical to the hash? Any small change on the file would require a new signature.

> That all said though, phpMussel is not currently capable of recognising nor reverse-engineering PDF files into their base/constituent parts, and so, scanning individual containers within a PDF file, independent of scanning the file as a whole, isn't currently possible at this time.

This is a big feature which needs development, testing and a good plan. etasploit is a mighty framework and you can inject any exploit to binary files and PDF files. Not sure but I guess this just works with the scripting engine in recent PDF files. And I doubt it is so easy to detect all current possible payloads which can be used for such attacks.

PS: the file download is blocked / detected by current scanners so it would make sense to use the VirusTotal API, this is typically faster and scales better with new attacks.

**Comment by DanielRuf** [comment]
https://www.virustotal.com/de/file/dddf6dcdc80bc2f04215ee0989ec911a3d27205c7eef648fadbbd63382d135a4/analysis/

JS.Exploit = Scripting engine in Adobe Reader and others.

http://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2008-2992

**Comment by wajdijurry** [comment]
The first time I used VirusTotal to scan this file, it does not caught by any engine!
So, it seems that VirusTotal takes time to inspect any infection in file.

**Comment by DanielRuf** [comment]
No, VirusTotal submits the file to all antivirus vendors. If they do not yet have a signatre, they will analyse the file and create one which takes some time as there are always many files in the waiting line at each vendor. Future VT analysis will show the new detection ratio. This takes some time. The antivirus vendors are slow, not Google/VT ;-)

**Comment by Maikuolan** [comment]
*Also relevant: https://github.com/Maikuolan/phpMussel/issues/124*

**Comment by wajdijurry** [comment]
Clab, Hi again :)
What is the way you follow to convert CVD database files to readable phpmussel files ?
I want to add my own signatures of viruses to the signatures already added to phpmussel, but I don't know how.

Thanks,

**Comment by Maikuolan** [comment]
Hi wajdijurry,

I've just updated the documentation to include better information about the format used by signature files, how they're converted, interpreted and so on.

You can find it __[here](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#8-signature-format)__.

I haven't yet documented how signature name "shorthand" works (planned to be done at some stage), but that shouldn't really be relevant for custom signatures anyhow; the newly added documentation in combination with pre-existing documentation should be sufficient for explaining the signature format as far as custom signatures are concerned.

With your own signatures, is this converting signatures from a pre-existing database somewhere, or writing entirely new signatures?

**Comment by Maikuolan** [comment]
Also, now that __[SigTool](https://github.com/phpMussel/SigTool)__ exists, I won't be cutting new signature sets manually anymore; I'll just use that instead, to do it automatically.

**Comment by Maikuolan** [comment]
Marking this issue as resolved.

I assume there should be enough information available to be able to write custom signatures, but if you need help, any more information and so on, just reply and let us know and I'll reopen the issue accordingly.
