### ISSUE TITLE
gitreports.com

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#146]
Instead of managing other issues in the forum we should collect them here as they might be relevant for others and in my opinion bugs should be discussed / reported in the open.

https://gitreports.com/

**Comment by Maikuolan** [comment]
Definitely a fantastic idea. :+1: 

My main concern with anonymous reports is the risk of bots getting into it and potentially spamming the issues page. Know of any other repos using it? Might be useful to check some of them out, to see whether or not that's a problem for them at the moment.

**Comment by DanielRuf** [comment]
See https://github.com/schneidmaster/gitreports.com/issues/128

**Comment by Maikuolan** [comment]
Still no updates to the above-linked issue since November, but I've noticed recently that GitHub now provides an option to "report" comments, in the comment context menu provided to owners and maintainers, alongside the options to "edit" and "delete" comments. That's a good thing, I guess, and favourable towards the idea of allowing anonymous participation to the issues page. I've never used the "report" option before, so I'm not 100% sure about how it works, but I'm assuming it reports the comment to GitHub staff..? Of course, that doesn't eliminate, or even really reduce the risk of bots at all, but might be useful in identifying them to GitHub, I guess.

Anyhow.. Still waiting for them to either respond further (i.e., to suggest implementing some of the mentioned ideas) at the above-linked issue or to close it (i.e., to dismiss the mentioned ideas). For now.. Seems to not be moving in either direction.

**Comment by Maikuolan** [comment]
August 2019.. still no updates to the above-linked issue.

Additionally, seems my concerns have been realised now by other users:
- https://github.com/schneidmaster/gitreports.com/issues/146
- https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/326

I don't anticipate any further progress at this point. I still like the idea.. but some other, alternative solution would probably be needed here to avoid the spam risk, I think.

Marking as *Abandoned* and closing. We can just create a new issue later if we find some better solution, or if some further progress is eventually made, I think.
