### ISSUE TITLE
False negative on EICAR Anti-Malware Testfile

### ISSUE THREAD

**Issue by dbanton** [phpMussel/phpMussel#148]
### phpMussel version used
name   : phpmussel/phpmussel
version: v1.1.0
source : {
   type         : git
   url            : https://github.com/phpMussel/phpMussel.git
   reference : fc84518cd2dcd544ecebe86c863225103f81ee40
}

### Signatures version
All signature files downloaded and extracted from:
https://github.com/phpMussel/Signatures/tree/master/clamav
No other signatures used

### PHP SAPI used
apache2handler

### PHP version installed
PHP 7.0.22

### Operating system used
Linux 4.4.0-104-generic 
Ubuntu 16.04.1 x86_64
Zend Engine v3.0.0 with Zend OPcache

---
## Issue
Ran manual scan of EICAR Anti-Malware Testfile as outlined in your documentation with these results:

Fri, 12 Jan 2018 07:21:53 -0500 Started. > Checking '/eicar.txt' (FN: 291664fe; FD: 21d4bb76): -> No problems found. Fri, 12 Jan 2018 07:21:53 -0500 Finished. 

Contents of file:
> X50!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*

Test file sourced from:
http://www.eicar.org/86-0-Intended-use.html

### Expected behavior
phpMussel should flag file as malware

### Actual behavior
File reported as not infected. See below:

Fri, 12 Jan 2018 07:21:53 -0500 Started. > Checking '/eicar.txt' (FN: 291664fe; FD: 21d4bb76): -> No problems found. Fri, 12 Jan 2018 07:21:53 -0500 Finished.

**Comment by Maikuolan** [comment]
Thanks for reporting this. :-)

A quick cursory test using CLI-mode with my current dev copy of phpMussel doesn't seem to replicate the problem:

![eicar](https://user-images.githubusercontent.com/12571108/34880056-2bb136ee-f7ea-11e7-9b45-df08f889e226.png)

The second detection ("phpMussel-Testfile.EICAR.Standard") is part of the "phpMussel" signature files, so, it's expected that that particularly detection isn't seen when using only the "ClamAV" signature files. The first detection though ("ClamAV-Clamav.Test.File-7") is part of the standard "ClamAV" signature files, so, definitely should've been seen.

I'm not writing this off yet though. ;-)

I'm currently at home and about to head to work in about 20 minutes, which is why I've only done a quick cursory test thus far (was out earlier and didn't see this issue until just now), but I wanted to at least get a reply in here before I head to work given that I had some time to spare and probably won't be able to reply again until the end of my shift tonight. I'll investigate further when I get home again, do some more testing, try to get to the bottom of this, etc. Will reply again with the results and to mention what I can find.

**Comment by dbanton** [comment]
Thanks for your prompt reply on this Maikuolan! 

Since we are running on a Unix system we are unable to test in CLI mode as in your screen capture but I went ahead and included all of the phpmussel signature files from the repo, and we are saving the eicar test file as plain text containing only their character string and even tried renaming it to match you as above -> 'eicar.com.txt'.

We are now running 53 Active Signature Files (as indicated inside our phpMussel front end Statistics) since installing the phpMussel signatures along with the ClamAv ones. 

We installed the phpmussel signatures from here:
https://github.com/phpMussel/Signatures/tree/master/misc

We still see:

Fri, 12 Jan 2018 11:51:23 -0500 Started. > Checking '/tests/Unit/eicar.txt' (FN: 291664fe; FD: 21d4bb76): -> No problems found. Fri, 12 Jan 2018 11:51:23 -0500 Finished.
Fri, 12 Jan 2018 11:51:23 -0500 Started. > Checking '/tests/Unit/eicar.com.txt' (FN: 24c8cb05; FD: 21d4bb76): -> No problems found. Fri, 12 Jan 2018 11:51:23 -0500 Finished. 

when running the scan through this PHP script:

<img width="738" alt="screen shot 2018-01-12 at 11 52 39 am" src="https://user-images.githubusercontent.com/23283132/34885820-270cea4e-f78f-11e7-98c3-5efe5a245381.png">

Not sure if I previously mentioned that we installed phpmussel through composer or if the '/vendor' folder in the path gave it away but hopefully these extra details help!

**Comment by Maikuolan** [comment]
Haven't been able to replicate the problem yet, but still working on it.

Out of curiousity, are the testfiles included with the phpMussel package (`/_testfiles/*`) detected when scanning them on your end, or do they similarly result in "no problem founds"?

*Approximate expected results:*
```
Sat, 13 Jan 2018 20:48:49 +0800 Started.
> Checking 'ascii_standard_testfile.txt' (FN: ce76ae7a; FD: 7b9bfed5):
-> Detected phpMussel-Testfile.ASCII.Standard!
> Checking 'coex_testfile.rtf' (FN: b0e404dc; FD: c44e0020):
-> Detected phpMussel-Testfile.CoEx!
> Checking 'exe_standard_testfile.exe' (FN: bc2b0816; FD: 0133b2e1):
-> Detected phpMussel-Testfile.EXE.Standard!
> Checking 'general_standard_testfile.txt' (FN: e0a8291b; FD: e1d00044):
-> Detected phpMussel-Testfile.General.Standard!
> Checking 'graphics_standard_testfile.gif' (FN: fa02d6a4; FD: 31dcb0b4):
-> Detected phpMussel-Testfile.Graphics.Standard!
> Checking 'html_standard_testfile.html' (FN: 20df694f; FD: 48e4ea2b):
-> Detected phpMussel-Testfile.HTML.Standard!
> Checking 'md5_testfile.txt' (FN: 26568969; FD: 4e8f9f87):
-> Detected phpMussel-Testfile.MD5!
> Checking 'ole_testfile.ole' (FN: 1d191026; FD: 0de5ef7a):
-> No problems found.
-> Reading 'ole_testfile.ole' (PHAR):
-> Checking 'ole_testfile.ole>%PATH%/ole_testfile.ole/ole_testfile.txt' (FN: 4974ab10; FD: b6da61cd):
--> Detected phpMussel-Testfile.OLE.Standard!
> Checking 'pdf_standard_testfile.pdf' (FN: 6d1c7c10; FD: 8c05e37f):
-> Detected phpMussel-Testfile.PDF.Standard!
> Checking 'pe_sectional_testfile.exe' (FN: 51114ec6; FD: f93ee86b):
-> Detected phpMussel-Testfile.PE.Sectional!
> Checking 'swf_standard_testfile.swf' (FN: 1c2de39d; FD: e0cfb75b):
-> Detected phpMussel-Testfile.SWF.Standard!
Sat, 13 Jan 2018 20:48:57 +0800 Finished.
```

**Comment by dbanton** [comment]
My results look different to yours again unfortunately:

Mon, 15 Jan 2018 14:41:35 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/ascii_standard_testfile.txt' (FN: a6b0ff3f; FD: 7b9bfed5): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/coex_testfile.rtf' (FN: 4e913c30; FD: c44e0020): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/exe_standard_testfile.exe' (FN: 5f33a143): -> Filetype blacklisted. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/general_standard_testfile.txt' (FN: 71ca9bff; FD: e1d00044): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/graphics_standard_testfile.gif' (FN: 5df49277; FD: 31dcb0b4): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/html_standard_testfile.html' (FN: 4819380a; FD: 48e4ea2b): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/md5_testfile.txt' (FN: 877513f1; FD: 4e8f9f87): -> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/ole_testfile.ole' (FN: bc3a8abe; FD: 0de5ef7a): -> No problems found. -> Reading '/vendor/phpmussel/phpmussel/_testfiles/ole_testfile.ole' (PHAR): -> Checking '/vendor/phpmussel/phpmussel/_testfiles/ole_testfile.ole>/vendor/phpmussel/phpmussel/_testfiles/ole_testfile.ole/ole_testfile.txt' (FN: 4974ab10; FD: b6da61cd): --> No problems found. Mon, 15 Jan 2018 14:41:36 -0500 Finished.
Mon, 15 Jan 2018 14:41:36 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/pdf_standard_testfile.pdf' (FN: 8e04d545; FD: 8c05e37f): -> No problems found. Mon, 15 Jan 2018 14:41:37 -0500 Finished.
Mon, 15 Jan 2018 14:41:37 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/pe_sectional_testfile.exe' (FN: b209e793): -> Filetype blacklisted. Mon, 15 Jan 2018 14:41:37 -0500 Finished.
Mon, 15 Jan 2018 14:41:37 -0500 Started. > Checking '/vendor/phpmussel/phpmussel/_testfiles/swf_standard_testfile.swf' (FN: ff354ac8; FD: e0cfb75b): -> No problems found. Mon, 15 Jan 2018 14:41:37 -0500 Finished. 

The only other thing we did in our config.ini was to edit these two controls:

cleanup=false
filesize_limit=8388608

**Comment by cwolcott** [comment]
Any suggestion on where to put some debug statements to see why it might not be detecting the virus?

**Comment by Maikuolan** [comment]
Although I'm not yet 100% sure what's causing the problem, my current thinking is that perhaps the signature files mightn't be being processed or read correctly.

In the [signatures section of the documentation](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#signatures-category), under "fail_silently":
> Should phpMussel report when signatures files are missing or corrupted? If fail_silently is disabled, missing and corrupted files will be reported on scanning, and if fail_silently is enabled, missing and corrupted files will be ignored, with scanning reporting for those files that there aren't any problems. This should generally be left alone unless you're experiencing crashes or similar problems. False = Disabled; True = Enabled [Default].

Assuming it's been left as its default, it'll likely be "false" at the moment. Just for the sake of debugging, if you change it to "true", and then try scanning again (and actually, for this, scanning any non-empty files should be sufficient), does it still show "no problems found", or are any errors/warnings produced about signature files?

**Comment by DanielRuf** [comment]
Can you provide more info about your PHP version + cli / module / fastcgi, if error output is disabled in `phpinfo` and other related debug / logging settings, if there are `@` error suppression hints in our code that might be problematic and if the access rights (chown, chmod) are correct?

**Comment by dbanton** [comment]
@Maikuolan - I changed 'fail_silently' to 'true' and did a re-scan of all the test files as above and the results are the same. A mixture of 'No problems found.' and 'Filetype blacklisted.' but no complaints.

@DanielRuf - I think our permission settings 'shouldn't' be causing any problems (right now the signatures are 660 and the system account that runs the script is also owner of the files). Let me take a look through some of our other PHP settings you mentioned and see if I can spot anything that might be affecting us. Back with an update soon.

**Comment by dbanton** [comment]
We changed 'scan_cache_expiry' to zero (0) and now we are getting results much like yours where all the test files as well as our eicar.txt and eicar.com.txt files are being detected.

When we first installed, we ran the scans against the clamav signatures alone (without the phpmussel signatures installed), phpmussel didn't detect problems, and remembered that result even after we added the phpmussel signature files.

What is strange is that even with the 6hr timeout we should have had a cache reset since the entire weekend elapsed without a scan.

**Comment by Maikuolan** [comment]
Glad to hear that the cause of the problem has determined. :-)

> What is strange is that even with the 6hr timeout we should have had a cache reset since the entire weekend elapsed without a scan.

Definitely so. Even if perhaps resolved, I'll keep this issue open for now; I'm going to try to test caching a bit further on my end to try to replicate the problem properly, and hopefully figure out why yours didn't expire after the default 6 hours (might be some bug introduced since some other recent change to the codebase, possibly; if so, that'll need to be fixed). Cheers for letting us know what you've found. :-)

**Comment by cwolcott** [comment]
To determine the above issue we placed echo statements in the Scan, Recursor and DataHandler functions.  Reading through the code I placed an echo statement in DataHandler after the if statement "To check for the existence of a cache entry corresponding to the file".  Once we determined we weren't reaching this point in the code I was able to determine the token and change the 'scan_cache_expiry' from 21600 to 0 and everything worked.  

Not sure if you would be able to return a 1 (object not flagged) but with a comment "Used cache info" so that when the message was sent a detail that the cache was used could be tagged.

We also thought the the cache should automatically clear itself if different signatures files were used than the previous call, just a thought.

Thank you for an excellent and useful library.

**Comment by cwolcott** [comment]
The whole reason we decided to upgrade at this point in time from 0.10.0 to 1.1.0 is that we were receiving a detection on many files just based on the filename.  So before requesting assistance we decided to upgrade and see if we still had the issue.  Answer: YES.

The file is named - **ValidationRecall-Proteomics-Serum-UCSF-BDNF-20171220-raw.txt**.  We replaced the contents with just the string 'abc' and the file was still being detected with the issue .
**phpMussel-FN.X-39!**.  Since this is all new to us it took some research to track down that the phpmussel.fdb signature is the culprit and that .fdb is a Filename signature type.  I removed this signature file from the active list and the file passed scanning.

My curiosity is how to understand the phpmussel.fdb contents and determine what is causing the detection.  Like I said there are many other files similar in name that are also being detected.  I do not want to tell the users they need to change their naming standard.  Our initial trial/error is that the first '-' and 'Proteomics' is causing the issue.  I can remove the first '-' and everything passes.

**Comment by Maikuolan** [comment]
Thinking on it, I might dump that particular signature from the database, actually.

The actual detection pattern for the signature in question (phpMussel-FN.X-39):
```
[a-z]{5,}\x2d(mahjong|em\x2dup|dash|delux|quest|pro|amazon|money)
```
(So in this case, the "-Pro" part is what's triggering it).

This particular signature was originally created due to some malware campaigns from a few years ago, whereby attackers were using various different types of malware, some of which was difficult to detect, but all with these spammy-looking filenames in uploads like "free-money", "games-dash", "xxx-delux" and that sort of thing. The signature provided an easy stopgap measure against some predictable and commonly used filenames, where it seemed legit users rarely used those types of names. Of course, there's nothing malicious about the names of the files in their own right; They just simply provided a convenient fingerprint for some uploads that were unwanted anyhow. I haven't seen the same fingerprint in recent years though, so, if it's falsing, it should be reasonably safe to just dump that particular signature from the database. I'll see to it for the next cut (which as it is, is kind of overdue now anyhow).

**Comment by cwolcott** [comment]
Did you see our previous [comment](https://github.com/phpMussel/phpMussel/issues/148#issuecomment-358034395) with a couple of potential suggestions?

**Comment by Maikuolan** [comment]
Definitely, those are good suggestions, I think. :-)

In particular, indicating whether the scan results are from the cache, shouldn't be too difficult to implement. Currently, I'm thinking I could <strike>add an extra entry</strike> to the "[debug array](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#how-to-access-specific-details-about-files-when-they-are-scanned)", and that should be reasonably easy to work with, I think. *Edit: Actually, scratch that. Just realised that I'd actually already implemented earlier exactly what I was currently thinking about implementing now. Must be the hot weather and lack of sleep getting to me, ha.*

**Comment by Maikuolan** [comment]
> We also thought the the cache should automatically clear itself if different signatures files were used than the previous call, just a thought.

Also a good suggestion. This is something I could work on next, I think.

**Comment by cwolcott** [comment]
I think the FAQ section [How to access specific details about files when they are scanned](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#how-to-access-specific-details-about-files-when-they-are-scanned) should be referenced in Section 3.0 [How to use for web servers](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#30-how-to-use-for-web-servers).  It has all the dirty details that can be useful for audit/logging.

**Comment by Maikuolan** [comment]
- __*phpMussel-FN.X-39*__ dumped.
- New signatures cut released.
- Some checks have been added to clear out the hash cache when there are changes to the active signature files.

Still working on the other things.

Agreed about referencing that FAQ section somewhere in section 3.0; Good catch. I'll make a start on that tomorrow.

**Comment by Maikuolan** [comment]
*Documentation updated. Closing.*
