### ISSUE TITLE
Only one signature at a time

### ISSUE THREAD

**Issue by senky** [phpMussel/phpMussel#151]
### phpMussel version used
1.2.0

### Signatures version
https://github.com/phpMussel/Signatures/commit/8c526853371c8c028f7fb3c8b92ca86a724176a2

### PHP version installed
5.6.32

### Operating system used
Darwin xxxxx-mac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

---
## Issue
I tried to install phpMussel 1.2.0 on my localhost. What I did:
1. copy the files
2. rename config.ini
3. allow frontend in config
4. head to Updates
5. install various signatures
6. activate first one
7. activate second one
- at this point, first activated signature is deactivated automatically

### Expected behavior
Multiple signature files are expected to be activated at the same time.

**Comment by Maikuolan** [comment]
Thanks for reporting this. :-)

Tested and successfully replicated the problem. Bug confirmed. Looking through the code now, to determine what's causing it.

**Comment by Maikuolan** [comment]
Okay.. Figured out what's causing it. As per the repository `.gitattributes` file, files with extensions not specified by the repository `.gitattributes` file *should* break lines with LF (per Unix standard), whereas INI files (e.g., the `config.ini.RenameMe`/`config.ini` file) *should* break lines with CRLF (per Windows standard, due to where the idea of using INI files comes from), and the codebase, including the function/closure for activating a component, had been written accordingly (i.e., to expect these types of linebreaks). For some reason though, which I don't know currently, at some point during some commit/update to the `config.ini.RenameMe` file in the repository, all the linebreaks defaulted to LF.

I discovered this just now, because when testing this bug, I found that the bug seemed to disappear when updating the configuration via the configuration page, and *then* trying to activate a component (because updating via the configuration page reverted to the expected linebreaks). Not seeing why that should make any difference, I compared the configuration file from when first downloaded, to after being updated without any changes, to see whether there were any differences at all, and found that difference.

I'm thinking what I'll need to do to fix this bug is update the function/closure for activating a component, to check the type of linebreaks being used by the configuration first, before trying to activate anything, so that it'll be able to handle either type of linebreak properly.

For now, as a temporary solution until I fix this bug (hopefully later tonight), if you go to the configuration page and press "Update", then go to the updates page and try activating the necessary components, it should work as expected.

(And for later, as a secondary objective after fixing the bug: I should try to figure out why the `.gitattributes` file was ignored during a commit).

**Comment by Maikuolan** [comment]
Hi @senky,

I believe I've managed to fix this bug just now. When you've got a moment, could you confirm whether it seems to now be working as expected on your end?

Cheers.

**Comment by Maikuolan** [comment]
Also, @DanielRuf : Any thoughts about the `.gitattributes` file?

**Comment by DanielRuf** [comment]
Will check it then. How are your Git settings (regarding pf / lbr)?

**Comment by Maikuolan** [comment]
Oh.. I've just realised what's happened, and now I feel really dumb. >.x

`.gitattributes` is set to use CRLF for INI files, but because the configuration file has the "RenameMe" bit on the end.. Technically, it isn't using an INI extension anymore.

Well.. At least it's not some major GitHub bug or anything.

I'll update the `.gitattributes` file shortly to include `*.renameme` in there.

**Comment by Maikuolan** [comment]
Done and done. :+1: 

Everything should be good now, as far as I can tell.

**Comment by DanielRuf** [comment]
That makes sense. In this case I would have recommended using config.default.ini like I wrote in the past ;-)

**Comment by DanielRuf** [comment]
In this case the IDE / editor still formats it as ini file and can lint it if needed. Never use another file extension.

**Comment by Maikuolan** [comment]
True, true. Main issue with keeping the normal file extension was with the INI file being accidentally overwritten sometimes when some users tried updating the package using external update mechanisms, but maybe this is something we could look into at some point, to come up with a better way of managing this. Using the proper extension would be ideal, if we could do so without any issues.

**Comment by senky** [comment]
@Maikuolan fix confirmed, thanks! 🙂
