### ISSUE TITLE
Testfiles passed

### ISSUE THREAD

**Issue by senky** [phpMussel/phpMussel#152]
### phpMussel version used
1.2.0

### Signatures version
https://github.com/phpMussel/Signatures/commit/8c526853371c8c028f7fb3c8b92ca86a724176a2

### PHP version installed
5.6.32

### Operating system used
Darwin xxxxx-mac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

---
## Issue
I installed phpMussel 1.2.0 on my localhost. Then enabled frontend, installed and activated `phpmussel_graphics.db` and `phpmussel_graphics_regex.db`. After that I used Upload Test to upload `graphics_standard_testfile.gif`, but file passed.

### Expected behavior
Testfile should be blocked with proper signatures activated.

**Comment by Maikuolan** [comment]
I haven't been able to replicate the problem thus far. I'm wondering if perhaps the signature files might've not activated properly due to the bug from issue #151?

Sorry to be a pain, but when you've got a spare moment, since #151 has been fixed now, could you confirm whether the problem mentioned in this issue (#152) still persists on your end?

If it doesn't, I'll mark this issue as fixed. If it does, I'll dig further and continue testing, to figure out what's going on. Cheers. :-)

**Comment by senky** [comment]
@Maikuolan yes, it is fixed now. Thanks a lot! 🙂

**Comment by Maikuolan** [comment]
Awesome! Glad to hear it, and thanks for letting me know. ^.^
