### ISSUE TITLE
preg_match compilation fail

### ISSUE THREAD

**Issue by gregory511** [phpMussel/phpMussel#157]
Hello,

I am trying to make a scan system callable from a cron task (we have specific restrictions on our server).

I'm getting the following error when trying to scan files from my PHP code :
`Warning: preg_match(): Compilation failed: missing ) at offset 60 in C:\wamp64\www\myproject\vendor\phpmussel\phpmussel\vault\functions.php on line 2902`

This line number refers to this piece of code :
```php 
} elseif (!preg_match('/(?:' . $ThisSig . ')/i', $ThisString)) {
```

In this case, $ThisSig looks like this, which results in a wrong regex :
`3c696672616d65207372(?`

Why is this happening in the first place?

Here is a shortened version of my code calling the scan closure :

```php
require_once SERVER_ROOT . '/vendor/phpmussel/phpmussel/loader.php';
$phpMussel['Set-Scan-Debug-Array']($scanDebugArray);
// some uninmportant code
$scanResult = $phpMussel['Scan']($file);    
```

I would be very grateful if you could guide me towards a solution which does not involve messing with the library code. Maybe this is a very basic issue that I somehow overlooked...

Anyways, here is some extra details.

## Server information.
Apache 2.4.33

### phpMussel version used (if known, please also include the exact commit hash).
v1.3.0 @70c829389f0a4815af85db20bef2d36dcccdbc9d

### Signatures version
The latest, taken from phpMussel/Signatures.

### PHP version installed
5.6.35 

### Operating system used
Windows 10 Enterprise

**Comment by Maikuolan** [comment]
Thanks for reporting this, and sorry to hear that this problem has occurred in the first place.

<strike>I think there's a problem with the latest cut of the signature files, and that it's responsible for the problem we're seeing here (as opposed to the actual phpMussel codebase itself). I've seen this a few times before when new cuts failed or were erroneous for whatever reason and such. Something might've changed that I hadn't caught when building the latest cut from the source files from ClamAV (in which case.. I might need to make some adjustments to SigTool, to try to prevent whatever's happened here for future cuts).

I'll take a closer look at it tonight and prepare a new cut at some point between now and tomorrow morning. I'll reply again when it's committed (at which point, assuming all goes well, and assuming what I'm currently thinking turns out to be correct, updating should fix the problem).</strike>

Edit: Found the problem. Signature files are fine; It is a bug in the codebase itself after all. Anyway, I'll get started on a fix shortly.

**Comment by Maikuolan** [comment]
Committed a fix for this just now. Also immediately releasing new version in response to this. Updating to this latest version (or alternatively, patching the files modified via this latest commit) should resolve the problem. :-)

**Comment by gregory511** [comment]
It works great now. Thanks for your quick action, much appreciated.
