### ISSUE TITLE
Signatures and testing

### ISSUE THREAD

**Issue by webtent** [phpMussel/phpMussel#159]
I have installed on FreeBSD 11.1 the latest version cloned from this Github repo. We are using Apache 2.4.33 with apache2handler and PHP 7.1.18, here is the uname output:

`FreeBSD hostname 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11 #0: Thu Jun 21 03:46:08 UTC 2018 root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64`

After install, the front end works. I tried Updates of the signatures and receiving this error:

`clamav.db – signatures/clamav.db – Checksum error! File rejected!
clamav.db – Failed to install! +0 bytes | -0 bytes | 0.191`

I've checked directory permissions, all owned by the apache user. I resorted to try SigTool but not 100% sure I've done correctly. I ran sigtool.php with xpmd options, all downloaded and ran successfully. Then I copied all the files clamav*db into the vault/signatures directory. I am able to run the CLI and scan the _testfiles without issue.

Can someone help to determine the issue with the front end updates and whether I have setup properly? I also tried the following script if I'm trying to test this correctly?

`<?php
require '/usr/local/www/phpMussel/loader.php';
$results = $phpMussel['Scan']('_testfiles', true, true);
echo $results
?>`

I installed above script into the DocumentRoot of the website and ran, which produces the following error:

`Fatal error: Uncaught Error: Function name must be a string in /www/ficras.com/phpmussel.php:3 Stack trace: #0 {main} thrown in /www/ficras.com/phpmussel.php on line 3`

**Comment by Maikuolan** [comment]
Hi webtent,

Thanks for reporting this issue. :-)

When the updater was implemented to phpMussel, a handful of simple security and safety checks were added as precautions against things that could potentially break or corrupt installations. One of these was an optional check against file checksums. When the updater attempts to fetch updates to specific files, if a checksum corresponding to the file being fetched exists in the metadata information corresponding to the component (phpMussel core, module, plugin, signature file, etc) being installed or updated, the updater will generate a new checksum for the newly fetched file and compare it to the corresponding checksum in the metadata information. If the two checksums match, the install/update proceeds as expected, but if the checksums don't match, the install/update will abort, any changed files will revert to their previous state, any newly fetched files will be purged (unlinked), and the "`Checksum error! File rejected!`" message will be given, to let the user doing the updating know what has happened.

Under normal circumstances, the checksums should always match, and this problem shouldn't occur. Circumstances that could cause this problem to occur though:
- Something went wrong at the upstream (e.g.; a hacked or compromised host [theoretically possible, but highly, highly unlikely; I use 2FA for my account, there's been no signs of this happening currently, and GitHub is pretty secure and reliable]; a host which somehow modified files at the upstream after they were already committed, or after hashes were already written [very possible if a repo has bad `.gitattributes` settings and such; I'll double-check on this shortly anyhow]; upstream unavailable due to server errors, bad routing, downtime, etc).
- Something went wrong at the downstream (e.g.; a host intercepts and modifies the files somehow during transit [maybe ModSecurity doesn't like something about a file or something like that], or after the updater fetches them, but before it can compare any checksums; files accidentally deleted by external software, etc).
- Something went wrong during transit (e.g.; bad connection, bandwidth issues, or packet loss while fetching the files; somehow the wrong file gets fetched; etc).
- None of the above happens, but it turns out I stuffed something up when committing an update (maybe wrote the wrong checksum to the signatures metadata file, committed a wrong file version, used the wrong Git commands and broke something when pushing, or something like that; hopefully I haven't done any of those things in this case, but I'll double-check on that shortly too, just in case; nobody is perfect, after all, and it's always good to cover all bases), or alternatively, I broke something in the codebase during a recent update to that (also hopefully this isn't the problem too, but I'll be able to figure that out and confirm one way or the other when I investigate further run some tests shortly).

Anyhow, I'll investigate this now and reply again shortly when I figure out what's happened in this case.

**Comment by Maikuolan** [comment]
Regarding the second mentioned issue of the "`Fatal error: Uncaught Error: Function name must be a string in ...`" message: What's the current value for the `general` -> `cleanup` configuration directive of your installation?

**Comment by Maikuolan** [comment]
Nevermind all the other above possibilities.. Found the cause of the problem, and.. I'm surprised nobody had noticed it earlier, but it should be very easy to fix. Bad path name in remote source. >.x

I'll commit a fix for that in a few minutes, re-test, and let you know how it goes.

**Comment by webtent** [comment]
That's great, thanks for the quick update. I'll check back tomorrow. My `general` -> `cleanup` is set to true.

**Comment by Maikuolan** [comment]
> That's great, thanks for the quick update. I'll check back tomorrow.

No problem at all. :-)

Fix committed, and seems to be working correctly now on my end. When you've got a spare moment, let me know how it goes no your end. Cheers. :+1: 

> My `general` -> `cleanup` is set to true.

Try setting the value to `false` and let me know whether the problem persists.

(phpMussel can also be manually unset from memory via `unset($phpMussel);` after all operations have finished if needed, if automatic cleanup via `general` -> `cleanup` is disabled).

**Comment by webtent** [comment]
I don't see the update or commit. Is there more than one repository? The last I see is the Documentation update.

**Comment by Maikuolan** [comment]
> Is there more than one repository?

Yep. :-)

Around about the time of the ~v1.0.0 release, the signature files were moved out to their own repository ([phpMussel/Signatures](https://github.com/phpMussel/Signatures)), in an attempt to try to keep the main repository a little cleaner and more maintainable (the signature files are quite large, and bloat the size of the main package quite a bit when combined together; keeping them separate should help to deal with that a bit). The updater is aware of the various different repositories though and how they relate to each other, so the different repositories shouldn't be any sort of problem for the updater. Bookmarking or starring the links for the different repositories should help make them a little easier to find though, when installing/updating things manually.

**Comment by webtent** [comment]
Oh ok, so I should use `2.3.3 Download signatures from "phpMussel/Signatures" and install manually` instead of the front end updates?

**Comment by Maikuolan** [comment]
Any of the mentioned methods should be fine. :-)

I just try to also include information in my replies which could be helpful to enable people to choose whichever method they prefer (so, updating via the front-end, or automatically, should work fine now that a fix for our earlier problem has been committed, but I mentioned the link to the signatures repository too, in case manual download is preferred).

TBH, I think using the front-end would provide a more user-friendly experience for most users, but some users prefer to do it manually, or prefer to cut their own using SigTool, so, all methods are documented, to try to make it easier for users to choose whichever method they would prefer.

**Comment by webtent** [comment]
Very good, yes, the updates on the front end now working, thanks. I'd like it to work automatically in the end. Once I have activated in the front end, will they update automatically or do I need to do something else?

Also, do we need all the different types of signatures, I guess it depends on what we intend to scan? And what is the difference between the ClamAV versus the phpMussel signatures?

**Comment by Maikuolan** [comment]
> Very good, yes, the updates on the front end now working, thanks.

Great to hear. :-)

> I'd like it to work automatically in the end. Once I have activated in the front end, will they update automatically or do I need to do something else?

In the future, I will likely come up with a better method, I think. For now though, there's a small tool I wrote, "[Cronable](https://github.com/Maikuolan/Cronable)", which allows users to update phpMussel (or CIDRAM; two different packages; Cronable can work with either of them) via cronjobs, if their server has a cron manager available to work with. For 100% fully-automated updates, that would currently be the simplest way to go, I think. Cronable has documentation too, with installation and usage instructions, so should be reasonably easy to set up.

Otherwise, just regularly checking the updates page and clicking "Update All" when updates become available will update it too (this, I consider a "semi-automated" solution, in the sense that the updater automatically takes care of fetching/adding/removing/modifying the necessary files, but the user is still manually triggering the process in the first place).

Cronable works quite well, and definitely should be sufficient, but the reason that I say that "in the future, I will likely come up with a better method", is because what Cronable does (a simplification, but not wrong), is emulate the aforementioned "semi-automated" process (i.e., uses PHP's curl implementation to log into the front-end, trigger the same functionality provided for the updater, etc), but in a cron context (thus technically making it "fully-automated"). Nothing wrong with that necessarily, but it also doesn't feel very elegant, and I think I could probably build something better eventually, when other things are finished and there's enough time for it (assuming, of course, that nobody else comes up with something first). ;-)

> Also, do we need all the different types of signatures

Nope. Not everything will be necessary.

> I guess it depends on what we intend to scan?

Yep. What will be necessary, will depend on context, package configuration, the types of files/data normally expected, not expected and so on. :-)

> And what is the difference between the ClamAV versus the phpMussel signatures?

That question could be interpreted in two different ways, so, for the benefit also of other people which might read this discussion in the future, I'll answer for both ways. ;-)

1. __The signatures directly from ClamAV as verbatim (`mains.cvd` and `daily.cvd`), versus the signature files which SigTool generates (or which can otherwise be downloaded/installed to phpMussel via the `phpMussel/Signatures` repository). Alternatively: Why, exactly, is SigTool useful, versus just using the signatures directly from ClamAV as verbatim?__

So, although phpMussel uses signatures from ClamAV, phpMussel doesn't use the actual ClamAV engine itself. Instead, the phpMussel codebase has been written from scratch, optimised for a context where everything can be done in PHP alone, without external dependencies and so on. However, because the signatures as verbatim are quite large, and there will be some differences between the ClamAV engine and the phpMussel codebase, the signature files are modified in such a way that they can be interpreted more quickly and efficiently by phpMussel than would otherwise be the same. This involves things like stripping down the ClamAV database to its most essential and most useful parts, to something more easily digestible for the types of memory limitations typically imposed on most PHP installations, and things like translating ClamAV's native expression syntax to PCRE-compatible expression syntax (so that they can be interpreted by PHP's `preg_*` functions and such). Processing also removes some unnecessary overhead from ClamAV's database, and then adds in some extra headers to each of the signature files so that phpMussel knows what to do with them all. In short: The signatures directly from ClamAV as verbatim, and the signatures resultant from parsing them with SigTool, will be similar, but not exactly the same, and the verbatim signatures won't work properly in phpMussel until they've been processed.

2. __After using SigTool (or after downloading the signature files from the `phpMussel/Signatures` repository), some of the filenames are prefixed by "`clamav`", and some of the filenames are prefixed by "`phpmussel`". What's the difference between the two?__

This simply allows us to distinguish who the original vendor is for the signatures contained by those signature files. In short: Anything prefixed by "`clamav`" originates (is sourced from) from ClamAV, whereas anything prefixed by "`phpmussel`" originates elsewhere (either written myself, via my own research, or gathered and aggregated from various other vendors). Generally, this distinction won't matter too much, unless a user decides that they only want to use signatures from ClamAV, or only want to use signatures from elsewhere, and that type of thing.

(This reply is beginning to get long, so I'm going to post it now, and continue with a follow-up reply).

**Comment by Maikuolan** [comment]
__Differences between some of the different signature files.__

It's not comprehensive, but there's *some* potentially information on this subject available in the "[generated signature files list](https://github.com/phpMussel/SigTool/blob/master/_docs/readme.en.md#sigtool-generated-signature-files-list)" section of the SigTool documentation.

There's also some somewhat more technical information available in the "[Signature Format](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#8-signature-format)" section of the phpMussel documentation, but that more covers technical aspects the various formats used by the signature files, rather than things like the intended purpose of individual signature files, or like when and in what contexts individual signature files would be useful (so, is somewhat less *to-the-point* on this subject).

Writing some more concise, informative, and *to-the-point* information on this subject is on the immediate to-do list currently, and I hope to get done very soon (but hasn't been done yet).

I'll reply here again to mention about it when I finish writing that information.

I should mention, that there's some old information available at SourceForge about the phpMussel signature files on a small Wiki there, but that information relates to pre-v1.0.0 versions, and is entirely outdated now, so there's no point in linking to it here, I think. '^.^

Briefly though, and because combined, they form more than >50% of the total bulk and footprint of all signature files in terms of bytes (meaning that, if you don't need them, you could potentially reduce the footprint of your installation by >50%): Any signature files whose names end with `_exe.db`, `_exe_regex.db`, `.mdb`, or `.medb`, are specifically looking for dangerous or infected Windows executables. So, if your website already doesn't allow users to upload Windows executables, or doesn't provide/support Windows executables in any way, then you won't need those specific signature files.

If you allow users to upload anything other than plain-text ANSI, it would be good to avoid `hex_general_commands.csv` due to a high risk of false positives (I plan to add a warning about this to the documentation soon). Most signature files are pretty safe, but that specific signature file is prone to false positives, due to some wide-reaching signatures which don't discriminate on context, type of file, etc. (This is also the only file which breaks the convention of using a `clamav` or `phpmussel` prefix to indicate vendor. For the record: It doesn't come from ClamAV, but exists due to some historical use-cases, back when phpMussel was first created. I'm not entirely sure yet whether I'll keep supporting it in the future, or maybe deprecate it for a future phpMussel v2.0.0; still thinking about it).

Signature files whose names end with `graphics.db` or `graphics_regex.db` deal specifically with dangerous or infected image files. If your website doesn't allow anything other than image files to be uploaded (this can apply sometimes to websites primarily operating as blogs, image galleries, or forums, where users might have the ability to upload images, but nothing else), you could set the `compatibility` -> `only_allow_images` configuration directive to `true`, to instruct phpMussel to block anything which isn't an image:

> If you only expect or only intend to allow images to be uploaded to your system or CMS, and if you absolutely don't require any files other than images to be uploaded to your system or CMS, this directive should be enabled, but should otherwise be disabled. If this directive is enabled, it'll instruct phpMussel to indiscriminately block any uploads identified as non-image files, without scanning them. This may reduce processing time and memory usage for attempted uploads of non-image files. False = OFF; True = ON.

When this is done, you could theoretically do away with all signature files aside from the graphics signature files (because nothing other than the graphics signature files would be needed anymore anyway), and just rely on the graphics signature files to catch any dangerous or infected graphics files that might come through.

Beyond that, similar logic could be applied for the various other signature files (once it's been established what their intended purpose is). `swf.db` and `swf_regex.db` signature files for Flash/Shockwave files, `pdf.db` and `pdf_regex.db` signature files for PDF files, `elf.db` and `elf_regex.db` for Linux executables, `macho.db` and `macho_regex.db` for Mac-OS (Mac, Apple, etc) executables, `java.db` and `java_regex.db` for dangerous and infected Java files, etc.

That doesn't cover all of them, but I'll start writing up some proper information soon anyway, and I'll let you know when it's available (hopefully within the next day or so, pending available time).

**Comment by webtent** [comment]
Very great, thanks again for all your great insight. I'm sure it will be beneficial to all, I certainly appreciate. The auto update is working with Cronable and I did finally have success with my test script after setting `general -> cleanup` to `false`. However, I did receive many warnings on this development server:

`Warning: fopen(/usr/local/www/phpMussel/vault/cache/41.tmp): failed to open stream: Permission denied in /usr/local/www/phpMussel/vault/functions.php on line 543

Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/local/www/phpMussel/vault/functions.php on line 544

Warning: fclose() expects parameter 1 to be resource, boolean given in /usr/local/www/phpMussel/vault/functions.php on line 545

Warning: preg_match(): Compilation failed: regular expression is too large at offset 334 in /usr/local/www/phpMussel/vault/functions.php on line 2684

Warning: preg_match(): Compilation failed: number too big in {} quantifier at offset 78 in /usr/local/www/phpMussel/vault/functions.php on line 2684

Warning: preg_match(): Compilation failed: number too big in {} quantifier at offset 54 in /usr/local/www/phpMussel/vault/functions.php on line 2684

Warning: preg_match(): Compilation failed: regular expression is too large at offset 93 in /usr/local/www/phpMussel/vault/functions.php on line 2684

<snip many warnings for line 2684 like above>

Warning: preg_match(): Compilation failed: regular expression is too large at offset 107 in /usr/local/www/phpMussel/vault/functions.php on line 2684
Wed, 27 Jun 2018 20:41:17 +0000 Started. -> Checking '/ascii_standard_testfile.txt' (FN: 6b65333b; FD: 7b9bfed5): --> No problems found. -> Checking '/coex_testfile.rtf' (FN: b5292674; FD: c44e0020): --> No problems found. -> Checking '/exe_standard_testfile.exe' (FN: f8375e80): --> Filetype blacklisted. -> Checking '/general_standard_testfile.txt' (FN: 87741db5; FD: e1d00044): --> No problems found. -> Checking '/graphics_standard_testfile.gif' (FN: cb0b847f; FD: 31dcb0b4): --> No problems found. -> Checking '/html_standard_testfile.html' (FN: 85ccf40e; FD: 48e4ea2b): --> No problems found. -> Checking '/md5_testfile.txt' (FN: eb2332ae; FD: 4e8f9f87): --> No problems found. -> Checking '/ole_testfile.ole' (FN: d06cabe1; FD: 0de5ef7a): --> No problems found. --> Reading '/ole_testfile.ole' (PHAR): --> Checking '/ole_testfile.ole>usr/local/www/phpMussel/_testfiles//ole_testfile.ole/ole_testfile.txt' (FN: 4974ab10; FD: b6da61cd): ---> No problems found. -> Checking '/pdf_standard_testfile.pdf' (FN: 29002a86; FD: 8c05e37f): --> No problems found. -> Checking '/pe_sectional_testfile.exe' (FN: 150d1850): --> Filetype blacklisted. -> Checking '/swf_standard_testfile.swf' (FN: 5831b50b; FD: e0cfb75b): --> No problems found. Wed, 27 Jun 2018 20:41:41 +0000 Finished.`

**Comment by webtent** [comment]
Nevermind, Failed to see the permission issue. Fixed and now runs fine. Thanks again!

**Comment by Maikuolan** [comment]
Excellent! Glad to hear it runs fine now, and you're welcome. ^.^

In any case, it's still useful for me to discover about these situations, because I can use this information to further improve the documentation, FAQ, etc (it's possible that other users in the future might encounter similar error and warning messages, but not realise about possible permission issues, so, I could add something to the FAQ about this to help point them in the right direction when this type of situation arises). :+1: 

I'll mark this issue as *resolved* and close it. Let me know if any problems persist though. :-)
