### ISSUE TITLE
cannot upload a normal doc/docx file 

### ISSUE THREAD

**Issue by 1nFrastr** [phpMussel/phpMussel#163]
## Server information.

phpMussel v1.5.0

php 5.6

WAMP SERVER on win7

---
## Issue
when i try to upload a normal doc/docx file , phpMussel returns the result like that:

> Filename manipulation detected (has+content.docx%3EC%3A%5Cwamp64%5Ctmp%5CphpECB4.tmp%2F_rels%2F.rels)!

`has+content.docx` is the file i want to upload. And `has+content.docx` is not empty.

i am confusing with the “Filename manipulation detected  ” ! 

It seems that my origin `.docx` file was transformed to `.rels` file . From search engine , i know that the `.rels` file is the xml information of Microsoft Word appending to the `.docx` file i created.

But, I can upload the empty doc/docx file successfully!

How to deal with that?

**Comment by Maikuolan** [comment]
Hi,

This is a false positive, I think. Most likely caused due to the internal structure of the file (this specific detection generally occurs when filename has a dot at the beginning or end of the file, and was originally intended to prevent users from uploading files which might be not properly seen or recognised by the file system; I can see that currently in the codebase though, that the contents of archives and archive-like files are also checked by this, which doesn't make so much sense, I think). I'm going to make some changes to the codebase tonight, which should hopefully resolve the problem.

I'll reply again a little later, after I've committed some changes.

**Comment by Maikuolan** [comment]
Hi again,

I've committed some changes to the codebase which should (in theory) fix the problem. When you've got a spare moment, try updating so that you'll have these changes reflected in your installation, try uploading again, and let me know how it goes. :-)

**Comment by 1nFrastr** [comment]
Now, the normal doc/docx file can be upload successfully! Thanks！

However , another question I found is that writing PHP script into `.txt` file can not be checked by phpMussel. And , writing  a PHP script and simply  changing its filetype name to `.php.txt`  cannot be checked by phpMussel either. Both  of them can upload successfully !

That may cause some security issue .

**Comment by Maikuolan** [comment]
*Primarily issue already resolved ("filename manipulation" false positive). Will resolve secondary issue via #164. Closing #163 in favour of #164.*

**Comment by jutho-agentur** [comment]
Sorry to dig out this old thread but I have problems to upload a normal docx file.
PHP 7.4 and the newest phpMussel always results in the following error: "Command injection attempt detected!"

I just have new docx file with one sentence in it - nothing else.

Why is it happen? What can I do?
(It even occurs with a filename without spaces)

[Ein ganz normales word dokument.docx](https://github.com/phpMussel/phpMussel/files/6149341/Ein.ganz.normales.word.dokument.docx)

**Comment by Maikuolan** [comment]
No need to apologise. :-)

I think, the blame for that particular message belongs to the `hex_general_commands.csv` signature file. Unfortunately, among all the currently available signature files, that particular signature file has probably the highest false positive risk.

Since a docx file is effectively an archive container, parts of the docx file are scanned by phpMussel accordingly, and within the attached docx file, within the `word/styles.xml` file, I noticed this:

```XML
<w:lsdException w:name="HTML Code" w:semiHidden="1" w:unhideWhenUsed="1"/>
```

Totally normal for a docx file, and nothing wrong with that. But, one of the signatures in `hex_general_commands.csv` check for the presence of the string, `code"`, which unfortunately matches against the file in question (`Ein ganz normales word dokument.docx/word/styles.xml`).

TBH, I've sometimes wondered whether I should just remove that particular signature file, due to the high false positive risk (it exists mostly due to the request of some users from a very long time ago, which wanted to block such strings quite strictly). It's a useful signature file to have if, like those users, you need a really strict upload environment, and only upload very limited types of files, like plain-text ANSI files and etc, but tends to produce a high amount of false positives whenever dealing with more complex text files, files containing markup, code, etc.

Since you're needing to be able to upload docx files, to scan them with phpMussel, and to avoid these false positives, I think, if you deactivate and remove that particular signature file, it should resolve the problem. :-)

**Comment by jutho-agentur** [comment]
Thank you for your very quick answer!
I just deleted the `hex_general_commands.csv` and now it works!
I hope it's still secure and can find real vulnerabilities.
