### ISSUE TITLE
can't detected PHP script in txt file

### ISSUE THREAD

**Issue by 1nFrastr** [phpMussel/phpMussel#164]
## Server information

phpMussel v1.5.0

php 5.6

WAMP SERVER on win7

## Issue

I found that :

1. writing PHP script into `.txt` file can’t be detected by phpMussel.
2. writing  a PHP script and simply  changing its filetype name to `.php.txt`  can’t be detected by phpMussel either. 

Both  of them can upload successfully ! That may cause  security issue .
**Wating for your reply , thanks !**

**Comment by Maikuolan** [comment]
Hi 1nFrastr,

Sorry for the delay. Got caught up with some other things.

Quick question.. In your installation, what's the `chameleon_from_php` directive's current value?

Also, would it be okay for you to share the files which were uploaded successfully? It would be useful for me, to be able to analyse them more closely, to try to figure out why they weren't detected. :-)

**Comment by 1nFrastr** [comment]
Sure.

Actually , I just wrote  a simple PHP script like this ,

```php 
<?php
echo "phpMussel is awesome";
```

then placed this into a TXT file named `foo.txt` . On the other hand ,  a PHP file `foo.php` then changed its extension to `foo.php.txt` . Both of them can upload successfully . 

Already confirmed `chameleon_from_php=true` in `config.ini` file . 

Thanks for your efforts on phpMussel and quick reply for my questions , it behaves excellently while uploading  a fake image file including PHP chamelon.

By the way , it seems that you haven't done a great test for this project ...

**Comment by Maikuolan** [comment]
Firstly, [the code responsible for this](https://github.com/phpMussel/phpMussel/blob/master/vault/functions.php#L2860-L2871):
```PHP
    /** PHP chameleon attack detection. */
    if ($phpMussel['Config']['attack_specific']['chameleon_from_php']) {
        if (!(
            substr_count(',cvd,inc,md,phar,pzp,tpl,txt,tzt,', ',' . $xt . ',') ||
            substr_count(',php*,', ',' . $xts . ',') ||
            substr_count(',cvd,inc,md,phar,pzp,tpl,txt,tzt,', ',' . $gzxt . ',') ||
            substr_count(',php*,', ',' . $gzxts . ',') ||
            substr_count(',' . $phpMussel['Config']['attack_specific']['archive_file_extensions'] . ',', ',' . $xts . ',') ||
            substr_count(',' . $phpMussel['Config']['attack_specific']['archive_file_extensions'] . ',', ',' . $gzxts . ',') ||
            substr_count(',' . $phpMussel['Config']['attack_specific']['archive_file_extensions'] . ',', ',' . $xt . ',') ||
            substr_count(',' . $phpMussel['Config']['attack_specific']['archive_file_extensions'] . ',', ',' . $gzxt . ',')
        ) && substr_count($str_hex_norm,'3c3f706870')) {
```

So originally, this was actually done intentionally, but I'm going to treat it like a bug and change it anyway, I think. I'd forgotten about it until now, but I've remembered why it was written like this. The reason it was done like this originally, was because of numerous README files for different projects, documentation files, notes, etc, which would be flagged by phpMussel as a [chameleon attack](https://ieeexplore.ieee.org/abstract/document/6234406/) whenever phpMussel tried to scan them, which would annoy some users (e.g., they would include notes about their own code in TXT files, phpMussel would see these files, see that they contain PHP code, and that they're not PHP files, and therefore flag them accordingly). There were some similar situations too where file extensions not typically associated with PHP files, might've sometimes contained PHP code and therefore been flagged (like with some CMS, which sometimes use extentions like INC, TPL, etc; the code snippet above demonstrates which extensions are currently exempted from the PHP chameleon attack detections).

The reason I'm thinking of treating it like a bug and changing it anyway: The documentation does clearly say, "Search for PHP header in files that are neither PHP files nor recognised archives." It does *NOT* say, "PHP files, plus TXT files, TPL files, INC files.. etc." So, I think, creating undocumented exemptions could be misleading, and potentially cause problems in some cases too. So, I'm glad you've mentioned about this, and I appreciate it. :-)

Maybe what I could do, instead of having undocumented exemptions, is just add a new directive for users to specify which extensions are permitted to contain PHP code (I could include maybe just PHP and PHAR by default, and then users can add whatever else they want to be exempted, if they maybe need to do so for TXT files and so on). I'll play around a little later tonight and try to commit something for this.

> Thanks for your efforts on phpMussel and quick reply for my questions , it behaves excellently while uploading a fake image file including PHP chamelon.

:-) :+1: 

> By the way , it seems that you haven't done a great test for this project ...

Yep. Unit testing definitely, 100% needs to be improved for the project. Currently, phpMussel is able to be unit tested (it has integration with Travis-CI, has a simple unit tests file, etc), but also, the full extent of current unit testing consists basically of executing the package as a whole and checking whether any errors are generated after the event (which.. is useful, but.. not really a "unit" test). Actually testing individual "units" is something to be done at some point.

Unit testing isn't my greatest strength, unfortunately. Any help with this from anyone willing to help would be welcome. Otherwise, I hope to eventually get proper unit testing implemented, but it may take me a while to do.

**Comment by Maikuolan** [comment]
Latest commit introduces a new configuration directive allowing users to specify which file extensions should/shouldn't be caught by this detection. :-)
