### ISSUE TITLE
Just a small issue, probably nothing.

### ISSUE THREAD

**Issue by ghost** [phpMussel/phpMussel#166]
## Server information.
GoDaddy
### Operating system used (`<?php echo php_uname(); ?>`).
Linux localhost

---
## Issue
Each time the programme is used, I keep getting the following error in my error_log.text;
`
[02-Aug-2018 09:56:31 UTC] PHP Notice:  Undefined index: CacheModified in /home/a05cl07huhyj/public_html/appphpdox/phpMussel-master/vault/functions.php on line 4717
`
I hope it's still working as it should. It hasn't detected anything yet. Also, is it adviced to install every single signature? I'm just asking because you make it an option, I'd have thought that everyone would naturally want them all. The scan doesn't take long, even having every single one installed. I think to scan an image takes about 2-3 seconds (average size of 2-5 MB image).

**Comment by Maikuolan** [comment]
> Each time the programme is used, I keep getting the following error in my error_log.text;

*Fixed by 70a3fe2553922245faf95ef95660ecb7324a4bec.*

> I hope it's still working as it should. It hasn't detected anything yet.

Should be. This bug wasn't a fatal bug and shouldn't prevent phpMussel from working properly.

> Also, is it adviced to install every single signature? I'm just asking because you make it an option, I'd have thought that everyone would naturally want them all. The scan doesn't take long, even having every single one installed. I think to scan an image takes about 2-3 seconds (average size of 2-5 MB image).

That's fantastic, if it scans that quickly. :-)

Definitely, if phpMussel with your PHP installation is able to scan files that quickly, using all the signature files would probably be the best option, I think. Unfortunately though, not all users have systems which are that fast, and phpMussel needs to be configurable and customisable in such a way that users on lower-end systems with poor memory, restrictions, limitations and so on will be able to use it properly, and in those cases, using all available signature files may slow down their systems to the point where it could easily take three or four times as long to scan files less than half that size, sometimes even timing out requests for the end-user or just crashing PHP entirely.

Obviously, these problems don't affect the majority of users, but it's important nonetheless the have a way to deal with these problems for those users which are affected.

**Comment by Maikuolan** [comment]
The general principle though: Each signature file has a particular area of responsibility, in terms of the types of infection vectors that phpMussel is able to protect against. In order to fulfill that area of responsibility, we'll want to use those particular signature files. However, in most cases, there are ways to also fulfill an area of responsibility without necessarily using the corresponding signature files.

Let's say, purely for example, that a particular signature file is responsible for scanning images. Obviously, you'll want that signature file, if you allow users to upload images. But, if for some reason, that particular signature file causes some problems, you could choose to prevent users from uploading images, such as by blacklisting various types of image files, or including some custom signatures that block all images and so on. Obviously, most sites which allow users to upload files, won't want to prevent images being uploaded, because images tend to be one of the most common types of files that users need to upload (forum avatars, embeds, post images, etc). But, the same mightn't necessarily be true for things like EXEs (executable files), APKs (Android application packages), documents containing macros, SWFs (flash files), and so on. Likewise, we'll need the corresponding signature files to scan those types of files, if they're allowed to be uploaded. But if those corresponding signature files somehow cause any problems, it might be a little more easier to choose to simply prevent the affected files from being upload entirely as an alternative to using those corresponding signature files.

**Comment by DanielRuf** [comment]
I guess he won't read the answer, the user account is deleted.

**Comment by Maikuolan** [comment]
Seems that way unfortunately. 😕

Well, at least I've given a response anyway, so that anyone else which might be interested, or which might have the same question, can see the answer, or, if he eventually creates a new account, or reads this issue again as an unregistered user, either way, will see the response.
