### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by jtallinger** [phpMussel/phpMussel#171]
Hi,

Has phpMussel been tested extensively with php 7.2.x?

I'm having some issues:
1) "regular expression is too large at offset 166" and I digged out the particular part to be:

$sig = '03f30d0a(?:..){0,3000}4c6962732f53746172746572(436d6445786563|4e65745574696c73|526563|53637265656e53686f7473|53657474696e6773)2e7079(?:..){0,5000}3c6d6f64756c653e';

if (!preg_match('/(?:' . $sig . ')/i', 'abc')) { }

Problem occurs at multiple signatures. In this particular case it will pass if I reduce 5000 to <1200.

2) If I scan certain file types (like docx) then I get:
preg_match(): Null byte in regex
I have not narrowed the exact part yet, where in the code it gets stuck.

3) When I scan PDF files it gets following at the URL scanning section:
Undefined offset: 2

if (preg_match_all('~(?:data|f(?:ile|tps?)|https?|sftp)://(?:www\d{0,3}\.)?([\da-z.-]{1,512})[^\da-z.-]~i',
$URLScanner['FixedSource'], $URLScanner['Matches'])) {

// TODO: Why original source code has [2] here?
foreach ($URLScanner['Matches'][1] as $ThisURL) {
...

Running a var dump on matches shows only index 0 and 1?

array(2) {
--
  | [0]=>
  | array(12) {
  | [0]=>
  | string(18) "http://www.w3.org/"
  | [1]=>
  | string(20) "http://ns.adobe.com/"
  | [2]=>
  | string(20) "http://ns.adobe.com/"
  | [3]=>
  | string(20) "http://ns.adobe.com/"
  | [4]=>
  | string(20) "http://ns.adobe.com/"
  | }
  | [1]=>
  | array(12) {
  | [0]=>
  | string(6) "w3.org"
  | [1]=>
  | string(12) "ns.adobe.com"
  | [2]=>
  | string(12) "ns.adobe.com"
  | [3]=>
  | string(12) "ns.adobe.com"
  | [4]=>
  | string(12) "ns.adobe.com"
  | }
  | }

**Comment by Maikuolan** [comment]
Hi nemiq,

Which version of phpMussel are you using currently? There was a bug affecting this part of the codebase found and fixed back in v1.3.1, so I would anticipate problems like these with any versions prior to that. If you're using an older version, I would firstly recommend updating and testing again, to confirm whether the problem persists. Otherwise, if you're using a version newer than that or using the latest codebase, and the problem still persists, it could be something new, so I'll do some more testing to see whether I can replicate it on my end and figure out what's going on (I haven't seen this kind of behaviour before with any newer versions or the latest codebase).

**Comment by jtallinger** [comment]
Hi,

Version 1.5.0, pulled through composer. I have refactored a lot of the code, making a "Laravel" version of this package. But I have not modified anything in the datascanner function, and as I can break out the actual issue I was wondering if this is php installation/configuration issue or something else. I tried on my staging and production server but same problem there (also running 7.2.7).

PCRE (Perl Compatible Regular Expressions) Support | enabled
PCRE Library Version | 8.42 2018-03-20
PCRE JIT Support | enabled

pcre.backtrack_limit | 1000000
pcre.jit | 1
pcre.recursion_limit | 100000

Br, Joakim

**Comment by Maikuolan** [comment]
> // TODO: Why original source code has [2] here?

That's.. an awkward mistake on my part. Basically, during a refactor a while back, the expression used for the match intended to populate the array for that loop was modified, and the loop *should* have been also modified accordingly, but I missed it during the refactor, and.. somehow consequently didn't pick up on it after either, until your mentioning it now. So, [2] *was* correct, when first written, but isn't correct anymore. It really should be [1] now. '^.^

The exact line in the commit where the expression was modified: [`b36a018fbc5b09bd4a414d469f0d51c3d2da2751#diff-a280b2eecaa2bd1690b9f424e3fccb93R2162`](https://github.com/phpMussel/phpMussel/commit/b36a018fbc5b09bd4a414d469f0d51c3d2da2751#diff-a280b2eecaa2bd1690b9f424e3fccb93R2162)

Marking this issue as "bug" and "work-in-progress", and I'll commit a fix for that particular bug within the next few minutes. Haven't looked too closely yet at the other problems raised by this issue though (at work at the moment, so back-and-forth between doing other things and then coming back to this when I get a spare moment; I'll look more closely at everything when I get back home a little later though).

> Has phpMussel been tested extensively with php 7.2.x?

The package's *to-do* list regarding "unit tests" is quite extensive. The repository is integrated with Travis-CI, but the current extent of unit testing is basically letting the package execute in various environments and failing the tests if anything errors out during execution (i.e., no individual "units" are currently being tested; just the possibility of erroring out during execution overall).

We started an issue for writing better units tests at #92, but that hasn't been done yet (and actually, the "units" themselves have significantly changed since that issue was created, so it's probably outdated by now and needs to be closed/recreated anyway).

Though, if a new list was to be created today, to list all the units which need tests, it would likely become outdated again in the near future, because I also plan to completely dump/rewrite/overhaul the way that phpMussel handles archives in the near future, due to multiple problems with the way that phpMussel handles archives currently and in the recent past (i.e., there's a strong likelihood that any code currently in phpMussel responsible for handling archives or archive content will be gone and replaced by something else in the near future).

Everything is *manually* tested prior to releasing new versions too, to check for any obvious problems and to check whether the package will behave as expected for most standard use-cases, though obviously the particular above-mentioned bug was missed during manual testing too, which demonstrates the need for better testing, one way or the other.

To be clear though: I won't defend the fact that I'm currently relying heavily on manual testing to ensure that phpMussel is bug-free, and that its unit tests are currently severely lacking, because I'm aware of, and agree, that this is a problem. Available time is a major problem though, seeing as I'm involved in a number of different projects, and my main employment needs to always take priority over any of these projects. I hope to eventually get that sorted out though, or, if anyone else is interested in taking over responsibility for unit tests, I would be very open and welcoming to that possibility (PS.. to any potential contributors, subscribers, followers, etc: There could be a few PR opportunities in that for Hacktoberfest, in case you're looking for such opportunities).

> preg_match(): Null byte in regex

There definitely shouldn't be any null bytes included in any patterns anywhere in the codebase, so if in fact null bytes do exist somewhere there.. I'd wager that it's probably bug, and I've made a mistake somewhere. In any case though, I'll look a little more closely at that when I get a spare moment.

**Comment by jtallinger** [comment]
Hi Caleb,

Thanks for explanation, no need to defend. I think you have done a great job by bringing this complex task of scanning files into a php package. I'm currently working on a decently big laravel project and an external security audit pointed out that uploaded files are not scanned, no ClamAV running on the server unfortunately either. Hence I found this project and have the past few days worked on converting the code base into a laravel package. I was planning to upload it as an fork once done, but I want to sort out current issues first.

The actual code changes are not really big functionality wise, it is more about putting all functions(.php) into a service class, move translations to laravel language resource files and replacing the .ini-config with plain laravel config. Now I can integrate it easily and also use it for ajax file uploads with JSON response when scan fails.

I used the sigtool to generate signature files, is there any explanation on what each file is for? I.e. *.hdb/*.htdb and elf_db vs. elf_db_regex? Any recommendation on which files to use for a moderately "safe" setup?

I'll continue debugging and I'll also use the signature files from the repo to see if they work differently.

**Comment by jtallinger** [comment]
preg_match(): Null byte in regex issue:

```
// Determine whether the file being scanned is a macro.
$this->memCache['file_is_macro'] = (
   preg_match('~vbaProject\.bin$~i', $Filename) ||
   preg_match("~^\xd0\xcf|\x00Attribut|\x01CompObj|\x05Document~", $Data)
);
```

I think we can change the escaping from " to ' to handle the null byte reading?

Test:
```
if (!preg_match('~^\xd0\xcf|\x00Attribut|\x01CompObj|\x05Document~', 'abc')) {
   echo 1; die;
}
```

**Comment by Maikuolan** [comment]
> Thanks for explanation, no need to defend. I think you have done a great job by bringing this complex task of scanning files into a php package.

Thanks, and appreciated. :-)

> Hence I found this project and have the past few days worked on converting the code base into a laravel package. I was planning to upload it as an fork once done, but I want to sort out current issues first.

That actually sounds really cool, I think. No obligations of course, but if you did upload it somewhere publicly, quite a large number of users could benefit from that, I think. A really good idea. :-)

In any case, I would love to hear about your experiences with it all, both positive and negative alike, when everything is finished, if there's the time and opportunity for it.

> I used the sigtool to generate signature files, is there any explanation on what each file is for? I.e. *.hdb/*.htdb and elf_db vs. elf_db_regex?

Yep. Best first point of call would be the __[SigTool generated signature files list](https://github.com/phpMussel/SigTool/blob/master/_docs/readme.en.md#sigtool-generated-signature-files-list)__ and __[Note regarding signature file extensions](https://github.com/phpMussel/SigTool/blob/master/_docs/readme.en.md#note-regarding-signature-file-extensions)__ parts of the SigTool documentation. It's not overly elaborate or detailed, but briefly summarises the differences between the different signature file extensions, names, etc.

It covers those which SigTool generates, as well as a few others. The difference between the *clamav_%* and *phpmussel_%* signature files (the documentation doesn't mention this specific point) is just to be able to easily separate by vendor when needed, and for better maintainability (*clamav_%* signature files are sourced from ClamAV, whereas *phpmussel_%* signature files are sourced from elsewhere, either written myself, or by other contributors, or adapted from other sources).

> Any recommendation on which files to use for a moderately "safe" setup?

A general rule of thumb that I would recommend to most users: Sort out package configuration first, before sorting out which signature files to use. The various configuration directives provide, for example, the opportunity to allow/disallow specific file extensions, specific types of files, etc.

File extensions are not usually a reliable indicator of file type, nor any kind of guarantee of whether a file will be safe or unsafe. However, for some types of files, the package provides the ability to detect some basic "chameleon attacks" (attacks whereby an attacker will attempt to circumvent security by tricking a system into thinking that a file being uploaded/handled is of a different type than it really is, often by way of changing the file extension, faking magic numbers, etc). Enabling the configuration directives which relate to chameleon attack detection should improve the reliability of file extensions for the file types relating to the enabled configuration directives.

In such cases where there are specific types of files disallowed by configuration, and where chameleon attack detection is also provided, we won't need to install/activate/use any signature files which relate specifically to those disallowed types of files, because we can assume those types of files will be blocked anyway, regardless of whether they're infected (thus scanning them becomes redundant). Because scanning file uploads can be quite intensive on memory, and can be sometimes be a little slow with specific types of files in some situations, avoiding any unnecessary scanning can improve efficiency and speed things up quite a bit.

The most notable example of this (where significant bottlenecks can occur) is for Windows PE (portable executable) files (e.g., EXEs, DLLs, etc). Although phpMussel will definitely help with securing against these kind of infected files, I would definitely never call it a "magic bullet", especially when working with a reduced/minified/streamlined signature database, as in most cases, this is generally going to be the favoured infected vector for most viruses/malware/trojans/etc, and there are new threats emerging literally every single day. However, this is also generally going to be the least frequently *needed* file type in most cases, for most websites, so.. if we do need them to be uploaded, obviously we'll want to install/activate/use the related signature files, but conversely, if we don't need them to be uploaded, and if there's the risk of a bottleneck, it would make sense to ditch the related signature files.

Conversely, in cases where we definitely need to allow some specific types of files to be uploaded, as well as in cases where file extensions could be completely unreliable and where chameleon attack detection isn't yet provided, we should definitely install/activate/use any related signature files, too.

**Comment by Maikuolan** [comment]
> I think we can change the escaping from " to ' to handle the null byte reading?

Yep. Good spotting. That does the trick. :-)

Will commit shortly.

**Comment by jtallinger** [comment]
Can't figure out the other issue with "regular expression is too large at offset". I'm getting same problem when testing at https://regex101.com/ so it is not server related. 

Same problem even when reducing the pattern from: 
03f30d0a(?:..){0,3000}4c6962732f53746172746572(436d6445786563|4e65745574696c73|526563|53637265656e53686f7473|53657474696e6773)2e7079(?:..){0,5000}3c6d6f64756c653e 

To:
(?:.){0,5000} 

If I remove the end limit (using {0,}) then it passes, but I don't know how that would affect the scanning and overall performance? Also that would require some change in the signature files. I'm just puzzled how this have worked for others?

Regarding the signature files, thanks for the explanation. Two more questions:
1) What is the difference between I.e. clamav and clamav_regex? Are they doing the same job or should both be included in the active directive? 
2) It says for clamav.db: "Targets all types of files; Works with file hashes.". Does it mean it already includes the other files like clamav_elf.db and they don't need to be included specifically?

**Comment by Maikuolan** [comment]
> What is the difference between I.e. clamav and clamav_regex?

The *%_regex%* signature files contain patterns/expressions, and phpMussel leverages PHP's PCRE functions (e.g., preg_match, etc) to process those, whereas the others don't and in most cases can generally be processed using just normal string functions (e.g., strpos, substr, etc). The idea is to process signatures in whatever way will be the quickest and most efficient way to process them (although PCRE is very powerful, and actually an essential thing for phpMussel, if the same thing can sometimes be achieved using simpler, quicker means, we may as well do that).

Of course, if we're processing some signatures in one way, and other signatures in other ways, we'll need a way to identify which are which, and that's where separating them into different files like that comes in.

> Are they doing the same job or should both be included in the active directive?

Generally, they should both be included (unless for some reason, some particular server has very strict PCRE limitations, but the backtrack and recursion limits you mentioned in one of your earlier replies look pretty good, and should definitely be sufficient, so I don't think we need to worry about that so much).

> Does it mean it already includes the other files like clamav_elf.db and they don't need to be included specifically?

Would still need to be specifically included (i.e., specifically marked in the `Active` configuration directive). Briefly, a long time ago (phpMussel versions < v1.0.0), phpMussel signature files could call each other, and didn't necessarily all need to be included, but it became a little too complex and wasn't so maintainable, so that ability doesn't exist anymore in any current versions. Nowadays, if a signature file isn't specifically included, phpMussel won't use it.

**Comment by Maikuolan** [comment]
(( Re: The problem with `(?:.){0,5000}` )): I suspect there may be some differences between PHP's PCRE engine, and ClamAV's own expression engine, which makes capture ranges like these in signatures perfectly okay and safe for ClamAV to use (or I assume perfectly okay, at least, given that I doubt they would knowingly implement a capture range into their signatures if it could break their own engine). TBH, I haven't ever looked closely at the source code for PHP's PCRE engine, so I'm not entirely sure the exact details about nor differences between how it handles capture ranges that have specific lower and upper limits versus capture ranges that don't have specific limits. Though, from this issue, and from some similar problems I've had in the past with capture ranges that have specific lower and upper limits, I'm wondering whether maybe I should update SigTool to automatically filter these types of signatures out entirely when preparing new signature files for phpMussel from the ClamAV database.

**Comment by Maikuolan** [comment]
I've made some slight changes to SigTool, that I'm hoping should resolve the problems associated with huge capture group ranges in signatures. I've committed and pushed these changes, as well as a new signature files cut, and tagged new versions/releases for both SigTool and phpMussel alike.

When you've got a spare moment, could you update to the latest version of the signature files, try running a few more scans, and let me know whether these errors continue? Cheers.

**Comment by jtallinger** [comment]
Hi,

I just merged recent changes and started to run some tests. Getting:
> Undefined offset: 1

At line 2548 (preg_split):
```
if (strpos($ThisSig, ':') !== false) {
                        $VN = $phpMussel['SplitSigParts']($ThisSig);
                        if ($ThisConf[3] === 2) {
                            ...
                        } elseif ($ThisConf[3] === 0 || $ThisConf[3] === 1) {
                            $ThisSig = preg_split((
                                $ThisConf[3] === 0 ? '/[^\da-f>]+/i' : '/[\x00-\x1f]+/'
                            ), $VN[1], -1, PREG_SPLIT_NO_EMPTY);
```

Running a var dump on VN gives:
> array(1) { [0]=> string(24) " Osx.Trojan.Janicab-1" }

It runs a bunch of signatures before this one hits. Problem is caused by signature itself(?):
$ThisSig:
> string(25) " Osx.Trojan.Janicab-1:"

**Comment by jtallinger** [comment]
For now I bypass empty signatures until issue is figured out. Then I logged following (which is down from ~35):

Anti-virus: Signature errors during file scan: 7 of 35546
Last error message: preg_match(): Compilation failed: number too big in {} quantifier at offset 78
Last signature: 7265766973696F6E20383630206C747B717569747D69662F417B2F4434303C(?:..){122880,}39303930393039303930393039303930393039304538303030303030303035

**Comment by Maikuolan** [comment]
Thanks for letting me know. Definitely, the reported signatures here shouldn't have gotten through, I think. I've gone through them all again, and I *think* I've managed to remove all problematic signatures from the latest cut available at the signatures repository, as well as update SigTool again to be able to detect and remove them from future cuts. Should be solved now, I think. Let me know if more problems arise though.

**Comment by Maikuolan** [comment]
Marking as fixed and closing, at least for now. If you encounter any more, similar problems though, feel free to reopen the issue.

**Comment by ibanks** [comment]
From my understanding, this is fixed in v1.60 but it looks like this is still "dev". Has this fix been officially release for Laravel?

**Comment by Maikuolan** [comment]
> From my understanding, this is fixed in v1.60 but it looks like this is still "dev". Has this fix been officially release for Laravel?

There is a related issue at [phpMussel/SigTool](https://github.com/phpMussel/SigTool/issues/4), which I've left open, because at least two different users have reported seeing this problem to me, but as yet, I haven't been able to actually replicate the problem at my end. From my end, AFAICT, it looks fixed. But, until I can either replicate the problem at my end, or get the all clear from those users that've reported seeing the problem to me, that they're no longer seeing the problem, I'm wary of closing the issue, and planning to leave it open for the moment.

**Comment by Maikuolan** [comment]
In regards to releases specifically for Laravel: @jtallinger could probably provide an answer to that, I think, but I don't personally have anything to do with that (I'm just managing the main package here, related repos attached to this org, etc), so I'm not sure, TBH. :-)

**Comment by ibanks** [comment]
@Maikuolan No problem. Thanks for your reply. I've decided to discontinue using phpMussel for my company's project since there isn't a public solution to use it load it within a Laravel framework. Also, I understand you more than likely being busy with things do not have the time to maintain it any longer. Thanks for taking the time to create it in the first place. We did find it useful up until a certain point :-)
