### ISSUE TITLE
CI and tests

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#177]
We should move the .travis.php file to tests/PhpmusselTest.php or similar for native PHPUnit testing and change the yml file (remove the phpunit line).

Also let's also test more PHP versions and on all three platforms supported by Travis CI.

**Comment by Maikuolan** [comment]
Sounds good. :-)

**Comment by Maikuolan** [comment]
Have began some work on this (for now, just mirroring how we added Codeception to CIDRAM, because we already know that works, and how it works, which makes it an easier, more straightforward way to move forward here with phpMussel). The `.travis.php` file has been deleted and a `tests` directory created accordingly. Haven't yet added any actual tests (other than the basic loader test).

**Comment by Maikuolan** [comment]
Some basic tests implemented. This should be worked on further in the future, but seeing as the main elements of this issue have been resolved, so it should be okay to close this now, I think.
