### ISSUE TITLE
Anonymise IPs by default

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#179]
@Maikuolan we should do this by default (GDPR), otherwise many users log IPs which is problematic.

**Comment by Maikuolan** [comment]
Agreed, and good idea. :+1:

I'll get started on that shortly.

**Comment by Maikuolan** [comment]
Forgot to reply to this earlier. Sorry about that. IPs should now be pseudonymised by default, at least (since 42060e9688e31a09e770a55691efee9a8ce613d2, committed mid-January). Current pseudonymisation implementation just x-outs the final octet in IPv4 addresses (e.g., `11.22.33.44` becomes `11.22.33.x`), and rounds IPv6 addresses up to the nearest 32 (e.g., `1:2:3:4:5:6:7:8` becomes `1:2::x`). Do you think this would be sufficient, or should we take it further (e.g., dropping IP addresses entirely from logs and such, working towards complete anonymisation)?

**Comment by DanielRuf** [comment]
> Forgot to reply to this earlier. Sorry about that. IPs should now be pseudonymised by default, at least (since [42060e9](https://github.com/phpMussel/phpMussel/commit/42060e9688e31a09e770a55691efee9a8ce613d2), committed mid-January). Current pseudonymisation implementation just x-outs the final octet in IPv4 addresses (e.g., `11.22.33.44` becomes `11.22.33.x`), and rounds IPv6 addresses up to the nearest 32 (e.g., `1:2:3:4:5:6:7:8` becomes `1:2::x`). Do you think this would be sufficient, or should we take it further (e.g., dropping IP addresses entirely from logs and such, working towards complete anonymisation)?

Thanks, this should be sufficient.
