### ISSUE TITLE
Normalize settings

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#181]
We have settings like `this_is_a_setting` but also `ThisIsASetting` and `Active`.

Should be all lowercase and with underscores imo (improves readability).

**Comment by Maikuolan** [comment]
Agreed. Actually, I consider this as a high priority thing, and as one of the very first things that should be done when development on phpMussel v2.0.0 begins.

I regard changing the names of existing configuration settings as backwards-incompatible changes though, due to how it could affect configuration customisations for existing users, so probably not something we should do for any v1 releases.

Thinking of branching for v2 and starting on that in January though, so not too long to wait.

On that note.. I think I prefer `ThisIsASetting` and `Active` more than `this_is_a_setting`. What do you think would be better? Or something else entirely maybe?

**Comment by DanielRuf** [comment]
`this_is_a_setting` is better to read and what I would use as variable types (snake case).

**Comment by Maikuolan** [comment]
Fast-forward to.. April 2. I haven't forked for v2 yet. 😢

(Has taken me longer than I'd anticipated to plan everything out, mostly due to external distractions).

I'll get onto that soon though.

Anyway, thinking on it more since our most recent replies to this issue, I'm thinking we'll go with `snake_case`, too. (I'll start normalising everything to that as soon as v2 is forked). 😊

**Comment by Maikuolan** [comment]
Was originally planning to sort out the new package structure (e.g., figuring out how to move most of the code out from the functions file, into distinct, individual classes; how to decouple the front-end, CLI-mode and so on from the package core; etc) before worrying out this too much, so that my commits would look slightly cleaner, to avoid any risk of duplicating work and so on. But, I also would prefer to not cause any issues to stagnate for longer than necessary, so.. I've gone ahead and finished implementing these changes now anyway (implemented by 7fb5da86326c21cb86a5bd5e7ceba8e3e5236abf). In any case.. was still hoping to sort this out pretty quickly after starting work on v2, so whatever. And, however commits end up eventually looking, I can at least close this off now (which is one small step closer to v2). '^.^
