### ISSUE TITLE
Scan of specific folder gives Warning + Fatal Error

### ISSUE THREAD

**Issue by gthbbr** [phpMussel/phpMussel#183]
### phpMussel version used.
1.8.0-DEV+19006606

### Signatures version .
2019.6.475 (ClamAV Standard,...)

### PHP SAPI used.
fpm-fcgi

### PHP version installed.
7.2.11

### Operating system used.

Linux dd41124 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64
(Shared Host)

---
## Issue
Scan of a specific folder with own php file ist not working as expected.

### Expected behavior
Scan of the a folder (joomla home folder) on the server with output of results.

### Actual behavior
Warning: preg_match(): Compilation failed: number too big in {} quantifier at offset 78 in /www/htdocs/xxxxxx/phpmussel/vault/functions.php on line 2619

[...]

Fatal error: Maximum execution time of 30 seconds exceeded in /www/htdocs/xxxxxx/phpmussel/vault/functions.php on line 2596

### Steps to reproduce the behavior
run my php script in the phpmussel folder with:
```
<?php
require 'loader.php';
$phpMussel['Set-Scan-Debug-Array']($Foo);
$results = $phpMussel['Scan']('/www/htdocs/xxxxxx/folder', true, true);
var_dump($Foo);
echo $results;
?>
```

---
Thanks for this great tool!
I'm a total beginner and tried to understand all available information, but seems that I need some hint or help here. Thanks a lot in advance!

PS: as I try to scan '_testfiles' it's working. But starting also with the same warnings and sometimes another warning in between: "unmatched parentheses at offset 321 [...] functions.php on line 2619".

PPS: In my case phpMussel seems not to find base64 malware in files. The Antivirus of my host has found several and if I scan them again with phpMussel there is the result "no problems found". (with all clamav signatures activated).

**Comment by Maikuolan** [comment]
Hi @gthbbr. Sorry for the delayed reply.

I've been doing some testing, but haven't been able to replicate the problem on my end yet.

I *suspect* that the problem might be related to **[<ruby>_this_<rp>(</rp><rt>SigTool/#4</rt><rp>)</rp></ruby>](https://github.com/phpMussel/SigTool/issues/4)** issue (similar PCRE warning; also haven't been able to fully replicate on my end yet), but couldn't 100% guarantee that the two issues are related until I'm able to replicate them both.

Still testing things though. I'll reply here again when I have some more ideas about what might be going on.

**Comment by huemane** [comment]
I've had the same warning quite a few times (Warning: preg_match(): Compilation failed: number too big in {} quantifier at offset...) but found out that it was either one or some of the signatures causing it.
I had all sig's activated so I deactivated them and only activated the one(s) i knew i might need at the moment. 
A quick way to do this is simply commenting out the activated sig's in the config.ini file, you don't have to do it manually through the frontend which can be tedious if doing all of them.
Since i did this, the warnings have gone.

Regarding the "fatal error: Maximum execution time of 30 seconds exceeded" error, this is likely due to your "max_execution_time=3600" in your php.ini - if you have access to it you can simply change it to something bigger. If not, google it, there are other ways you can try or you can ask your host to do it - but they might not like to.

Regarding the base64 issue, read this page (https://serverfault.com/questions/817687/maldet-with-clamav-missing-php-base64-decode-eval-hacks) and see the best answer - they are saying after installing the Malware Signatures from malware expert, the base64 issues are resolved.
Direct download links to the signatures are on this page: https://malware.expert/signatures/
Then just add them to your active sig's list in the config.ini like so: ,malware.expert.hdb,malware.expert.ndb...
I've just installed the .ndb & .hdb sig's (as i don't see the other two extensions used in phpMussel) and it doesn't crash my phpMussel but i haven't tested on a base64 infected file as i don't have one... (yet) lol.

(@Maikuolan  - correct me if i'm wrong on any of this) :)

Hope some of this helps :)

**Comment by Maikuolan** [comment]
> Then just add them to your active sig's list in the config.ini like so: ,malware.expert.hdb,malware.expert.ndb...
> I've just installed the .ndb & .hdb sig's (as i don't see the other two extensions used in phpMussel) and it doesn't crash my phpMussel but i haven't tested on a base64 infected file as i don't have one... (yet) lol.

It shouldn't crash phpMussel, but phpMussel won't use them either (not without some small modifications, anyway). The signature files originally released by ClamAV and the signature files used by phpMussel are mostly the same, but there are some small differences. Because phpMussel uses PHP's PCRE expression engine to handle expressions, and it works differently to ClamAV's own expression engine, any expressions used by signatures need to be translated from ClamAV-compatible expressions to PCRE-compatible expressions. The [SigTool](https://github.com/phpMussel/SigTool) package that I wrote handles all this automatically though (the SigTool used by ClamAV itself is a different package; the shared name is intentional, to make the similarity in purpose more obvious, in the sense that ClamAV's SigTool prepares signature files for ClamAV, and phpMussel's SigTool prepares signature files for phpMussel). phpMussel's SigTool also adds a small header to signature files, to help phpMussel determine the type of signature file it is, and to determine the best way for phpMussel to process the signature file (ClamAV's own, native signature file format doesn't have such headers, using mostly the file extension to determine the type of signature file it is, and some other mechanisms in some cases specific to ClamAV). I maintain the same file extensions for phpMussel signature files, mostly out of aesthetic, and to make it easier, at a glance, for us to quickly identify which signature files are what, and doing what, and to quickly identify how they relate to their ClamAV counterparts, when we look over them, but phpMussel (current versions, anyway) actually solely uses these small headers added by SigTool to determine that information.

What this means is.. It should be relatively easy to apply these same modifications to the free signature files that Malware Expert releases, in order to be able to use them, but using their free signature files, without modification, won't work, because phpMussel won't find the header that it looks for to determine the type of signature file it's looking at, will assume the signature file is corrupted or broken, and just ignore it, moving on automatically to the next signature file in the queue. So, no crashing, but nothing caught either.

It would be relatively easy for me to add the Malware Expert signature files with the necessary modifications to the phpMussel signatures repository and make them available to install and activate via the front-end in the same manner as all the other currently available signature files, but I need to figure out first whether Malware Expert would be okay with that.

I can't see any license information anywhere on the page, so I've sent them a quick message via their contact page to ask them for verification about it, to let me know whether redistribution would be okay. The signatures are freely available, and the way they've presented the signature files, to me, strongly implies that it would be perfectly okay to *use* them, with no legal question there, but adding them to the phpMussel signatures repository could constitute *redistribution*, which would be a little different to just using them. Anyway, I'll reply here when I get a reply from them, to confirm what they tell me, whether it's okay or not to do this.

**Comment by huemane** [comment]
Good to know! Thanks for the clarification, its really cool that you can get new signatures to work with PHPM! It will keep it in the loop 🙂

**Comment by Maikuolan** [comment]
I received a reply from them. They're okay with it, so we're good to proceed. I'll reply again when it's done. :-)

**Comment by Maikuolan** [comment]
Partially implemented. Hash signatures have been integrated directly into existing signature files. Haven't gotten around to sorting out the others yet, but will get to that shortly.

**Comment by huemane** [comment]
Excellent! Great stuff 🙂

**Comment by Maikuolan** [comment]
@gthbbr @huemane The problem originally described by this issue should now be resolved as of the most recent cut of the signature files, due to recent changes made to SigTool ([v1.0.0](https://github.com/phpMussel/SigTool/releases/tag/v1.0.0)), so for the moment, I'll go ahead and mark this as resolved. If you encounter the problem again, let me know. Cheers. :-)

I'll keep the issue open for the moment, to enable any further discussion, and due to some things on the periphery that haven't quite been entirely resolved yet (e.g., fully implementing the new malware signature files and so on). I'll try to sure-up some of the internal guard code and other safety checks within phpMussel related to the originally described problem too, when I get a bit more spare time in the near future.

**Comment by Maikuolan** [comment]
The source for the new signature files doesn't seem to have direct download links anymore to the remaining signatures which I hadn't gotten around to implementing yet. Not sure I'll be able to do those now. Anyway, everything else here has been sorted out, so I'll go ahead and close this issue now.
