### ISSUE TITLE
Local development server

### ISSUE THREAD

**Issue by huemane** [phpMussel/phpMussel#184]
Hi, thanks for these awesome scripts!
I'm trying to get this working on my local development server (xampp), have php & pcre and not had any apparent problems installing main script, signatures, frontend management etc. But i do get an error when trying to scan a file using the provided code:

 $results = $phpMussel['Scan']('/user_name/public_html/my_file.html', true, true);
 echo $results;

The error I'm getting is:

The function requires a string.

I'm on windows 7 using xampp and i also gave full folder permissions as described in the doc.

Any ideas as to what's wrong?

Thanks.

**Comment by Maikuolan** [comment]
Hi @huemane,

You're welcome. :-)

The mentioned error:
> The function requires a string.

Is that the exact wording of the error? I ask this, because that particular wording doesn't exist anywhere in phpMussel's language data, and isn't hardcoded into any errors or exceptions in the codebase itself, so I'm not sure whether that message is produced by phpMussel, or maybe by PHP itself, or potentially something else running alongside phpMussel.

Per the codebase, the first parameter supplied to the function must be a string, or an array of strings, representing the files or directories to be scanned; the second and third parameters must be booleans. The example reflects this, and so, is not providing incorrect parameter types to the function, so I'm not entirely sure why an error message like that would be produced.

**Comment by huemane** [comment]
Hi Maikuolan,

Sorry, the exact wording of the error message is like this:

> Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\test.php:82

Following that is a stack trace of other includes.
This is a wordpress site, could there be conflicts with includes/templates etc?
The line of code I'm using is this:

> $results = $phpMussel['Scan']('/index.php', true, true);
> echo $results;

Any ideas?

Thanks.

**Comment by huemane** [comment]
Hi Maikuolan,
I've set up a test simple non wordpress site and it works fine. I assume therefore it is a conflict with my wordpress site. Are there known issues with WordPress?

**Comment by Maikuolan** [comment]
> Are there known issues with WordPress?

Other than some possible problems with asynchronous file uploads (e.g., via AJAX, AJAJ, jQuery, etc) due to that phpMussel, by default, returns a normal HTML response, rather than whatever else whatever AJAX/AJAJ/jQuery/etc scripts/plugins/etc might be expecting (which couldn't possibly be anticipated exactly anyway), not AFAIK.

Any chance you could share what's in your `test.php` file? (Omitting out any credentials and sensitive information from the file, of course).

**Comment by huemane** [comment]
Hi,
I've sorted it out, it gave that error due to it not finding the phpMussel folder.
Thanks.

**Comment by Maikuolan** [comment]
No worries. Glad to hear you've figured out what was going on. :-)
