### ISSUE TITLE
which signature(s) do i use for video file uploads?

### ISSUE THREAD

**Issue by huemane** [phpMussel/phpMussel#185]
which signature(s) do i use for video file uploads?
I installed all signatures but get False Positives with some video file uploads which to my knowledge are clean. I also get FP's with large video files.
Thanks.

**Comment by Maikuolan** [comment]
I'm going through all the signature files currently actually so that I can write something up to answer this question properly, in more detail. I'll reply again a little later tonight or early tomorrow.

**Comment by Maikuolan** [comment]
Done. :-)

I've written up some basic information about the various signature files, when to use them and when to not use them, and committed it to the directories containing the various signature files in the signatures repository, here:

https://github.com/phpMussel/Signatures/blob/master/misc/readme.md
https://github.com/phpMussel/Signatures/blob/master/clamav/readme.md

If you're only dealing with video uploads, then there's quite a few signature files that you likely won't need, I think. Any signature files where I've mentioned potential "performance costs", or where I've mentioned there being a "very number of signatures", I would definitely ditch, due to that video files usually tend to be quite large, and so would have a high chance of triggering some of those performance costs in some cases.

There aren't any signature files dedicated specifically for video files, although the graphics signature files could have some cursory relevance in some cases, possibly. Most of the signature files that aren't dedicated to specific formats (like the "complex extended signatures files", for example) would definitely be useful for things like fake video uploads (due to some of the chameleon attack detections included in those signature files), and for detecting other types of malicious files that might be pretending to be video files and similar such things.

The URL signatures file could be useful, too (for malicious links embedded in subtitle files and such things, maybe; not something I've really seen happen in the wild, but a potential theoretical benefit anyway, maybe).

There definitely exists malware and viruses that use videos as their preferred infection vector, but it's relatively rare, and not an overall preferred choice for the creators of most malware and viruses nowadays, so the risk associated with video files is relatively low compared to various other potential infection vectors (e.g., executables, script files, archives, infected Word documents, etc). As long as it's actually a genuine video file and not something else, and as long as anyone attempting to access the file (e.g., you, your users, your website visitors, etc) regularly updates whatever software they use to access and read that file (i.e., ensures that they're not using outdated, vulnerable software versions), I wouldn't worry too much about it.

If you already know exactly which types of video files you want being uploaded, and don't want other types of files being uploaded, it could be worth utilising the [filetype greylist](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#filetype_whitelist-filetype_blacklist-filetype_greylist) too, to harden phpMussel against any types of files that you don't specifically want being uploaded (which won't necessarily do anything to protect against malicious video files, but would help save time and processing power by removing the need to worry about whether any unwanted types of files might be malicious).

I hope that helps. Let me know if there are any further questions, clarification needed and so on. :-)

**Comment by huemane** [comment]
Brilliant, thanks again!
This does give me an idea of which signatures I'll use.
I am using JamesHeinrich's getID3 [https://github.com/JamesHeinrich/getID3](url) in conjunction with phpMussel to add as many security checks as possible as my site is primarily a video stock site so there will be a lot of uploading going on.
I have noticed that other video stock sites have recently begun to no longer allow direct file uploads anymore but rather to allow imports from URL's to existing uploads, I wondered if this had something to do with recent File Upload Vulnerabilities discovered especially within wordpress sites... [https://www.wordfence.com/learn/how-to-prevent-file-upload-vulnerabilities/](url)
Anyway, thanks for all your help, this is an amazing repository and ou have done a LOT of excellent work!
:+1:
