### ISSUE TITLE
phpMussel is not scanning my Wordpress site

### ISSUE THREAD

**Issue by Josuejoelmm** [phpMussel/phpMussel#187]
## Issue
i did uploaded phpMussel, rename config.ini, and hook into wp-config.php file this ( require '/home/oxoftmed/zowagroup.com/phpmussel/loader.php'; )... now, What should normally happen?? how to scan my site ?

### Actual behavior
My site just open normally, should i open loader.php with URL like e.g: zowagroup.com/phpmussel/loader.php, to scan ?

**Comment by huemane** [comment]
Yes, open open loader.php as described and select Upload Test from the left menu.
Select a file to upload from the phpMussel\_testfiles directory and click OK.
If your install is working correctly, you should get an Upload Forbidden message.
If not, check that you are referencing your phpMussel folder correctly with the require or include method.
I initially had trouble correctly referencing mine but i found a way.
You can use it like this in your config.php or in the php code of the page you want to use it
`require( ABSPATH . '/phpMussel/loader.php' );`
ABSPATH is a wordpress function that returns your root directory path, so no matter how deep in the folder hierarchy you are, this will return the correct path.
HTH.

**Comment by Josuejoelmm** [comment]
thanks for your help, just to confirm, should i put `require( ABSPATH . '/phpmussel/loader.php' );` into wp-config.php ? or index.php ?

**Comment by huemane** [comment]
Yes you can put it in your config.php file.
When you have logged in to the /phpMussel/loader.php page,
try first to upload the testfile "graphics_standard_testfile.gif".

**Comment by Josuejoelmm** [comment]
ok, after trying many times without success, I repeated the whole process, delete mussel and upload it again, rename config.ini, change disable_frontend to false, place `require (ABSPATH. '/phpMussel-phpMussel-114df0a/loader.php');` inside wp-config.php, I opened the loader.php and I was successful, I logged in phpMussel but when I click upload test, phpMussel asks me to log in again. Any idea of ​​the problem?

**Comment by Maikuolan** [comment]
Does the phpMussel directory have write permissions (CHMOD) set correctly? Not certain that this is the problem here, because if it's installed in Wordpress, write permissions are *probably* already correct (would've had to set permissions when first setting up Wordpress anyway, because of plugins, themes, templates, etc).. but it could be worth checking anyway, to confirm. Without write permissions, phpMussel won't be able to create sessions correctly, which could theoretically cause login/logout problems like that.

**Comment by Josuejoelmm** [comment]
I was able to upload graphics_starndard_testfile.gif already and it yielded me the following message "uploaded denied", i noticed that the test does not always work, I tried to load another file from the _testfiles folder and when i click on the "OK" button, the only thing it does is to reload the same page "upload test" ... putting all this aside, I'm more interested in scanning my wordpres, how do i scan my wordpress from the phpmussel front-end?

**Comment by huemane** [comment]
That is the correct error message you should be getting when uploading an (apparently infected) test file. Also, if you haven't activated any signatures yet then that's the only file that it will scan (as far as i understand).
Why do you want to scan your whole wordpress site? All you really need to scan is the UPLOADS folder unless you have other folders that users can upload to?
If you do want to scan your whole site, I assume you will need quite a few of the various signatures to cover all WP's different file types. However, I can see this taking a LONG LONG time even doing it on your local machine. Why not just use an antivirus scanner for that?
AFAIK phpMussel is designed and intended to give your live site/server realtime protection from file uploads, its not meant to be an all inclusive antivirus package.
(@Maikuolan - correct me if i'm wrong - just trying to help lighten your load) :)

**Comment by Josuejoelmm** [comment]
ouh, I'm sorry, I thought I could analyze all the files on my site, thanks for your clarification and help

**Comment by Maikuolan** [comment]
> (@Maikuolan - correct me if i'm wrong - just trying to help lighten your load) :)

I appreciate it! And, correct in your thinking regarding phpMussel's intended purpose. :-)

If you wanted to scan your *entire* WordPress site though (or whatever other website, for that matter, too; one possible scenario where I could see this being useful, might be if you've already been accepting user uploads for some significant amount of time, these user uploads could've potentially interacted with your website in ways other than simply being stored, if you're only just now implementing phpMussel, and want to check whether phpMussel would've potentially blocked any of the files which were already uploaded prior to implementing phpMussel), it would be possible to do this, by writing a custom PHP script to call the `$phpMussel['Scan']()` closure to trigger a scan of the root directory. More information about that is [available in the documentation](https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.en.md#30-how-to-use-for-web-servers), too.

In terms of how long it would take to complete such a scan.. The time required to scan an individual file can vary, based on things like the type of file being scanned, how big it is, the number of signatures used, which signatures are used, configuration and so on. Generally though, if we're talking about things like simple HTML files, small images and such, it shouldn't take more than a second or two to finish scanning the file, and would hopefully take even less time than that, if we've been able to properly optimise an installation to suit the particular needs of the website in question, to detect what we want it to detect and to ignore anything we don't care about. However, that said.. due to that an entire, complete WordPress installation, along with its plugins, themes, templates and so on, could potentially comprise thousands upon thousands of files.. if we (as an example) assume that it takes a hypothetical 2 seconds to scan a single, hypothetical file within a hypothetical website using phpMussel, and if we assume that this hypothetical website contains 3,000 files.. 2 seconds multiplied by 3,000 files would equal 6,000 seconds, or **1 hour and 40 minutes** necessary in order for phpMussel to finish scanning the entirety of this hypothetical website (also assuming, of course, that it actually scans all 3,000 of these hypothetical files; we could probably skip over quite a few of them by utilising the whitelist, greylist, and blacklist features in phpMussel; but anyway, this is just as a hypothetical example, and sufficient, I think, to convey the general idea I'm putting across regarding necessary time).

I could argue that such time requirements aren't too bad, considering the potential depth of scanning involved, but it'll still be a problem though, when we consider that most webservers have an automatic timeout of around ~30, ~60 seconds or thereabouts.

One possible alternative though, if you're able to download a copy of your entire website onto your local machine (or if you've already done this for development purposes, for backups, etc), could be to use phpMussel's "CLI mode" functionality. There aren't any automatic timeouts when using CLI mode, so any scan should still be able to *eventually* complete, no matter how much time might theoretically be needed to do so. I have [short video on YouTube](https://www.youtube.com/watch?v=H-Pa740-utc) demonstrating how phpMussel's CLI mode works. Whether scanning uploads or using CLI mode to scan something else, the actual scan process should still be exactly the same, but CLI mode provides a convenient interface to leverage phpMussel's scan functionality when working from your own local machine (also not phpMussel's main intended purpose, but useful for testing purposes, ensuring things are set up correctly, checking how phpMussel will react to particular files it might encounter without necessarily needing to actually connect it to your website or webserver beforehand, etc).

**Comment by Maikuolan** [comment]
After reading over my previous reply, in hindsight, I probably should've mentioned too, in case people reading this issue in the future get the wrong idea about phpMussel: Although phpMussel's CLI mode would technically allow it to scan files on your local machine, it is still nonetheless intended to protect websites. phpMussel is *not* a replacement for traditional, desktop-based anti-virus solutions.

**Comment by Maikuolan** [comment]
*Marking as resolved and closing.*
