### ISSUE TITLE
Can auto detection of uploads be disabled?

### ISSUE THREAD

**Issue by huemane** [phpMussel/phpMussel#188]
I'm trying to disable auto detection of uploads because I want to detect uploads in my own script so I can retrieve numeric results and handle those accordingly (in other words, I don't want the 403 errors, I just want the output type integers returned when an upload is scanned, then i can execute other functions in my script.)
Is this possible?
Thanks.

**Comment by Maikuolan** [comment]
Yes and no.

Yes, in the sense that it *can* be done: Due to phpMussel's modular approach, and due to that the phpMussel "core" (i.e., the actual main viscera and core functionality of phpMussel) is separated from, and not interdependent with the phpMussel "upload handler" (i.e., the code that triggers the call to the phpMussel core when files are uploaded), one very easy way to disable automatic upload scanning, is to simply delete or rename the `upload.php` file. If phpMussel can't find the `upload.php` file in the vault, phpMussel will still continue to operate normally, except in the sense that upload scanning wouldn't be automatic anymore (no errors, exceptions, etc, will be produced).

No though, in the sense that the above solution isn't necessarily regarded as a "best practice" in the context of modern programming (e.g., providing separate packages entirely for the "core" and for the "upload handler" might be considered better practice, or, failing that, just having a configuration option to disable it; as it is currently, we don't have such a configuration option). I plan to improve things for the next major version though, to align everything more closely to what we would call "best practise" at the moment. The way it is currently, generally shouldn't be much of a problem.. except that, if people update using Composer, or certain other external package managers, changes made could potentially be reverted (and thus the undesired functionality restored) when updating and such.

Anyway.. TL;DR; version: Yes, automatic upload scanning can be disabled. :-)

**Comment by huemane** [comment]
GREAT! I was actually just thinking that it may be a case of disabling upload.php.
Great work and thanks for the instant respone!
:1st_place_medal:

**Comment by Maikuolan** [comment]
No problem; You're welcome. :-)
