### ISSUE TITLE
Specific extensions check in zip (jpg & pdf) and count the files

### ISSUE THREAD

**Issue by hansknight** [phpMussel/phpMussel#190]
## Issue
I am using Zip files for updating.
And the control from phpMussel workst fine.
But is it possible to check if there are only images in JPG in the ZIP?
And can I check the max. of files to be in the ZIP?
I can realize that probably with a seperate script also.
But maybe it is in phpMussel also.

**Comment by Maikuolan** [comment]
> But is it possible to check if there are only images in JPG in the ZIP?

There aren't any native configuration options in phpMussel to do this, but it could be done easily using custom signatures. I could create something for you, if you would like?

> And can I check the max. of files to be in the ZIP?

Not currently, but this is a good idea. I could create a new option for this, I think.

**Comment by hansknight** [comment]
Thanks Maikuolan. 
I'm not a programmer. But I like to learn. (I'm 67 young)
So if you have a demo to realise the check of JPG, I will appreciate that.

**Comment by Maikuolan** [comment]
> Thanks Maikuolan.
> I'm not a programmer. But I like to learn. (I'm 67 young)
> So if you have a demo to realise the check of JPG, I will appreciate that.

No problem at all, and definitely, that can be arranged. :-)

> > And can I check the max. of files to be in the ZIP?
>
> Not currently, but this is a good idea. I could create a new option for this, I think.

The ability to flag or block archives that contain a number of files exceeding a specified limit has been implemented to phpMussel as of tonight via fa0243250d896122c374f1cf730a34a7b3fc8354 (after updating, a new, corresponding configuration directive should appear in the configuration).

About to get some sleep for the night, but I'll get that demo prepared in the morning and reply again when it's ready.

**Comment by Maikuolan** [comment]
(Just a quick update. I've been a little delayed the past few days due to distractions and having slightly less available time than I'd anticipated. I hope to have something ready soon though).

**Comment by Maikuolan** [comment]
You could try using this as a possible solution: **[experimental.cedb.gz](https://github.com/phpMussel/phpMussel/files/2923038/experimental.cedb.gz)**

After downloading, extract the contents (experimental.cedb), and copy to `/vault/signatures`. After that, add "experimental.cedb" to the "Active" configuration directive (under "signatures"). It should cause phpMussel to block/identify any archives that contain non-JPEG files.

One potential problem with this solution: Due to the way that phpMussel caches scan results, after an archive is blocked (assuming blocked as the result of a signature file, as per this particular solution), the file inside the archive that caused the block, would be blocked too, if later uploaded separately (at least, until the cached scan results expire). This is because phpMussel would regard the file as "infected", treating it accordingly when encountered again (and generally, an infected file would still be an infected file, regardless of whether or not it's inside an archive). This wouldn't usually be a problem (and would, in fact, usually be desirable behaviour), but I mention this as a *potential* issue, because the distinction of "this file is unwanted, and therefore should always be blocked" (normal behaviour) versus "this file is unwanted specifically when inside an archive, and therefore should be blocked when found inside an archive, but should otherwise not be blocked" isn't there (i.e., a potential problem if you use this signature file *and* also want to only block non-JPEG files specifically when inside archives files but otherwise allow non-JPEG files when uploaded separately).

If this distinction is needed, let me know; I can work on finding a different way to approach this.

**Comment by Maikuolan** [comment]
*Marking as resolved and closing.*
