### ISSUE TITLE
Is there any way i could extract realtime scanning progress info to show user?

### ISSUE THREAD

**Issue by huemane** [phpMussel/phpMussel#192]
I have just coded a realtime conversion progress info window which works with FFMPEG so a user can see the progress status of an uploaded file whilst its being converted.

I'm hoping to do the same for phpmussel which is first scanning this same file before it gets processed by FFMPEG. As you can imagine, some of these files are not small hence phpmussel can take some time to process.

For FFMPEG I use php to write the status to a file and **comet** to read that file and pass the data via ajax back to the page that has the info window.

Any ideas?

**Comment by Maikuolan** [comment]
It should be possible to write a small phpMussel plugin to do the same thing for phpMussel, I imagine. phpMussel's plugin system makes it possible to execute custom code at various points during phpMussel's execution, such as during scan events.

(A boilerplate for creating new phpMussel plugins can be found **[here](https://github.com/phpMussel/plugin-boilerplate-v1/blob/master/boilerplate-v1/plugin.php)**).

phpMussel CLI-mode already displays progress information for scan events when scanning multiple files, but it is for multiple files, rather than for displaying the progress of individual files, so a simple copy/paste of that existing code probably won't quite achieve the desired outcome in this case.

With the plugin idea, I might need to add some more hooks to the core though, to be able to execute code at the correct point during the scan process for being able to ascertain progress. I'll look over it all tonight with an eye for possible new hook locations and for other possible alternative ideas too.

**Comment by Maikuolan** [comment]
(Also, I should mention, before I forget: Plugins can be written using classes and objects, too. There's nothing wrong with that. The comments in the boilerplate only mention functions and closures, but those comments are a little outdated, and should probably be rewritten at some point, when there's enough time).

**Comment by huemane** [comment]
AWESOME! Thanks for the quick response! I'll get right to it :)

**Comment by Maikuolan** [comment]
I had been meaning to add some more hooks to the codebase, to allow for a more granular, precise way to get those percentage values (as per my earlier reply), but hadn't gotten around to doing that yet. Had been caught up with other things and hadn't gotten around to it yet, but I appreciate the patience. :-)

Aside from that though, how are things looking at your end? Have you had any progress, or any specific problems or difficulties thus far?

**Comment by Maikuolan** [comment]
Hooks added (4726a38d1c43d5961e265c462888b1354766994b). No new replies for other issue participants in nearly a month now, so marking this issue as resolved and closing.

**Comment by huemane** [comment]
Super! I've been a bit caught up with other things too but will look at this asap! Will let you know when I've got something working 🙂

**Comment by Maikuolan** [comment]
No problem at all, and no rush. Take your time, and I look forward to hearing from you when you've got something working and there's more time. :-)
