### ISSUE TITLE
Instance already active! Please double-check your hooks

### ISSUE THREAD

**Issue by gunarecro** [phpMussel/phpMussel#193]
### Operating system used Windows NT INFO952 10.0 build 17134 (Windows 10) i586
---
## Issue
I'm getting the below error

Instance already active! Please double-check your hooks while scanning the file.

**Comment by gunarecro** [comment]
Hi Maikuolan,

I forgot to mention in my earlier post that the above stated issue is not only happening in window application but also in live server with AWS Centos.

Thanks
Guna

**Comment by gunarecro** [comment]
Hi Maikuolan,

I have modified the `loader.php` code as shown below.

**loader.php** inside phpmussel folder
```
/*if (defined('phpMussel')) {
    header('Content-Type: text/plain');
    echo '[phpMussel] ' . (
        isset($phpMussel['L10N']) ? $phpMussel['L10N']->getString('instance_already_active') : 'Instance already active! Please double-check your hooks.'
    );
    die;
}*/

if (!defined('phpMussel')) {
    define('phpMussel', true);
}
```
**scan.php**

```
class scan {    

        public function scanFile ($filePath) {

            require ROOT . '/phpmussel/loader.php';
            $results = $phpMussel['Scan']($filePath, false, true); // if file path is array value 2nd false means answer array

            return $results;

        }
    }
```


After changing the code, It's now working fine. Will this change cause any issue later?

Thanks,
Guna

**Comment by Maikuolan** [comment]
> After changing the code, It's now working fine. Will this change cause any issue later?

Nope; Should be okay. :-)

Sorry for not replying earlier. Got distracted. '^.^

But yeah; What you've done, is what I would've suggested doing anyway.

As a more detailed explanation: The above-quoted code (which checks whether the "phpMussel" constant is defined, and if defined, dies the script and prints that message, or if not defined, defines it, then continues processing) is intended as a kind of "sanity check". In the event that someone accidentally loads phpMussel multiple times in the same request, it's possible that phpMussel might end up scanning the same uploads multiple times in the same request (due to that the code responsible for initiating the scan could be being executed twice, thrice or more). This "sanity check" is basically a way of telling people in such cases that "hey, we don't need to do that same thing multiple times; you've probably added the same `require` multiple times to your code somewhere by mistake".

It doesn't serve any purpose other than to act as this "sanity check" though, and removing it shouldn't, AFAIK, cause any problems at all (and I think, in your case, removing it makes sense, considering that you've written your own class to load and call phpMussel when needing to scan files anyway).

**Comment by gunarecro** [comment]
Thank you Maikuolan.
