### ISSUE TITLE
Some of the files are showing as infected while upload? even it's not affected by virus

### ISSUE THREAD

**Issue by gunaerode** [phpMussel/phpMussel#195]
Server information.
phpMussel version used v1.8.0
PHP SAPI used apache2handler
PHP version installed 7.1.1
Operating system used Windows NT INFO952 10.0 build 17134 (Windows 10) i586

---
## Issue
I'm trying to upload the file from IOS App through rest API that time some of the files are showing as infected. But it's allowing from postman.

Error code:
2 | Indicates that the target was successfully scanned and problems were detected.

**Comment by Maikuolan** [comment]
Do you have scan logs enabled? If so, what does it say in the logs for the files shown as infected?

**Comment by gunaerode** [comment]
> Do you have scan logs enabled? If so, what does it say in the logs for the files shown as infected?

yes, i'm getting the blow error
`a:7:{s:10:"start_time";i:1551698960;s:8:"end_time";i:1551698962;s:6:"origin";s:13:"121.240.238.x";s:15:"objects_scanned";i:1;s:16:"detections_count";i:1;s:11:"scan_errors";i:0;s:10:"detections";s:131:"Image chameleon attack detected (%2Fhome%2Fuser%2Fpublic_html%2Fposts%2Fphotos%2F1187%2F3F7E7941-C6A2-4C4C-B3C2-0AAEF9723C75.png)!";}`

**Comment by Maikuolan** [comment]
That particular detection, "Image chameleon attack detected", occurs when the extension of the file being scanned indicates that the file is an image, and the file doesn't have the "magic number" expected of the particular indicated image format (in this case, PNG image format).

Typically, if you look at a PNG file using a text editor or hex viewer, you should see `‰PNG` (`0x89504e47`) at the very beginning of the file. If you look at the particular file being shown as infected, do you see that same data at the beginning of the file, or something else? If you see the same data, then it could be a problem with phpMussel, or a problem with the implementation somewhere. Otherwise, if you see something else, or don't see that same data at all, then it's possible that the file could have the wrong extension (maybe a different image format, and given the wrong extension by mistake), or could be something else, pretending to be a PNG file. (I'm also assuming, that the filename cited in the log entry, is the actual filename of the file which is being shown as infected; if the filename is something else entirely, then that could indicate some other kind of problem).

**Comment by Maikuolan** [comment]
*Marking as resolved and closing.*
