### ISSUE TITLE
2 testfiles (metadata_testfile) not detected

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#25]
The two metadata_testfile archives are not detected by phpMussel. Is this by intention or do I have to configure something?

Wrote now a small tool to automate the uploads and test many files at once. Will send you the final version of it in the next days.

**Comment by Maikuolan** [comment]
Definitely not intentional; Shouldn't need to change any configuration for it to work.

I've just tested it on my end, both using CLI and using a standard web interface, and can confirm the problem on my end.

It definitely was working in the past; I must've recently changed something that broke it by accident.

Marking this as a bug and looking into it now. Good spotting.

**Comment by Maikuolan** [comment]
Worked out what the problem was.

The newline character at the end of each signature line in the signatures was causing CRC mismatch during the archive metadata checks, because I hadn't coded to remove them during comparisons (I've done this for all the other types of signatures, but had omitted to do so for archive metadata); I think this bug may have actually always been there, but, because the `metadata_mussel.cvd` signatures file, until quite recently, only ever contained one signature, I'd never actually encountered this bug until now (no newline characters in a file that only has one line).

I've added in some `preg_replace` calls to fix it; Seems to be working locally for me now (both in CLI and in the web interface).

Let me know if it persists.

**Comment by DanielRuf** [comment]
Great. Thanks for the fast fix. 

I did not have the time to check the signatures as this was in the very late evening.

I will check this today again and close the issue and let you know, when this works on my end like it should.

I am sure it will work now but I will keep this issue open to remind me, that I have to test this.

**Comment by DanielRuf** [comment]
The two files are now detected, closing this issue.
