### ISSUE TITLE
add setting to block files which use steganography

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#27]
```
copy /b image.ext + payload.ext image_payload.ext
cat image.ext payload.ext > image_payload.ext
```

`decode_threshold=0` helps sometimes to detect appended files.

But we should add some setting to generally block files which have other files appended.
Because someone could append a (password protected) zip file to an image and extract this on the server.

Not all steganography methods can be (easily) detected, but some (like Stegdetect does) like appendx can be detected (and maybe added to the chameleon detection).

http://www.outguess.org/detection.php

I am currently evaluating what can be detected and solved. For example when we recreate/copy images using PHP (gdlib or imagemagick) it should remove (most) steganogryphic content.

We may also have to detect appended archive files (like it is used by sfx).
http://www.strchr.com/creating_self-extracting_executables
https://en.wikipedia.org/wiki/Template:Archive_formats

**Comment by Maikuolan** [comment]
I think this is a great idea (and I have thought so since back when the issue here was first created). But, I've tried researching this idea a few times now since back then, and I'm not sure whether it's something within my current capabilities and skills to pull off correctly. Plus, nobody else since then has tried it yet, either. I would like to see it happen, but realistically, I don't think it will end up happening, and this issue is now.. 5 years old. I think, in order to help clean up stale issues, I should go ahead and close it now.

Still feeling a "yes, please" towards this idea. :-)

But, maybe somebody can surprise with a pull request one day, or we can reopen it later if we find a start to start progress on it. Anyway, closing it for the moment.
