### ISSUE TITLE
add signatures for other webshells

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#29]
Some webshells are not detected.

I have tested around 1200 files and asp, aspx, ps1, jsp, cfm, cgi, java and so on are not detected, although there are (known) webshells using these filetypes.

I have used the repositories here:
https://github.com/stars/DanielRuf?utf8=%E2%9C%93&q=shell

Some more:
https://github.com/Neo23x0/Loki/blob/master/signatures/thor-webshells.yar
https://github.com/Neo23x0/Loki/tree/master/signatures

**Comment by Maikuolan** [comment]
Good finds. :)

I'll have a look at them all during the week to try to come up with some new signatures for them.

Also, I've received the undetected files that you'd sent via email and I'm in the process of writing some new detections for those, too.

**Comment by DanielRuf** [comment]
updated first post with 2 more links

**Comment by Maikuolan** [comment]
Cheers. :-)

**Comment by Maikuolan** [comment]
*(Copy/paste of the reply I just wrote for #56):*

Has been stale for 3 years. Realistically, probably not going to progress further with this due to lack of time, continuous evolution and emergence of new webshells which would require constant, regular attention to keep on top of and so on (and working on something *forever*, which we already don't have enough time for, isn't a good strategy). We've also moved signatures out to their own, dedicated repository since after this issue had been first created (so, any changes specifically related to signatures, could probably go there; but this issue predates that anyway).

Further work with "normalisation" and "decoding" of data could help a little here; maybe finding a way to tokenise PHP code, and then just scan for specific series of tokens to determine the presence of webshells, might be the best way to proceed (and that way, we wouldn't need to worry so much about which specific webshells we're looking at and such). But anyway, such things should have their own, dedicated issues, and aren't strictly related to this issue.

Marking this as *Abandoned* and closing.
