### ISSUE TITLE
detect PGP encrypted strings

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#30]
Just some idea. What if more webshells and malware use PGP and hide the actual payload with it, it would help to detect PGP encrypted strings and block the upload (if set).

Taken from https://de.wikipedia.org/wiki/Pretty_Good_Privacy#Aussehen_einer_verschl.C3.BCsselten_Nachricht

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v2.0.16 (GNU/Linux)

hQEMA1PUVhZb8UnsAQf+KS9PNvkWYFONnoStveMc4KwvGT7WlRFv/ZACvdyFsKDO
icurhL57uh56KCof1m5drfftwjDQWgNyMy0cixqV/2WzeQgjZILE0Z1FDg7cgAbs
UZvy2hmaJf0dhHEUziALotfUMhoSeHeObxmomzb7vovJv5tWDtQ9W+p2tbQ4tiin
LAsJtwQhEVPNltootBteC0dTgOdISe6kfqUSoN3A22SiSUihmjxMPiiO6iZB8gBS
hhfiSPa4khNwODncRe2BjqW+YQHf7L6CfLjx2S1BCSr+KWLmUnVdWSUonhHPF9mI
E/q7t2uoBWg0iQgCjQubgYeqSUYN/xWpqAUX9O71zdKUAbVjjLVT0qTjNLLvms2H
s4BDzHEqKeuGuMAWFzyfuW+VNofTxtcHhzrdjPuYi7sRL3YNUvqUpcGeKGyTApW2
k/fd7U32av7Pq63NoKK2g3RFcyBUiSdNlNhW8TYS1NdMSMXNw1R9dWVgFmsLj2vs
Rv89ufRiPbNLDXcx7CkRrTf13q0miy1850d6k5nt8qUFrnh4xQ==
=z6Xk
-----END PGP MESSAGE-----
```

If this is decoded, we can test / see if it is encrypted with PGP and therefore suspicious.
http://www.oktay.de/decode/base64.htm

Because some webshells use PGP

**Comment by Maikuolan** [comment]
True.

Although difficult to decode without the relevant private keys, detecting that it is in fact actually encoded in and of itself should be very easy to do.

**Comment by DanielRuf** [comment]
Right, you can try it yourself with Cleopatra (Gpg4win) on Windows to encrypt files and decode the PGP headers (which are not encrypted) on the website.

Reference about the PGP header: https://tools.ietf.org/html/rfc4880#section-4.2

**Comment by Maikuolan** [comment]
A kind of simplistic implementation, and quite late in getting it done, considering when this was first suggested, but, as of the latest commits to the main package + signatures (commited a few minutes ago), it should be possible to detect and block PGP-encrypted files. :-)

Currently, when the `detect_encryption` directive is enabled, to detect and block these files, it just checks for "----BEGIN PGP" in the file content and checks for the .pgp file extension, and if either of these two things are present, the file will be blocked. We can expand on this if neccessary, but those two indicators alone should catch most PGP-encrypted files, I think. It's possible that some people might strip the PGP header in order to circumvent this and just send the BASE64 data by itself, but if they do that, I'm not entirely sure whether we could distinguish it from other, normal BASE64-encoded data anyhow.

Anyway, I'll close this for now, but we can reopen it if there are new suggestions and ideas for it, or if we determine that further work needs doing.

**Comment by DanielRuf** [comment]
That's fine =)
