### ISSUE TITLE
stop scan when high load (DoS)

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#31]
We can check the current load on Linux and others using `sys_getloadavg()`. Windows is much more complicated. I am still trying different solutions for Windows.

When I start multiple uploaders at once, phpMussel runs much slower and still processes all uploads.

We should add some options like max_execution_time, get_server_load and check memory usage (if possible?) and stop the further execution to prevent DoS.

If PHP_OS or php_uname() contains WIN use another solution
http://stackoverflow.com/a/1482271/753676

`sys_getloadavg()` for non-Windows
`$load = sys_getloadavg()[0]; // last 1 minute`

http://php.net/manual/de/function.sys-getloadavg.php

Edit: it seems this does not work on all Linux platform (for security reasons) but we need some protection for sure.

@Maikuolan Do you have some ideas, how a protection against this problem (too many uploads at once making the server slow) could look like?

This is still a problem, that we have to look at but I have not yet the ideal solution.

**Comment by Maikuolan** [comment]
Yeah, this is a problem. There are some small things I've done before to help reduce the risk of this, but the risk definitely still exists.

I haven't found an ideal solution yet either, but I'll look into it, too.

Hopefully we'll work something out.

**Comment by Golpha** [comment]
I do not recommend to let phpMussel interop with server load issues ( created by DoS or dDoS attacks ). Load is something that should always be controlled outside the php scope ( load balancing, DoS shielded gateways ) otherwise you waste a lot of script execution time ( finally performance ) to just compile a superset of variables for the current environment to determine if the current server load might be the result of an attack or the result of an "just periodically busy server".

**Comment by DanielRuf** [comment]
@Golpha You are right. 

But how to handle it when the procession of the file uploads with phpMussel creates to much load like in the loadtests? 

This seems to be an issue which is theoretically caused by phpMussel when many files are processed at the same time.

Tweak the performance of phpMussel (scanning) in general to reduce the load created by it?.

**Comment by Golpha** [comment]
I dont think that phpMussel should negotiate upload processing. That is something that should be implemented with performance in mind when **using** phpMussel as a component. Userland-Hooks should not abort an upload due to a possible lack of resources that is calculated by a limited set of data in a "one of many" case.

**Comment by Maikuolan** [comment]
Fair enough.

Either way, whether or not this is something we wanted to do.. We've had the issue listed since June last year, and I haven't yet found any reliable and non-compromising way to actually do this without potentially introducing complications.

Maybe I should add the "wontfix" label and close it? Thoughts?

**Comment by Golpha** [comment]
I would suggest a client-side upload stack to prevent performance gaps at the server. Its more an architectural issue that needs an alternative solution instead of an entirely not fixable issue. 

But whatever we provide is nothing that would work on any hosting platform ( specially without shell access to start services to engage scanning queues with long-polling based feedback to the client ).

**Comment by DanielRuf** [comment]
> Maybe I should add the "wontfix" label and close it? Thoughts?

I think this would be good. When there are bottlenecks like the IO, RAM and CPU of the server, we can not do much (without shell access) so this should be solved in the server architecture like @Golpha says, we can not control this.

Maybe we should mention that the server should handle overload and related issues with big scripts which process many files.

Theoretically the upload loadtesting would be a DoS which may affect all PHP scripts out there, not just ours. But we should improve the overhead of phpMussel which adds to the loadtime for sure.

> But whatever we provide is nothing that would work on any hosting platform ( specially without shell access to start services to engage scanning queues with long-polling based feedback to the client ).

Right, this is one of the problems we already identified. I just thought that we can maybe control it a bit but like you said without shell access and the required commands, we can not do much. This should be handled by the actual hardware stack.

I just had some hope that we could add some checks to control this a bit but shell access is just here available not on all these cheap masshosters.

**Comment by Maikuolan** [comment]
Hm, a tricky problem.

If we could develop some solutions like this, it would be advantageous to whoever uses phpMussel and is able to use these solutions, and so, would be good to do; At least, as something optional or extra.

Of course, adding anything as a requirement that won't work for hosting platforms (dependencies, extra binaries, etc) could cause phpMussel to lose its edge and one of its primary advantages over other AVs (that it can be installed and executed on any PHP+PCRE environment without needing things like dependencies, extra binaries, shell access, etc), and so, I think, these things would need to be optional additions, rather than requirements.

(Of course, also, I would suggest to anyone using phpMussel on a hosting platform - especially if on a shared hosting environment - to carefully optimise their installation, so that they're only using what they need; eg, if they don't need to upload PE files, they can blacklist those filetypes, maybe add some custom signatures to block specifically the magic numbers of those filetypes, then, dump all the included PE signature files, which won't be needed for their installation; systematically repeat for whatever they do and don't need; things like that. There are ways to prevent these problems when careful optimisation is done, but, still, very difficult to standardise a recommendation like this, due to to differences in the specific needs of different users).

**Comment by Golpha** [comment]
As i told, there is in the most of all cases a solution. A client-side upload-stack, that does upload one file after another, could fix those things and react on slow responses. Not everything must be handled on server-side.

**Comment by Maikuolan** [comment]
True, and good point.

**Comment by DanielRuf** [comment]
We could add some file with timestamps of the uploads and such things (I think we have this discussed before @Maikuolan ?) to check if we have to throttle it a bit.

**Comment by Golpha** [comment]
A proper configured common server should handle hundred of uploads at a time and has technically just bottlenecks in case of bandwidth limits. I currently cannot figure out how a timestamp would help here. Concurrent uploads shouldn't be avoided.

But i have to mention that i have no practice with multi-upload performance optimization. We should investigate here before labeling it "wontfix".

**Comment by DanielRuf** [comment]
@Golpha you can easily test/simulate it with JMeter

https://github.com/Maikuolan/phpMussel/issues/40
https://github.com/DanielRuf/phpMussel-extras/tree/master/Benchmark

**Comment by DanielRuf** [comment]
At least further optimisation of the overall performance and resulting overhead should mitigate this in some cases. 

When I think about other websites who process file uploads (conversion and other related stuff) this problem also exists there as far as I could test this with custom scripts and loadtesting frameworks using concurrent uploads.

**Comment by Maikuolan** [comment]
Issue is super stale now (no further progress since 2016). Marking as "Won't Fix" and closing (need to get rid of some of these stale issues and clean up the issues page a bit, plus realistically, probably won't ever get around to sorting this one out, I think).
