### ISSUE TITLE
list phpMussel on public software repositories

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#33]
I am currently collecting some websites where phpMussel is missing and can be added (just links to the phpMussel website, repository and so on):
- [x] [AlternativeTo.](http://alternativeto.net/software/phpmussel/)
- [ ] [en.wikipedia.org](https://en.wikipedia.org/w/index.php?search=phpMussel)
- [ ] [heise.de](http://www.heise.de/download/neu_af?lang=e)
- [x] [hotscripts.com](http://www.hotscripts.com/listing/phpmussel/)
- [ ] [PHP Classes](http://www.phpclasses.org/browse/class/78.html)

I don't know if phpMussel should be listed on all of these websites (I will collect some more in the future).

This list is just meant as a help to create and track future listings.
I would say at least Wikipedia and alternativeTo. I will help with the creation of the listings when needed.

**Comment by Maikuolan** [comment]
Awesome, sounds good. :-)

**Comment by Maikuolan** [comment]
I've got it listed at [hotscripts.com](http://www.hotscripts.com/listing/phpmussel/); I don't think it's listed on the others yet though.

**Comment by DanielRuf** [comment]
@Maikuolan Awesome =)

Right. alternativeto (and others) needs some information and I had no clue / was a bit unsure what to enter in some fields.

**Comment by DanielRuf** [comment]
It seems some suggest using a PAD file, never heard about this before but it seems this is widely used.

https://translate.google.de/translate?sl=de&tl=en&js=y&prev=_t&hl=de&ie=UTF-8&u=https%3A%2F%2Fde.wikipedia.org%2Fwiki%2FPortable_Application_Description&edit-text=&act=url

http://padsites.org/
http://padsites.org/pad/?orderby=1&query=&pagesize=2&category=all&lng=0

This seems interesting:
http://padsites.org/submit_software
http://robosoft.rudenko.com/

**Comment by Maikuolan** [comment]
I've never heard of this before, either.

I'll take a closer look at this when I get home from work later today.

**Comment by DanielRuf** [comment]
> I've never heard of this before, either.
> 
> I'll take a closer look at this when I get home from work later

So I am not the only one who never heard of this :D 

Ok. I tried the trial of RoboSoft and so far this seems to be very helpful to manage the listing of phpMussel on multiple download sites.

**Comment by Maikuolan** [comment]
> Ok. I tried the trial of RoboSoft and so far this seems to be very helpful to manage the listing of phpMussel on multiple download sites.

Cool. :-)

**Comment by Maikuolan** [comment]
I'd neglected this for far too long now.

Just now, I've registered phpMussel with [alternativeto.net](https://alternativeto.net/software/phpmussel/); Hopefully, it should be approved there soon.

Will look at others shortly.

**Comment by DanielRuf** [comment]
Great =) Will check when they have approved the entry and update the initial post.

**Comment by DanielRuf** [comment]
Added PHP Classes and updated alternativeTo as they have approved phpMussel.

**Comment by Maikuolan** [comment]
Attempted to add phpMussel to the PHP Classes website, but something went wrong when trying to import the repository there (affects some, but not all projects; attempted to add CIDRAM there too, which was affected by the same problem; attempted to add my "Common Classes Package" repository there, and that one went through without any problems, and got approved within a few hours). Talked with Manuel about it, and he's already aware of the problem (seems to be effecting some other projects too), and is in the process of sorting it out. Anyway, we should be listed there reasonably soon, I think.

**Comment by Maikuolan** [comment]
No more word from PHP Classes yet since my previous reply.

Probably won't ever be listed on Wikipedia, due to the continual need to justify the package as being relevant and whatever else to moderators/editors/etc, which I don't really want to deal with TBH. Probably wouldn't be good coming from me anyway, due to being the original package author (might just look like yet another programmer wanting to spam/advertise their work on Wikipedia if it comes from me; probably would hold more weight if it came from a user, or from someone that isn't actively working with the project, I think).

As for heise.. I'm not really entirely sure how things actually work over there, how things get listed and such.

HotScripts was actually completely dead for a few years (which is why I pulled their badge from the [phpmussel.github.io](http://phpmussel.github.io/) page), but seems to be back online again now.. weird. Not sure what was going on there, but I guess, we have that listing again now.

Anyway, I'll mark this as implemented due to partial implementation. Closing because super stale. We can still list phpMussel at any relevant places we find though (more listings is always good), and if anything needs to be discussed, we can just create a new issue for it again.
