### ISSUE TITLE
test cases for PHPUnit

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#45]
I have started creating test cases for PHPUnit. This issue is for reference and contains a first example. Should we add unit tests to phpMussel?

```
phpMussel-tests.php
<?php
include 'phpMussel.php';
class MaliciousTest extends PHPUnit_Framework_TestCase
{

    public function testIsMalicious()
    {
        // Arrange
        $a = phpMussel("_testfiles/ascii_standard_testfile.txt");
        // Assert
        $this->assertEquals(2, $a);
    }

}
```

**Comment by Maikuolan** [comment]
Could be useful for future developers and could useful for those interested in PHPUnit, but, putting it directly into the main working directory or other currently existing directories elsewhere might confuse those that don't know what it's for or those that aren't developers.

Maybe something like an "extras" directory (`_extras` or something like that) should be created (for things that aren't essential code or signature files like the things in `vault`, that aren't documentation like the `_docs` data and that aren't testfiles like the `_testfiles` data, but which might still otherwise be useful)? If we created an extras directory, I can think of some other things to possibly throw in there too (for example, branding files like the 48x48 icon that phpMussel displays on the SourceForge page).

What do you think?

**Comment by DanielRuf** [comment]
This sounds very helpful. We can make an extra branch for this and place the extra files there or make a second, special repository for this and use a git submodule (the main repository) or just the extra files for example http://git-scm.com/book/en/v2/Git-Tools-Submodules

So we can place additional ressources, tests, reports and much more which is not part of the main repository and sourcecode.

**Comment by Maikuolan** [comment]
Sounds good; I like that idea. :-)

A good excuse to experiment with submodules, too; Something I've been curious about for a while but hadn't yet had much reason to explore.

**Comment by Maikuolan** [comment]
Added the file.

I've read some of the documentation, and I'm not sure how easy/difficult it'd be to do submodules from within Github for Windows. Doable from Powershell, of course, but, ideally, doing it from Github for Windows would be better for me (because that's what I'm syncing my commits from).

If I created a submodule using Powershell, I'm wondering, also, whether that'd conflict with Github for Windows (and if it'd cause problems for syncing future commits to/from the repo).

Have you tried it before?

**Comment by DanielRuf** [comment]
Are you using Git bash? Git submodules should work on all platforms. Powershell is not needed at all.

http://stackoverflow.com/questions/5252450/using-someone-elses-repo-as-a-git-submodule-on-github

Submodules are in fact a bit more complex as we have to update them on the local computer / client (which is the pull request for normal repositories).

http://git-scm.com/docs/git-submodule

> When cloning or pulling a repository containing submodules however, these will not be checked out by default; the init and update subcommands will maintain submodules checked out and at appropriate revision in your working tree.

https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

Theoretically it is just a link to another repository with the URL to it, which can be embedded, something like a Windows LNK / shortcut but with checkout / update and so on (independent of main repository where it is included).

> Submodules are composed from a so-called gitlink tree entry in the main repository that refers to a particular commit object within the inner repository that is completely separate. A record in the .gitmodules (see gitmodules[5]) file at the root of the source tree assigns a logical name to the submodule and describes the default URL the submodule shall be cloned from.

**Comment by Maikuolan** [comment]
*Closing in favour of #92 + Travis-CI has since been implemented, which utilises PHPUnit.*
