### ISSUE TITLE
lang.inc suggestions

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#48]
Should we move this to the phpmussel.ini file?
https://github.com/Maikuolan/phpMussel/blob/master/vault/lang.inc#L66

Also would it not be better to allow dynamic addition of additional langiages just by dropping the specific lang.inc file into the lang directory?
We can get the filenames and languages using something like `glob()` with some callback filter.

https://github.com/DanielRuf/phpMussel/blob/master/vault/lang.inc#L71
I also think that this big if-else statement can be minified into one line (or at least some switch-case statement) and that the language is used as a variable instead of the full filename for each language.
Because when we add more languages in the future, we have to keep this in mind and change multiple PHP files accordingly.

**Comment by Maikuolan** [comment]
Yeah, we probably should. As standard, configuration information should always been defined using `phpmussel.ini`, and shouldn't be hardcoded; I forgot to do that when I wrote that line. That can be fixed easily, though.

I'm somewhat apprehensive about switches, because I've experienced very strange behaviour with them in the past (whether this apprehension is justified or not, I'm not sure), but I agree that it [the `lang.inc` file] isn't coded as best it could be at the moment; I think minifying it would be a good idea, or, possibly doing away with those if-else statements entirely; Because language data is now segregated by language into separate files, those if-else statements mightn't be necessary anymore, anyhow; Partly, the if-else statements exist for the localised error messages for when the language data file desired isn't available, but mostly, the if-else statements are just an old left-over from when everything was in the one file, prior to segregation (and those localised error messages aren't likely to be useful unless someone goes messing around with the files in weird ways, anyhow).

**Comment by Maikuolan** [comment]
Committed some related changes (https://github.com/Maikuolan/phpMussel/commit/89652ac997b5e917f359a15c4367a65fd8a7f979).

**Comment by Maikuolan** [comment]
The if-else statements have been removed, and, although I've not implemented any sort of callback function, strictly speaking, it should still be possible to call a language file just by dropping the language file into the `/lang/` directory and then defining that language with the `lang` directive, or (if `lang_override` is enabled) dropping the language file into the `/lang/` directory, adding its code to the `lang_acceptable` directive and then having the browser define that language as the preferred language.

What's your thoughts on it at the moment? I could have phpMussel iterate though the `lang` directory to determine which languages should be acceptable as a way to avoid the need for the `lang_acceptable` directive, but, I figure if anyone is going to add or remove a language to/from the `lang` directory, they'll already have access to the configuration anyhow and presumably have at least a partial understanding of the code structure and how the configuration works, so, they could easily add/remove an entry to/from `lang_acceptable` at the time of dropping the file, and this would save the small amount of additional processing time that'd be required by iterating through the directory to determine these values automatically.

**Comment by DanielRuf** [comment]
> they could easily add/remove an entry to/from lang_acceptable at the time of dropping the file, and this would save the small amount of additional processing time that'd be required by iterating through the directory to determine these values automatically.

Right. This should be ok. Adding some autmatic scanning of the language files in the directory would decrease the performance. And decreasing the performance is not what we want. The disadvantages would outweigh the advantages.

I think so far this should be enough, everything what is needed is there in the configuration and if someone works on additional language files, this should be clear that the lang_acceptable directive has to be modified / updated to support the new language.

In my opinion we can close this issue.
