### ISSUE TITLE
no more phpMussel($what_to_scan,2)?

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#50]
There was an option for saving the result into a global variable (what is the name of it?) using 2 as value
https://github.com/Maikuolan/phpMussel/blob/master/_docs/readme.en.md#3a-how-to-use-for-web-servers

But it seems this was removed?

Before:
https://github.com/Maikuolan/phpMussel/blob/3ab6285dc2657ab9167bf58186e2d9924c9d5411/vault/phpmussel.inc#L860

After:
https://github.com/Maikuolan/phpMussel/blob/41dd96faee05f5402a117083d8f5fde9a32f62cd/vault/phpmussel.inc#L9957

**Comment by Maikuolan** [comment]
Kind of the reverse of that, actually; Whereas previously, saving the result into a global variable could be opted for with `2` (and wouldn't occur with `1`), now, it just always saves the result into a global variable, regardless of whether `1` or `2` is used.

The `$fm` variable was used to tell phpMussel whether it should save the results to a global variable, but has been removed from the core code. This was done as a fix for issue #44,  because doing so ensured the results would always be the same when saving to the cache, but I didn't account for what had been documented when I removed that variable (so, at the time, because removing this variable fixed #44, it seemed like a good idea, but because I didn't account for what had been documented, in hindsight, it could be a problem). I actually remember, when I was looking at the code and thinking about ways to fix that issue, thinking to myself, "Why would I code this to -not- save the results to a global variable? Shouldn't this be safe to remove? Seems to work without it.. Removing this should be okay." */Facepalm*

I'm not sure what it would suggest, when I forget my own code, or why I coded something; Probably nothing good.

I think I may need to code in some sort of new check, to ensure backwards-compatibility and conformity with the documentation. 

Anyhow, glad you spotted this! The default functionality of phpMussel shouldn't be affected (because all default calls to phpMussel were already using `2` anyhow), but I don't want to invalidate my own documentation, so, I'll think of a way to fix this soon.

**Comment by DanielRuf** [comment]
Ah ok, in my opinion this makes much more sense now than before.
So just the (default) behaviour changed (which is not addressed in the documentation so far).

The global variables are `$GLOBALS[xfm]` and `$GLOBALS[xsk]` as it seems (which is not quite clear from the documentation where these variable names are not mentioned)?
`to export the results to a global variable.`

**Comment by Maikuolan** [comment]
Yeah, it isn't mentioned anywhere in the documentation, but those are the two global variables that it saves the results to.

I started writing a functions list yesterday and plan to start a variables list soon, too; There's a few things like this that aren't thoroughly documented yet; Hopefully it should help a little when those are done.

**Comment by DanielRuf** [comment]
Ok, please let me know when there is something new so I can help you with the documentation and translations.

Take the time you need for it. We have many things on the roadmap which will improve the performance, stability and overall quality and I have planned some things to drive more users to phpMussel, find new contributors and much more. I will let you now when I have something for you regarding this.

Sure, this would be very helpful when we have this (the functions and variables, and much more).
Maybe adding some inline documentation and using tools like phpDocumentor would be helpful for future contributors.

https://en.wikipedia.org/wiki/PHPDoc
http://www.phpdoc.org/
https://github.com/phpDocumentor/phpDocumentor2
( https://github.com/doxygen/doxygen )

You can use todo, deprecated and other keywords with this and much more.

But this (documentation of the sourcecode for example for plugin system in the future and other things) is not important at the moment and so is much later in some roadmap I have in mind. First we have to improve the overall stability, quality and performance before making the next big steps. Or how do you see it? These are just some ideas and opinions I have.

**Comment by Maikuolan** [comment]
Yeah, I'm thinking the same; Ultimately, quality and performance are the things that users are going to care about the most; Good documentation is important, too, of course, but for most users, imperfect documentation is more tolerable than imperfect quality and performance.

**Comment by Maikuolan** [comment]
..Thinking on it a bit more, I wonder how important this is? Maybe, rather than having the three options (`1`, `2`, `3`), we just stick with the two (so, rather than trying to code back in some sort of check for whether or not to set these global variables, I just update the documentation to comply with the current behaviour and be done with it)? It might be partially backwards-incompatible by way of the behavioural change, but, it does seem to work better without the three options, would make it simpler, and would save the time and hassle of finding ways to make it work without then potentially breaking something else in the process of it. I'm not really sure how many users would be likely to be actually using the various different options at this point anyhow.

What do you think? :?

**Comment by DanielRuf** [comment]
In my opinion the two options, instead of three, are much better (eg for future plugins) and changing the documentation seems to be the best solution. I did not benchmark this but this might not have a big impact on the performance but makes integrating phpMussel using its results with the globals much easier.

**Comment by Maikuolan** [comment]
Good points there, too.

I think, then, that we'll just use the two options, instead of three, and I'll update the documentation to reflect this.

**Comment by Maikuolan** [comment]
@DanielRuf: Although I haven't yet finished the Dutch translations (which I suspect I haven't done a particularly good job of thus far anyhow, and also still needs a lot of work overall), the documentation has otherwise now been fully updated to comply with the changes and an entry has been added to the `change_log.txt` regarding the changes; I'll remove the Work-In-Progress tag. I think this issue should be safe to close now, but, is there anything you can think of that might've been missed (regarding this issue)?

**Comment by DanielRuf** [comment]
I think this can be closed. So far I did not find anything what we might have missed.

When I have created the first unit tests, testing should be much easier (just run the PHPUnit tests and see if none of them fails).

**Comment by Maikuolan** [comment]
Awesome. Closing now. :-)
