### ISSUE TITLE
composer.json and Packagist

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#73]
I think it makes sense to create a simple composer.json file and publish the package on https://packagist.org/

```
{
    "name": "Maikuolan/phpMussel",
    "description": "PHP-based anti-virus anti-trojan anti-malware solution.",
    "require": {
        "php": ">=5.3.0"
    }
}
```

I am not sure on the required PHP version.

See here for more details on the required PHP versions: https://github.com/Maikuolan/phpMussel/issues/8

**Comment by Maikuolan** [comment]
I've read about the benefits of using composer, and I think it's definitely worth considering to do, but, I don't really have any experience with it, so, I wouldn't be entirely sure about the exact correct way to implement it.

If we could determine the correct required PHP version, would the example you posted above be correct for implementing composer (just replacing the "5.5.3" with the actual correct required PHP version and including that in the repo with the composer.json file)?

**Comment by DanielRuf** [comment]
Yes, this should probably right but I have to test it and and read the dos again. Composer is like Maven and other tools for managih dependencies.  phpMussel should have no other packets as dependencies but can then easily integrated and updated in Composer projects.

**Comment by DanielRuf** [comment]
You can use composer.phar on the CLI to create the file for you.

http://blog.grossi.io/2013/creating-your-first-composer-packagist-package/
https://getcomposer.org/doc/03-cli.md

So you can directly generate it and try it with the install command.

Some more documentation:

https://getcomposer.org/doc/01-basic-usage.md
https://getcomposer.org/doc/02-libraries.md
https://getcomposer.org/doc/04-schema.md
http://composer.json.jolicode.com/

https://getcomposer.org/doc/05-repositories.md
https://knpuniversity.com/screencast/question-answer-day/create-composer-package

**Comment by Maikuolan** [comment]
Cross-referencing the functions used by phpMussel against the [PHP5 changelog](http://php.net/ChangeLog-5.php) and against the [compatibility information](https://github.com/Maikuolan/phpMussel/issues/8) you'd posted back in May, I think, in theory, phpMussel should be capable of executing without crashing and without any critical problems, even from the `5.3.0` minimum compatibility requirement of composer.

I'm not sure if we should use that version or a later version, though, because, although phpMussel can be used from that version without crashing and without any critical problems, there are still some possible non-critical problems that could limit the effectiveness of phpMussel.

I'll list some of them here.

`gzdecode` is used by phpMussel to decode GZ compressed files, and as is, currently, without that function, GZ files can't be decompressed. Currently, as is, phpMussel does a `function_exists` check for `gzdecode` before attempting to use it, and if the `gzdecode` function isn't defined, phpMussel will just return the `scan_extensions_missing` message (meaning that it won't crash, but, it also won't be able to decompress the files):

```
                if(!function_exists('gzdecode'))
                    {
                    $GLOBALS['memCache']['scan_errors']++;
                    if(!$GLOBALS['MusselConfig']['signatures']['fail_extensions_silently'])
                        {
                        $GLOBALS['killdata'].=md5($in).':'.$eS.':'.$ofn.$GLOBALS['linebreak'];
                        $GLOBALS['whyflagged'].=$GLOBALS['MusselConfig']['lang']['scan_extensions_missing'].' ';
                        }
                    return (!$n)?-1:$lnap.$GLOBALS['MusselConfig']['lang']['scan_reading'].' \''.$ofn.'\' (GZIP):'.$GLOBALS['linebreak'].'-'.$lnap.$GLOBALS['MusselConfig']['lang']['scan_extensions_missing'].$GLOBALS['linebreak'];
                    }
```

The minimum PHP version required for `gzdecode` is `5.4.0`.

`hex2bin` is a function used extensively by phpMussel throughout the entire script, and, just like `gzdecode`, the minimum PHP version required for `hex2bin` is `5.4.0`. I wrote and implemented a fallback function for `hex2bin` last year, which can be used instead of the normally in-built function, if the normally in-built function isn't normally defined by the PHP version being used.

```
if(!function_exists('hex2bin'))
    {
    function hex2bin($str)
        {
        $l=strlen($str);
        for($n='',$x=false,$i=0;$i<$l;$i++)
            {
            $x=(!$x)?true:false;
            if($x)
                {
                $z=$i+1;
                $n.=chr(hexdec($str[$i].$str[$z]));
                }
            }
        return $n;
        }
    }
```

This fallback function works correctly, doesn't crash and etc, but, unfortunately, it's much slower than the normally in-built function, so, although it's okay for phpMussel to use this function, it will result in reduced performance, so, the normally in-built function is preferable, when available.

The `cli_set_process_title` function is used by phpMussel when executing in CLI mode, to set the title used for the prompt window, but, `function_exists` checks for this function are used before using this function (so that phpMussel can avoid using this function if it isn't defined). This function is a bells-and-whistles function, though, providing an improved aesthetic, but having no effect on performance and no effect on the level of protection provided, so, I don't think it's something to really worry about for the purposes of declaring minimum compatibility.

So, if we were to declare the true, absolute minimum version of PHP required in order to actually execute phpMussel without it crashing and without severe problems, errors, etc, the default `5.3.0` should, in theory, be acceptable. But, honestly, I wouldn't recommend anything lower than `5.4.0` for performance reasons and because of the minimum required version for the `gzdecode` function, and so, `5.4.0` could be considered a minimum version of PHP required for an acceptable level of performance quality.

This all assumes, of course, that I haven't missed anything; This is all from reading the aforementioned documentation and compatibility information provided and cross-referencing against the actual code of phpMussel, without doing any actual, real testing against the various versions of PHP.

The version of PHP I use on my development machine for when I make changes to the core code is `5.5.12`, so, I know for certain that specific version is okay.

**Comment by DanielRuf** [comment]
> But, honestly, I wouldn't recommend anything lower than 5.4.0 for performance reasons and because of the minimum required version for the gzdecode function, and so, 5.4.0 could be considered a minimum version of PHP required for an acceptable level of performance quality.

Right, and 5.3 is EOL and may have many security holes. http://php.net/eol.php
PHP 5.4 is not so old and still used but 5.3 is not supported anymore (and there were some breaking changes from 5.3 to 5.4 which at least do not affet us but poor written software not following guidelines).

In my opinion we should use 5.4.0 as minimum version.

**Comment by Maikuolan** [comment]
Seems to be working. :-)

https://packagist.org/packages/maikuolan/phpmussel

**Comment by DanielRuf** [comment]
Awesome =) Can we close the ticket?

**Comment by Maikuolan** [comment]
Yep, I think we're good. Closing now. :-)

**Comment by DanielRuf** [comment]
One last note: maybe you have to force update the tags / releases in the packagist UI so the releases appear on the overview page on the right side (manual update of the repository on packagist).

Should show something like `Importing tag ...`

**Comment by Maikuolan** [comment]
I tried doing that, but nothing seemed to be happen.

I also created a webhook for it, and both sides (GitHub and Packagist) are reporting that everything is working correctly, but, it seems to have no effect on the tags or version information.

Maybe I've done something wrong..? I'm not sure. Maybe it's the way I've versioned old releases (because of the old releases not following SemVer)..? :-/

**Comment by DanielRuf** [comment]
Lets see: https://github.com/composer/packagist/issues/606

http://stackoverflow.com/questions/23090338/how-create-version-of-a-package-on-github-and-packagist-php-specific

**Comment by DanielRuf** [comment]
Ok, new releases should appear on Packagist as there is the composer.json file already.

https://github.com/composer/packagist/issues/606

And it seems we have to use SemVer, you are right.

Good to know.

**Comment by Maikuolan** [comment]
Cool cool. I had been originally planning to switch to SemVer at `1.0.0` (as per described by the changelog), but, I guess we can just start from the next release instead (so, `0.9.0` instead of `v0.9`). Hopefully that'll fix it (I think ensuring that releases are properly listed is probably more important than the reason for waiting until `1.0.0` anyhow).

**Comment by DanielRuf** [comment]
Exactly, this improves also the workflow, the versioning and developers can directly integrate future phpMussel versions into their projects using Composer.
