### ISSUE TITLE
false positiv on normal php files (PHP.Shell.Function 00/01)

### ISSUE THREAD

**Issue by BugBuster1701** [phpMussel/phpMussel#76]
I upload a ZIP, in the ZP file is located the php file "popup.php", a file from the CMS Contao.
Result is:

```
Detected phpMussel-PHP.Shell.Function-00 (popup.php)! 
Detected phpMussel-PHP.Shell.Function-01 (popup.php)!
```

Log:

```
Tue, 17 Nov 2015 21:53:01 +0100 Started.
> Checking 'popup.php.zip' (FN: 11f74f6b; FD: dca3da56):
-> No problems found.
-> Reading 'popup.php.zip' (ZIP):
--> Success! Proceeding to check contents.
--> Checking 'popup.php.zip' > 'popup.php' (FN: b809e934; FD: 3194c5ca):
-> Detected phpMussel-PHP.Shell.Function-00!
-> Detected phpMussel-PHP.Shell.Function-01!
Tue, 17 Nov 2015 21:53:01 +0100 Finished.
```

When i rename the file in popup.php.txt, there is no error. Eh?

I can attach the zip here, if it helps you.

**Comment by Maikuolan** [comment]
If it's nothing sensitive and you can do that, it would definitely help. :-)

It seems the signatures being triggered probably need more refining, but, due to them being used to block a number of highly malicious shell scripts, I don't think I could remove them entirely (at least, not unless I can find a better way to detect these types of shell scripts).

I've actually had other unrelated false positives caused by these same two signatures in the past, so, I think, these two may be a little trickier to get the right balance for, but of course, the more information available, the easier this becomes.

Currently (not yet modified, and as is, at the time that this false positive was found), the "phpMussel-PHP.Shell.Function-00" and "phpMussel-PHP.Shell.Function-01" signatures, both, are written as so that they should trigger for the file being scanned:
- If the `$fileswitch` variable does -not- match "pefile" (this check was added in some time ago due to potential false positives being generated whereby certain files were recognised as being both PHP files and PE files simultaneously, which shouldn't ever happen; the `$fileswitch` variable is assigned prior to running through the normal code section for PE files, so, unlike the normal code section for PE files which checks files more thoroughly, the checks for the `$fileswitch` variable are much simpler; it will match "pefile" if the contents of the file being scanned begins with "MZ", the magic number for the header of PE files).
- If the `$is_not_php` check fails (the `$is_not_php` check will pass if, after removing any archive related file double-extensions [GZ, ZIP, RAR, 7Z, etc] {when and if such a double-extension exists}, the remaining/initial file extension of the file being scanned does -not- begin with PHP [so, PHP, PHP4, PHP5, will fail; ABC, ZYX, XXX, YYY, ZZZ, etc, will pass], -and- if, after normalising the contents of the file being scanned [removing all whitespace, removing all control-characters, converting to lowercase, etc], the contents of file being scanned does -not- contain the string `<?php`.
- If, after normalising the contents of the file being scanned, the contents of file being scanned -does- contain the string `<?`.
- If the `$fileswitch` variable does -not- match "ignore" (this check was added in to avoid false positives being generated specifically for phpMussel's own included `.inc` files, whereby some of these included files would trigger the signatures, due to the internal normalisation code having some similarities to the strings being targeted by these same signatures, and to avoid false positives being generated specifically for the README files and certain documentation, whereby, due to the phpMussel documentation containing some of the strings being targeted by these signatures, as human-readable examples specifically of what can be detected and blocked, when scanning the actual phpMussel documentation, it would be detected by these signatures; not a severe or critical problem, but an ironic potential nuisance nonetheless; it [the `$fileswitch` variable] will match "ignore" if the final file extension matches [case-insensitive] exactly `cvd`, `inc`, `md` or `txt`).

Then, for "phpMussel-PHP.Shell.Function-00", if the contents of the file being scanned (after normalisation) contains any of these strings:

```
 assert
 create_function
 eval
 exec
 passthru
 popen
 proc_open
 system
```

..Immediately followed by any of these characters:

```
 "$'(:;`
```

And, for "phpMussel-PHP.Shell.Function-01", in reverse to its (..)00 counterpart signature, if the contents of the file being scanned (after normalisation) contains any of these characters:

```
 "$'(:;`
```

..Immediately followed by any of these strings:

```
 assert
 create_function
 eval
 exec
 passthru
 popen
 proc_open
 system
```

**Comment by Maikuolan** [comment]
There are still some potential risks with using the `$fileswitch == "ignore"` check, due to the potential for someone to attempt to upload a shell script with one of the ignored file extensions (`txt`, `md`, `cvd`, `inc`), if they're able to then find a way to include it as PHP code (such as by exploiting a vulnerable `require` or `include` elsewhere on the site, or by tampering with `.htaccess` and etc), so, whether this check should be implemented, could possibly be argued in either direction, but, if a website is configured correctly, if these file extensions aren't being parsed by PHP (so, if the server is configured correctly for which applications should handle which files and etc) and if the website isn't using some software or CMS generally considered vulnerable (and of course, most commonly known CMS nowadays is reasonably secure, with ill-coded plugins, extensions, themes and templates being the primary culprit of vulnerabilities nowadays), in theory, it should be safe to use this check.

Checking for these strings in recognised PHP files, which can actually be executed, though, I think, is important, due to these being frequently exploited by hackers, malware authors, etc. Of course, unfortunately, many benevolent PHP scripts also use these functions, for innocent purposes, and that's where we have problems with these sorts of false positives being generated; The trick, of course, is striking the correct balance, in finding ways to better distinguish between malevolent use and benevolent use of these functions (and, the difficulty in finding that balance is one of the main reasons I think using FTP to upload these sorts of files is always a better idea, or, even temporarily disabling phpMussel while uploading these sorts of files, in order to upload them without them being detected, but, of course, unfortunately, many people won't/can't use FTP, and, with the direction that many CMS are heading towards nowadays, with uploading plugins/extensions directly through the frontend rather than through the backend, striking this correct balance will probably become more and more difficult in the future; it's also one of the main reasons, too, that I'm happy about PHP7 being released soon, due to PHP7 being more secure, changing the way that many of these functions work, where they can be called, even removing the functionality of some of them and etc).

**Comment by BugBuster1701** [comment]
ok, then is that the row with the problem in my script?
`System::loadLanguageFile('default');`

Here is the [ZIP file](http://goo.gl/iND8Mo).

**Comment by Maikuolan** [comment]
Yep, that's it. :-)

The primary reason for `system` being one of the strings to be blocked, is because of the security risks associated with the [system();](http://php.net/system) function of PHP, but, blocking classes with that name aren't the intention of these signatures, so, I think what I'll do, is split those two signatures into four signatures (have two that look for `system`, but not `:` or `;`, and then the other two that don't look for `system`, but continue to look for `:` and `;`), and that should, in theory, fix the problem.

I'll reply here again when the commit is ready (about half an hour or so).

**Comment by Maikuolan** [comment]
Committed. :-)

**Comment by BugBuster1701** [comment]
Looks good, thanks.
