### ISSUE TITLE
why message-> [phpMussel] Required variables aren't defined: Can't continue

### ISSUE THREAD

**Issue by netred** [phpMussel/phpMussel#79]

**Comment by DanielRuf** [comment]
Please provide more details.

How did you install phpMussel, how did you run it and most important which version do you use?

Did you already try to set the value of cleanup to false? https://github.com/Maikuolan/phpMussel/blob/94d6fbc51e857ae21a105cc390c00d857d8b9aac/vault/phpmussel.ini#L26

**Comment by Maikuolan** [comment]
This message..

> `[phpMussel] Required variables aren't defined: Can't continue.`

..occurs when the `$memCache` (or `$GLOBALS['memCache']`) variable is missing (this variable is an array containing information relating to any scanning in progress, such as detection information, details about the files being scanned, etc; it's expected and required by phpMussel whenever scanning occurs).

---

In the current codebase, the code for this message exists at the beginning of the primary scanning function (`phpMussel();`) and its two sub-functions (`phpMusselR();` and `phpMusselD();`):

```
function phpMussel($f='',$n=false,$zz=false,$dpt=0,$ofn='')
    {
    if(!isset($GLOBALS['memCache']))
        {
        echo (!isset($GLOBALS['MusselConfig']['lang']['required_variables_not_defined']))?'[phpMussel] Required variables aren\'t defined: Can\'t continue.':'[phpMussel] '.$GLOBALS['MusselConfig']['lang']['required_variables_not_defined'];
        die;
        }
```

```
function phpMusselD($str='',$n=false,$dpt=0,$ofn='')
    {
    if(!isset($GLOBALS['memCache']))
        {
        echo (!isset($GLOBALS['MusselConfig']['lang']['required_variables_not_defined']))?'[phpMussel] Required variables aren\'t defined: Can\'t continue.':'[phpMussel] '.$GLOBALS['MusselConfig']['lang']['required_variables_not_defined'];
        die;
        }
```

```
function phpMusselR($f='',$n=false,$zz=false,$dpt=0,$ofn='')
    {
    if(!isset($GLOBALS['memCache']))
        {
        echo (!isset($GLOBALS['MusselConfig']['lang']['required_variables_not_defined']))?'[phpMussel] Required variables aren\'t defined: Can\'t continue.':'[phpMussel] '.$GLOBALS['MusselConfig']['lang']['required_variables_not_defined'];
        die;
        }
```

---

This message should never normally occur during the default scanning of file uploads, but, it can occur during any subsequent scanning (such as when calling phpMussel functions from outside of phpMussel, such as from by the CMS or by the framework where phpMussel is installed) if any subsequent scanning occurs after phpMussel has already unset itself from memory (_this relates to the "cleanup" directive; information relating to this directive can be found in the documentation, under `6. CONFIGURATION OPTIONS` -> `"general" (Category)` -> `"cleanup"`_).

Normally, if `cleanup=true`, phpMussel will unset itself from memory the moment PHP has finished parsing it (the core script, `phpmussel.inc`, for most variables, including `$memCache`, and `phpmussel.php` for everything else). Changing the value of this directive as so that `cleanup=false` will prevent this (when `cleanup=false`, phpMussel won't attempt to unset itself from memory, and everything should just unset normally when PHP finishes executing the request).

If this is the situation for you (subsequent scanning occurring after phpMussel has already unset itself from memory), the solution would be to change the value of the "cleanup" directive to false (this should solve the problem).

If, however, this isn't the situation for you (no subsequent scanning occurring, or if "clean" is already false), we may require more information, in order to determine what has happened.

**Comment by netred** [comment]
Hi!, thank you very much, now with cleanup=false it run fine!!

**Comment by DanielRuf** [comment]
Thanks for the update, that it works now. Closing the issue as resolved.
