### ISSUE TITLE
Undefined index: eof in phpmussel.inc line 9050

### ISSUE THREAD

**Issue by rockyweng** [phpMussel/phpMussel#81]
I downloaded the code from master and I am getting the error Undefined index: eof [APP/vendors/phpmussel/vault/phpmussel.inc, line 9050].

This is my usage
$results=phpMussel($this->data['Resource']['file']['tmp_name'],true , true);
echo $results;
exit();

Notice (8): Undefined index: eof [APP/vendors/phpmussel/vault/phpmussel.inc, line 9050]

**Comment by Maikuolan** [comment]
Sorry to hear there's been problems with the code.

This particular problem is very unusual.

L9050:
`if($GLOBALS['memCache']['eof'])`

Currently, in master, the `EOF` index of `$memCache` is initially assigned at L97, as:

`$memCache['eof']=false;`

..And will be either unset or modified at L10388-L10389 (the actual EOF), as:

```
if($MusselConfig['general']['cleanup'])unset($cli_args,$r,$pedata,$killdata,$whyflagged,$k,$i,$c,$phpmusselsafety,$phpmusselua,$memCache,$inidefaults,$linebreak,$time,$phpmusselversion,$phpmusselversion_int);
else $memCache['eof']=true;
```

..Pending the value of `$MusselConfig['general']['cleanup']` (which is assigned based on the value of `cleanup` as per defined by the configuration in `phpmussel.ini`).

At first glance, considering the usage, I was thinking that the problem might've been because of an incorrectly assigned `cleanup` directive in the configuration, but, if `cleanup`was incorrectly assigned, based on the usage, the script should've been killed by L9045-L9049 (which should've produced an internal phpMussel error message, stating that required variables were missing), before PHP had the chance to find any possible error at L9050:

```
    if(!isset($GLOBALS['memCache']))
        {
        echo (!isset($GLOBALS['MusselConfig']['lang']['required_variables_not_defined']))?'[phpMussel] Required variables aren\'t defined: Can\'t continue.':'[phpMussel] '.$GLOBALS['MusselConfig']['lang']['required_variables_not_defined'];
        die;
        }
```

It shouldn't be unset or modified anywhere else in the script, and L97 precedes any other calls to the core `phpMussel();` function and precedes the function itself being defined, so, in theory.. This error message shouldn't be occurring.

I'll look into this further and let you know what I find.

Also, would I be correct in assuming you're using the code from master as verbatim, without any modifications?

**Comment by rockyweng** [comment]
Hi Caleb,

I didn’t change the coding in the library and I am using PHP 5.3. Is there anyway I can get it to work in PHP 5.3?
Thank you for your help.

**Comment by DanielRuf** [comment]
Generally PHP 5.3 (and even 5.4) have reached their end of life, means thee are no more (security) updates available by Zend.

5.4+ is required / highly recommended.

See the composer file: https://github.com/Maikuolan/phpMussel/blob/master/composer.json

I recommend switching to a current supported version like 5.5, 5.6 or 7.0.

PHP 5.6 would be good.

Not sure if this is some bug in 5.3.
Will check it too with a local WAMP stack.

**Comment by DanielRuf** [comment]
Can not reproduce this with WAMP stack 5.3.18.

``` php
error_reporting(E_ALL);
ini_set('display_errors', 1);
include 'phpmussel.php';
$results=phpMussel($_FILES['userfile']['tmp_name'],true , true);
echo $results;
exit;
```

`Wed, 20 Jan 2016 02:29:33 -0800 Started. > Checking 'C:\Bitnami\wampstack-5.3.28-0\php\tmp\phpC803.tmp' (FN: 6946a939; FD: ebaf141c): -> No problems found. Wed, 20 Jan 2016 02:29:34 -0800 Finished.`

**Comment by rockyweng** [comment]
Hi Daniel,

Thank you for your help. I am running phpMussel under MAMP environment. I tried to set the cleaup=false and it is still not working.

$GLOBALS = array();
require_once APP."vendors/phpmussel/phpmussel.php";
var_dump($GLOBALS);
$results=phpMussel($_FILES['data']['tmp_name'], true , true);
echo $results;

I tried to run this and I am still getting the same error message.

When I var_dump the $GLOBALS it only contains memCache element.
array(1) { ["memCache"]=> array(1) { ["CacheCleaned"]=> bool(true) } }
Notice (8) <>: Undefined index: eof [APP/vendors/phpmussel/vault/phpmussel.inc, line 9050]

**Comment by DanielRuf** [comment]
If cleanup is set to true, they scripts shows gives a different warning, that the variables are not set. So if this was set to true before and you did not get the warning, the problem may be the PHP version. I recommend upgrading to a newer version or install some current Bitnami MAMP Stack, you can install multiple MAMP stacks and use them all.

https://bitnami.com/stack/mamp/installer

$GLOBALS is set in the phpmussel.php fileso no need to define it.

Please test it with a newer MAMP Stack from Bitnami (5.6 or 7.0)

**Comment by rockyweng** [comment]
Hi Daniel,

When I tried to var_dump($GLOBALS) in phpMussel() function just before 
if(!isset($GLOBALS['memCache']))

It only contains array(1) { ["memCache"]=> array(1) { ["CacheCleaned"]=> bool(true) } }

Do you have any ideas about the $GLOBALS not being set in my system?
Thanks a lot for your help.

**Comment by DanielRuf** [comment]
I am not sure because I could not reproduce ge eof issue with the mentioned PHP 5.3 stack here.

@Maikuolan can you reproduce this?

**Comment by rockyweng** [comment]
Hi Daniel, 

I tried to run this under PHP 5.6 and I am getting the same error.

The $GLOBALS does not contain eof.

Here is my test code for your reference. Please let me know if I have done something wrong.
require_once '../phpmussel.php';
$results=phpMussel($_FILES['test']['tmp_name'], true , true);
echo $results;

Thank you for your help.

**Comment by Maikuolan** [comment]
The test code looks correct, and your usage seems correct, too, so, I don't think those are the problems; Most likely, there's some problem with PHP configuration, or possibly some conflict somewhere between addons, plugins, modules, etc.

Unfortunately, I haven't been able to replicate the problem on my end (yet, anyhow; I'll keep trying).

Very strange that `var_dump($GLOBALS)` isn't producing more information, because, regardless of phpMussel, PHP itself should be setting quite a lot of information to `$GLOBALS`.

Could you create a new PHP file somewhere on your system, containing this:

```
<?php
var_dump($GLOBALS);

```

..And let me know whether or not it's empty? There could potentially be sensitive system information there, so, you don't need to copy/paste whatever is there, if anything is there, but, it would be good to know whether this variable is being correctly populated by PHP.

**Comment by DanielRuf** [comment]
@ralph-ento Did you already try to reinstall a new MAMP version? I also think there is a configuration problem with your setup.

As an alternative, please try Bitnami MAMP Stack.

I tested with a current MAMP stack from https://www.mamp.info on Windows and I still do not get the mentioned notice. So I think it may be some issue with your (outdated) MAMP stack or its configuration.

And some antivirus does not cause this issue?

Please provide more details about the MAMP stack that you use.
Migrating to a newer version should not be hard. Just copy the htdocs content to the new one and export the database(s) from the old and import in the new one.

**Comment by Maikuolan** [comment]
@ralph-ento Any news? :-)

**Comment by rockyweng** [comment]
Hi Caleb and Daniel,

I managed to find the issue and the issue caused when I putting it inside the CakePHP controller.
I am not sure if cakephp is doing something to overwrite the $GLOBALS variable.

Thanks a lot for your help.

**Comment by Maikuolan** [comment]
No problem, and thanks for letting us know.

I don't personally have any experience with CakePHP, so, I couldn't confirm one way or the other; Definitely something worth looking into, though.

**Comment by bundun2002** [comment]
Hi Maikuolan,

I have been helping out Ralph and have got it working within Cake. 

Simply doing this at the end of phpmussel.php

```
    $variables = array(
        'vault',
        'MusselConfig',
        'disable_lock',
        'x',
        'MusselPlugins',
        'query',
        'phpmussel',
        'pword',
        'logspword',
        'musselvar',
        'phpmusselversion',
        'phpmusselversion_int',
        'linebreak',
        'time',
        'inidefaults',
        'phpmusselua',
        'memCache',
        'phpmusselsafety',
        'cli_args',
        'c',
        'pedata',
        'killdata',
        'whyflagged',
        'HashCache'
    );
    foreach($variables as $variable) {
        if (isset($$variable)) {
            $GLOBALS[$variable] = $$variable;
        }
    }
```

Not the most elegant solution though does seem to work (when cleanup=false). It seems to fail over a certain file size regardless of what I set `pcre.backtrack_limit` and `pcre.recursion_limit` to.

This is the line causing issues.

```
if (!preg_match('/' . $xsig . '/i', $str_norm) && !preg_match('/' . $xsig . '/i', $str_xmlxdp_norm)) continue;
```

Not sure if you have any further ideas? Appreciate your time too as well.

**Comment by Maikuolan** [comment]
No worries. :-)

To clarify, when you mentioned "fail", do you mean that there are errors produced by PHP, that phpMussel or PHP crashes, that there are missed detections, or something else?

**Comment by bundun2002** [comment]
Sorry should have clarified. Error reads Warning: preg_match(): Compilation failed: regular expression is too large at offset #######.

**Comment by Maikuolan** [comment]
Ah, okay; That makes sense now.

Because the actual regex patterns being used at the line in question come from the regex-based signature files, I believe the cause of that particular error is most likely a dodgy signature somewhere in one of the regex-based signature files.

I'll dig through the files to try to figure out which one is causing the problem.

**Comment by Maikuolan** [comment]
Hm, interesting.

Checking the current codebase, the longest regex-based signature currently in the signature files is <strike>1,026</strike> 1,116 bytes long.

_According to the **[PCRE specifications](http://pcre.sourceforge.net/pcre.txt)**:_

> The maximum length of a compiled pattern is 65539 (sic) bytes if PCRE is compiled with the default internal linkage size of 2. If you want to process regular expressions that are truly enormous, you can compile PCRE with an internal linkage size of 3 or 4 (see the README file in the source distribution and the pcrebuild documentation for details). If these cases the limit is substantially larger. However, the speed of execution will be slower.
> 
> All values in repeating quantifiers must be less than 65536. The maximum number of capturing subpatterns is 65535.

So, I'm back to square one with this, I think.

@DanielRuf Your thoughts?

**Comment by Maikuolan** [comment]
I'm not entirely convinced it was the cause of the problem, but, I've just synced a new commit for `vault/general_mussel_regex.cvd`, because there were 3 signatures in that file (including the aforementioned longest regex-based signature) that didn't have proper limits to the size of capture and subcapture groups, which could potentially lead to runaway backticking problems if left unchecked. I discovered the problem with these 3 signatures as a result of looking at the signature files because of this issue.

If PCRE is complaining about the length of patterns, it shouldn't be parsing them anyhow, and so, the runaway backticking problem wouldn't come in to play, and conversely, the size of captured data shouldn't necessarily affect or have anything to do with any issues to do with the actual length of the original pattern, but, it's something that needed to be fixed, anyhow.

If you download the updated file and try scanning again using that, let me know whether it fixes the problem (I suspect it won't, but, failing any other ideas for the time being, it's something to try, anyhow).

**Comment by DanielRuf** [comment]
I think we also had this issue with the regex in some unit tests.

https://github.com/Maikuolan/phpMussel-extras/issues/3#issuecomment-125038783
https://github.com/Maikuolan/phpMussel/issues/39

I would suggest opening a new issue for this as this is not directly related to the $GLOBALS issue, probably a problem with the regex pattern.

See http://stackoverflow.com/a/31173022

The compiled regex (the result set) may be bigger and hit the pcre limits in the php.ini.

http://stackoverflow.com/a/8269231

@bundun2002 Which values for the pcre configuration values did you try? Did you restart the server after settign them?

What would be a better approach? Improving the regex (should be possible) or setting the limits for PCRE (may fail and not be possible in specific environments).

**Comment by rockyweng** [comment]
@Maikuolan I have tried the general_mussel,regex.cvd from new commit and it didn't fix the problem and I am still having the same problem bundun2002 is experiencing. 

Thank you for your help.

**Comment by DanielRuf** [comment]
Please look for any related warnings or notices in your error logs regarding the problem with CakePHP.

Regarding https://github.com/Maikuolan/phpMussel/issues/81#issuecomment-174411094
@ralph-ento @bundun2002 I highly advise to open an issue at https://github.com/cakephp/cakephp/issues with all relevant details (CakePHP version, bootstrap file code, and so on).

We can not test and debug this without any further information like the used CakePHP version and if it is related to a bug in an old CakePHP version, an issue with the bootstrap file or framework itself.

@ralph-ento @bundun2002 did you try setting the limits to the values mentioned in the linked StackOverflow answers?

@bundun2002 the exact line and offset would be very helpful

> Sorry should have clarified. Error reads Warning: preg_match(): Compilation failed: regular expression is too large at offset #######.

**Comment by Maikuolan** [comment]
In `phpmussel.inc`, there are currently two matches for `if(!preg_match('/'.$xsig.'/i',$str_norm)&&!preg_match('/'.$xsig.'/i',$str_xmlxdp_norm))continue;` ([L4729](https://github.com/Maikuolan/phpMussel/blob/master/vault/phpmussel.inc#L4729) and [L5067](https://github.com/Maikuolan/phpMussel/blob/master/vault/phpmussel.inc#L5067)), so, I think it's one of those two he meant. In either case, though, if we're seeing the "`regular expression is too large`" error, the fault would be with one of the signatures somewhere (not sure which one, though; the offset could help with determining that).

I'm still thinking at this point there must be something external to phpMussel (such as CakePHP, or something else on the system) causing the original problem, due to the "`Undefined index`" error appearing without the script being killed (because the `EOF` index exists as an element of the `$memCache` array {`$GLOBALS['memCache']['eof']`}, the preceding `if(!isset($GLOBALS['memCache']))` check should've been triggered, and thus should've killed the script if this index wasn't defined).

**Comment by Maikuolan** [comment]
I think I -might've- found the signature causing this problem (a bit of a bastard to find, this one; the problem was replicated for me after I'd removed all error suppression from my local copy and tried scanning a few HTML files, which for whatever reason, seemed to trigger this one quite a lot; this signature doesn't -look- like it should be problematic, when looking it at in a text editor, but, after a lot of trial and error, and after manually disabling numerous other signatures one-by-one, the replicated problem eventually disappeared for me after disabling this particular signature):

```
 \x1A\x30\x23\x1B\x58-02:(0d0a){0,4000}4.4.4.3d224.7.3d3d:A
```

Anyhow.. I'll upload a new commit later today with this signature removed; I'll post here again after I've done so.

**Comment by DanielRuf** [comment]
What should this specific signature detect? Looks like shellcode / binary in hex format.

**Comment by Maikuolan** [comment]
I'd written it some time ago to detect some VBS-specific shells I'd encountered.

I'm still not entirely sure _why_ PCRE thinks that it's "too large", but, it's definitely a signature that was triggering these problems for me when I'd replicated the problem on my end.

Oh well. I can always re-explore adding some alternative signatures in the future to cover what it was intended to detect after finishing what's currently being worked on, so, it shouldn't matter too much if it's removed.

**Comment by Maikuolan** [comment]
Committed. :-)

**Comment by DanielRuf** [comment]
> I'm still not entirely sure why PCRE thinks that it's "too large"

This might answer it maybe: http://stackoverflow.com/a/33988643

http://www.rexegg.com/pcregrep-pcretest.html

If we take the pattern and concatenate it 4000 times, we will get a large regex.

`(0d0a)` for example has a length of 4, multiplied with 4000, we get 16 000 characters (multiply it with the size of each character - 8bit?), much more than the 64K (around 128K?). Or am I wrong?

Running this with pcre2test gives me this result:

```
PCRE2 version 10.21 2016-01-12
  re> /^(0d0a){0,2849}$/i,memory
Memory allocation (code space): 65530
```

2850 gives me this:

```
PCRE2 version 10.21 2016-01-12
  re> /^(0d0a){0,2850}$/i,memory
Failed: error 120 at offset 16: regular expression is too large
```

Lower values will give you 64K or less but 4000 seems to be to much.

**Comment by Maikuolan** [comment]
>  it may compile a state machine by copying part of the regexp 4000 times

That is a little scary, if PCRE is doing that.. I didn't know about this behaviour before. o.0

And this, if true, is even scarier/worse:

> My guess is that some regex like this:
> 
> (123){1,3}
> 
> is compiled to something like this
> 
> (123)(123)?(123)?
> 
> Which makes it bigger than the maximum length

If this is true, I may need to rethink all the regex signatures of phpMussel, in how they collectively express repeated substrings (most infinite quantifiers "*" and one-or-more quantifiers "+" were replaced with "{0,4000}" a few versions back, to deal with a different bug where PCRE would just backtrack itself into oblivion and crash PHP sometimes with certain large files, which could've potentially been exploited).

**Comment by DanielRuf** [comment]
The repitition quantifier is definitely the problem at least.

http://www.regular-expressions.info/repeat.html#limit

It just says how many times should the token appear (min, max) which seems to be internally expanded and compiled to the bigger version as PCRE as the compiled regualr expression is in most cases faster and used by PCRE.

**Comment by DanielRuf** [comment]
@ralph-ento @bundun2002 can you check the latest release (not the current master) if there are still related issues? I think this should be fixed as at least the one signature was removed, which caused this problem.

@Maikuolan we could mark future signatures in the database which are compiled larger than 65539 bytes (64K) and try to set / check the ini value for this. But the problem is mostly the underlying pcre library and the size of the regular expression. We should try to optimise them.

When we build the databases, we should check the signatures if they are successfully compiled or throw the warning about the size, which we can catch then.

**Comment by Maikuolan** [comment]
Definitely.

I've made some subtle changes to the scripts that I'd written and have been using for generating updates to the included ClamAV signature files (namely, reverting back to standard +/\* quantifiers in favour of the min/max quantifier, but including non-capturing `?:` for all sub-patterns and capture groups), and I'm hoping to do some more tests after generating the next update to see if it has any effect (ie, if there's any improvements, etc).

Hopefully (fingers crossed..), this will have the desired effect. The testing I've done so far (using the signatures from the current codebase) looks promising (no errors as far as I can tell), but these have been edited to conform to these changes manually, rather than via the updated generation scripts, so, won't know for sure whether these changes will have the desired effect until after I next run them and then run tests on the resulting signature files.

**Comment by Maikuolan** [comment]
Cautiously (at least, for now), marking this issue as fixed and closing it. The signatures have mostly been updated and replaced since this issue was last discussed in detail back in February (they're now using non-capturing groups and the original standard +/\* quantifiers), and I haven't encountered the problem again since we'd last encountered it, nor have I been able to replicate it again with the latest version of the signatures. With no further input from the users that'd originally opened this issue to suggest the contrary, I'm assuming that the issue is no longer persisting.

We can reopen this issue again later if we re-encounter the issue or if we determine that it hasn't been fixed.
