### ISSUE TITLE
ransomware detection

### ISSUE THREAD

**Issue by DanielRuf** [phpMussel/phpMussel#88]
Not sure if just web related or also desktop. The desktop variants (binary files) may bemuch bigger.
- [ ] CTB-Locker
- [ ] KimcilWare
- [x] ~~MireWare~~ (too many variants for dekstop)
- [x] ~~Locky~~ (too many variants for dekstop)
- [x] ~~Petya~~ (too many variants for dekstop)

the problem is that there are many different samples, also got many different Locky samples for example. But the web variants may be more interesting.

Will ask some of my contacts about more ransomwares for webservers, collect the samples and names and provide them (PGP encrypted).

Do you know a few more? I am a bit overwhelmed by the many new actors and different groups spreading their own ransomware, it's currently exploding here, AV vendors also have issues handling all the requests so many have a relatively low detection ratio (like 0-10 / 57).

Many hacked websites often host the Locky samples (the binary files) and other ransomware variants. So this is something where we could provide some protection.

**Comment by Maikuolan** [comment]
I've written a handful of signatures for a number of the desktop binaries variants of a number of these, but, due to how quickly new permutations appear and the impossibility of keeping up with all of these, generally, I'll just write signatures for those that I happen to come into possession of, I'll usually write PE sectional signatures and/or hash-based signatures for them (which catch less, and become redundant more quickly, due to being very specific, but are quicker and easier to write, too) and tend to not worry too much about actively seeking them out. Individual permutations tend to have rather short half-lives, too, due to how many individual permutations may be targeted towards specific intended victims and many of the creators of these binaries use toolkits to produce them en-masse, and so, after creating these new signatures, usually, I'll ditch them again after a year or so of keeping them in the signatures files, purging them along with other much older signatures regularly purged whenever too many new signatures are added and the database needs to be trimmed down a little.

The web varieties for many of these ransomware families, however, aren't usually so easy to come by, so, it would be really cool to be able to take a look at some of these, to pull them apart and figure out what's in them, exactly.

> Will ask some of my contacts about more ransomwares for webservers, collect the samples and names and provide them (PGP encrypted).

That would be great; Definitely would be useful to have some of these. :-)

> Do you know a few more? I am a bit overwhelmed by the many new actors and different groups spreading their own ransomware, it's currently exploding here, AV vendors also have issues handling all the requests so many have a relatively low detection ratio (like 0-10 / 57).

Yeah.. I can definitely feel that. It's pretty nuts, how much is coming out at the moment.

I'll take a look at my lists a little later tonight to try to see if there are any I can add to the list here.

**Comment by DanielRuf** [comment]
I guess we can close this issue here. There is now much more to detect than just a few ransomware samples (ransomware exploded in the last year(s)).

**Comment by Maikuolan** [comment]
Sounds good.

Probably a bit too much work for just the two of us, I think; Finding and processing samples is kind of a full-time job nowadays, with new permutations, malware families and so on coming out all the time.

I'll close this issue now.
